import { json } from '@sveltejs/kit';
import {
  deleteMediaRecord,
  listMedia,
  setMediaAlt,
  MAX_ALT_LENGTH,
} from '$lib/blog/media.server';
import type { RequestHandler } from './$types';

/**
 * The blog media library, owner-only.
 *
 * WHY IT LIVES UNDER /api/admin AND NOT NEXT TO THE IMAGES
 *
 * The obvious home is `/api/blog/images/`, beside the route that serves the
 * bytes. That prefix is PUBLIC — it has to be, or no reader could load an
 * image in a published post. Serving one asset to anyone who already has its
 * URL is fine; handing out the INDEX is not the same act. A listing endpoint
 * under that prefix would let the internet enumerate every upload against every
 * post, including drafts that have never been published and images pulled from
 * a post before it went out. So the listing sits behind the owner gate and the
 * bytes stay in front of it.
 *
 * No auth code here on purpose: everything under /api/admin is already gated in
 * hooks.server.ts, and a second check in the handler is a second thing that can
 * drift out of step with the first.
 */

/** A post id is a serial primary key; anything else is a client bug, not a query. */
function parsePostId(value: unknown): number | null {
  const n = typeof value === 'string' ? Number.parseInt(value, 10) : value;
  if (typeof n !== 'number' || !Number.isInteger(n) || n <= 0) return null;
  return n;
}

/**
 * Filenames are generated by the upload route (`<epoch>-<uuid8>.<ext>`) and are
 * only ever echoed back to us. Bounding the length keeps an absurd body out of
 * a LIKE-free equality lookup; the value never touches the filesystem from
 * here, so traversal is not the concern it is in the byte-serving route.
 */
function parseFilename(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > 300) return null;
  return trimmed;
}

async function readBody(request: Request): Promise<Record<string, unknown> | null> {
  try {
    const body = await request.json();
    return body && typeof body === 'object' ? (body as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

// GET /api/admin/blog/media?postId=
export const GET: RequestHandler = async ({ url }) => {
  const postId = parsePostId(url.searchParams.get('postId'));
  if (postId === null) {
    return json({ error: '`postId` must be a positive integer.' }, { status: 400 });
  }
  return json({ media: await listMedia(postId) });
};

// PATCH /api/admin/blog/media  { postId, filename, altText }
export const PATCH: RequestHandler = async ({ request }) => {
  const body = await readBody(request);
  if (!body) return json({ error: 'Body must be JSON.' }, { status: 400 });

  const postId = parsePostId(body.postId);
  const filename = parseFilename(body.filename);
  if (postId === null) {
    return json({ error: '`postId` must be a positive integer.' }, { status: 400 });
  }
  if (filename === null) {
    return json({ error: '`filename` must be a non-empty string.' }, { status: 400 });
  }
  if (typeof body.altText !== 'string') {
    return json({ error: '`altText` must be a string.' }, { status: 400 });
  }
  if (body.altText.length > MAX_ALT_LENGTH) {
    return json({ error: `\`altText\` must be ${MAX_ALT_LENGTH} characters or fewer.` }, { status: 400 });
  }

  // A filename that matches nothing updates nothing and still reports ok: the
  // panel PATCHes on blur, so a blur that races a Remove would otherwise put a
  // red banner on a row the author has already dealt with.
  await setMediaAlt(postId, filename, body.altText);
  return json({ ok: true });
};

// DELETE /api/admin/blog/media  { postId, filename }
export const DELETE: RequestHandler = async ({ request }) => {
  const body = await readBody(request);
  if (!body) return json({ error: 'Body must be JSON.' }, { status: 400 });

  const postId = parsePostId(body.postId);
  const filename = parseFilename(body.filename);
  if (postId === null) {
    return json({ error: '`postId` must be a positive integer.' }, { status: 400 });
  }
  if (filename === null) {
    return json({ error: '`filename` must be a non-empty string.' }, { status: 400 });
  }

  // THE ROW ONLY. The bytes stay in the store, and that is not laziness:
  // "remove from library" is a tidy-up of a picker, but a published post — or a
  // preview link, or an RSS reader's cache — may still point at that URL, and
  // this handler has no idea whether it does. An orphaned row is recoverable
  // (re-upload, or re-insert the row); a deleted blob is a hole in a live page.
  // Reclaiming unreferenced bytes is a sweep that reads post content first, and
  // it is not this endpoint.
  await deleteMediaRecord(postId, filename);
  return json({ ok: true });
};
