// Generated by node-builder-codegen emitter. Do not hand-edit this file.
import type { NodeSpec, OptionsResolverSpec, OAuthSpec } from '../spec/types';

/**
 * Emits `src/lib/integrations/adapters/<integrationType>.ts` for a NodeSpec
 * that declares an `integrationType`. The emitted module side-effect-registers
 * an IntegrationAdapter with optional `resolveOptions` (for resource-picker
 * dropdowns) and `testCredential` (for the test-connection action widget).
 *
 * Returns the file content. Callers should write it to
 * `src/lib/integrations/adapters/<safeFileName(spec.integrationType)>.ts`.
 *
 * Returns null if the spec has no integrationType (no adapter needed).
 */
export function emitAdapter(spec: NodeSpec): string | null {
  if (!spec.integrationType) return null;

  const resolveOptions = renderResolveOptions(spec.optionsResolvers ?? []);
  const testCredential = renderTestCredential(spec.testCredentialBody);
  const oauthSpec = renderOAuthSpec(spec.oauthSpec);

  const adapterFields = [
    `integrationType: ${JSON.stringify(spec.integrationType)},`,
    oauthSpec,
    resolveOptions,
    testCredential,
  ]
    .filter((line) => line.length > 0)
    .map((line) => '  ' + line)
    .join('\n');

  return `// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import { registerIntegrationAdapter } from '$lib/integrations/registry';

registerIntegrationAdapter({
${adapterFields}
});
`;
}

function renderResolveOptions(resolvers: OptionsResolverSpec[]): string {
  if (resolvers.length === 0) return '';
  const cases = resolvers
    .map((r) => {
      const body = indentBody(r.body, 6);
      return `    case ${JSON.stringify(r.fieldName)}: {
${body}
    }`;
    })
    .join('\n');
  return `resolveOptions: async (fieldName: string, credentialId: string) => {
  switch (fieldName) {
${cases}
    default:
      throw new Error(\`Unknown resource-picker fieldName: \${fieldName}\`);
  }
},`;
}

function renderTestCredential(body: string | undefined): string {
  if (!body) return '';
  const indented = indentBody(body, 2);
  return `testCredential: async (credentialId: string) => {
${indented}
},`;
}

function renderOAuthSpec(oauth: OAuthSpec | undefined): string {
  if (!oauth) return '';
  return `oauthSpec: {
  authorizationUrl: ${JSON.stringify(oauth.authorizationUrl)},
  tokenUrl: ${JSON.stringify(oauth.tokenUrl)},
  defaultScopes: ${JSON.stringify(oauth.defaultScopes)},
  clientIdEnvVar: ${JSON.stringify(oauth.clientIdEnvVar)},
  clientSecretEnvVar: ${JSON.stringify(oauth.clientSecretEnvVar)},
},`;
}

function indentBody(source: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return source
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}

/** Filesystem-safe filename for an integrationType. */
export function adapterFileName(integrationType: string): string {
  return integrationType.replace(/[^a-z0-9-_]/gi, '-') + '.ts';
}
