// Generated by node-builder-codegen emitter. Do not hand-edit this file.
import type { NodeSpec } from '../spec/types';

export function emitDocs(spec: NodeSpec): string {
  const front = `# ${spec.label}\n\n> ${spec.description}\n\n`;
  const body = spec.docs.trim();
  const examples =
    spec.llmExamples.length > 0
      ? `\n\n## Example configurations\n\n${spec.llmExamples.map(formatExample).join('\n\n')}`
      : '';
  const footer = `\n\n---\n\n*Auto-generated by node-builder-codegen for node \`${spec.type}\`.*\n`;
  return front + body + examples + footer;
}

function formatExample(ex: {
  scenario: string;
  config: Record<string, unknown>;
  notes?: string;
}): string {
  return (
    `### ${ex.scenario}\n\n` +
    '```json\n' +
    JSON.stringify(ex.config, null, 2) +
    '\n```' +
    (ex.notes ? `\n\n${ex.notes}` : '')
  );
}
