// Generated by node-builder-codegen emitter. Do not hand-edit this file.
import type { NodeSpec, NodeDep } from '../spec/types';

export function emitExecutor(spec: NodeSpec): string {
  const importBlock = buildImports(spec);
  const optionsResolverFns = buildOptionsResolvers(spec);

  return `// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

${importBlock}

import type { NodeExecutor, NodeResult } from '$lib/workflows/types';
import { ${camel(spec.type)}Def } from './${spec.type}.def';
export { ${camel(spec.type)}Def } from './${spec.type}.def';

export const ${camel(spec.type)}Executor: NodeExecutor = {
  type: '${spec.type}',
  async execute(input, config: Record<string, any>, _ctx): Promise<NodeResult> {
${indentBody(spec.executorBody, 4)}
  },
  getInputSchema: () => ${camel(spec.type)}Def.configSchema,
  getOutputSchema: () => (${JSON.stringify(spec.outputSchema, null, 2).replace(/\n/g, '\n  ')}),
};
${optionsResolverFns ? '\n' + optionsResolverFns : ''}`;
}

function buildImports(spec: NodeSpec): string {
  const lines: string[] = [];
  lines.push(`import { getCredential } from '$lib/integrations/credentials';`);
  for (const dep of spec.deps) {
    if (dep.name === 'tsdav') {
      lines.push(`import * as tsdav from 'tsdav';`);
    } else {
      lines.push(`import * as ${depImportName(dep)} from '${dep.name}';`);
    }
  }
  return lines.join('\n');
}

function buildOptionsResolvers(spec: NodeSpec): string | null {
  if (!spec.optionsResolvers || spec.optionsResolvers.length === 0) return null;
  const fns = spec.optionsResolvers.map((r) => {
    return `export async function resolveOptions_${r.fieldName}(credentialId: string): Promise<{ value: string; label: string }[]> {
${indentBody(r.body, 2)}
}`;
  });
  return fns.join('\n\n');
}

function depImportName(dep: NodeDep): string {
  return camel(dep.name.replace(/[^a-z0-9]/gi, '-'));
}

function camel(kebab: string): string {
  return kebab.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function indentBody(body: string, spaces: number): string {
  const ind = ' '.repeat(spaces);
  const lines = body.split('\n');
  // Find minimum indentation of non-empty lines (to strip existing indentation uniformly)
  const minIndent = lines
    .filter((l) => l.trim().length > 0)
    .reduce((min, l) => {
      const leading = l.match(/^(\s*)/)?.[1].length ?? 0;
      return Math.min(min, leading);
    }, Infinity);
  const base = minIndent === Infinity ? 0 : minIndent;
  return lines
    .map((line) => (line.trim() ? ind + line.slice(base) : ''))
    .join('\n');
}
