// Reusable field templates, grouped by domain and tied to the standard they
// come from. The engine offers these so designers reuse a known, well-defined
// field instead of inventing a near-duplicate. Each carries provenance
// (sourceStandard) and a one-line `why`.

import type { FieldTemplate, Sector } from './types';

export const FIELD_TEMPLATES: FieldTemplate[] = [
  // ---- Universal record scaffolding ----
  {
    name: 'record_id',
    title: 'Record identifier',
    type: 'identifier',
    description: 'A stable, unique identifier for this row within the dataset.',
    required: true,
    pii: false,
    specialCategory: false,
    format: 'String, unique, immutable',
    why: 'Every record needs a stable primary key so it can be referenced and updated.',
    domains: ['education', 'childrens-social-care', 'child-protection', 'health', 'local-gov', 'cross-gov', 'employment', 'housing', 'justice'],
  },
  {
    name: 'reference_period',
    title: 'Reference period',
    type: 'string',
    description: 'The period the record describes (e.g. academic year 2025/2026, or 2026-04).',
    required: true,
    pii: false,
    specialCategory: false,
    format: 'ISO 8601 date or period string',
    sourceStandard: 'iso-8601',
    why: 'Time framing is essential for comparability across submissions.',
    domains: ['education', 'childrens-social-care', 'child-protection', 'health', 'local-gov', 'cross-gov', 'employment', 'housing', 'justice'],
  },
  {
    name: 'snapshot_date',
    title: 'Snapshot / census date',
    type: 'date',
    description: 'The date the record is a true reflection of (the census reference date).',
    required: true,
    pii: false,
    specialCategory: false,
    format: 'ISO 8601 (YYYY-MM-DD)',
    sourceStandard: 'iso-8601',
    why: 'Point-in-time data needs an explicit reference date.',
    domains: ['education', 'childrens-social-care', 'child-protection', 'health', 'local-gov'],
  },

  // ---- Establishment / organisation ----
  {
    name: 'urn',
    title: 'School URN',
    type: 'identifier',
    description: 'The Unique Reference Number of the school/establishment.',
    required: false,
    pii: false,
    specialCategory: false,
    identifier: 'urn',
    format: '6-digit number',
    sourceStandard: 'gias',
    why: 'Reuse GIAS URN so the data joins to the authoritative school register.',
    domains: ['education'],
  },
  {
    name: 'ukprn',
    title: 'Provider UKPRN',
    type: 'identifier',
    description: 'UK Provider Reference Number of the education/training provider.',
    required: false,
    pii: false,
    specialCategory: false,
    identifier: 'ukprn',
    format: '8-digit number',
    sourceStandard: 'gias',
    why: 'The standard provider key across DfE/ESFA funding systems.',
    domains: ['education', 'employment'],
  },
  {
    name: 'la_code',
    title: 'Local authority code',
    type: 'identifier',
    description: 'ONS / DfE local-authority code.',
    required: false,
    pii: false,
    specialCategory: false,
    identifier: 'gss-code',
    format: '9-char GSS code (or 3-digit DfE LA number)',
    sourceStandard: 'gss-geography',
    why: 'Use the standard geography code, not a council name string.',
    domains: ['education', 'childrens-social-care', 'child-protection', 'local-gov', 'cross-gov', 'housing'],
  },
  {
    name: 'ods_code',
    title: 'Organisation ODS code',
    type: 'identifier',
    description: 'NHS Organisation Data Service code for the provider organisation.',
    required: false,
    pii: false,
    specialCategory: false,
    identifier: 'ods-code',
    format: 'Alphanumeric ODS code',
    sourceStandard: 'nhs-data-dictionary',
    why: 'The standard organisation key across health and care.',
    domains: ['health'],
  },
  {
    name: 'uprn',
    title: 'Property UPRN',
    type: 'identifier',
    description: 'Unique Property Reference Number for the address.',
    required: false,
    pii: false,
    specialCategory: false,
    identifier: 'uprn',
    format: 'Numeric, up to 12 digits',
    sourceStandard: 'uprn-usrn-llpg',
    why: 'Join on UPRN instead of matching free-text addresses.',
    domains: ['local-gov', 'housing', 'cross-gov'],
  },

  // ---- Person identity ----
  {
    name: 'upn',
    title: 'Unique Pupil Number',
    type: 'identifier',
    description: 'The pupil\'s UPN.',
    required: false,
    pii: true,
    specialCategory: false,
    identifier: 'upn',
    format: '13-character UPN',
    sourceStandard: 'school-census',
    constraints: 'Education-purpose use only — cannot be a cross-domain spine.',
    why: 'The established pupil key — but note its legal purpose limitation.',
    domains: ['education'],
  },
  {
    name: 'uln',
    title: 'Unique Learner Number',
    type: 'identifier',
    description: 'The learner\'s ULN.',
    required: false,
    pii: true,
    specialCategory: false,
    identifier: 'uln',
    format: '10-digit ULN',
    sourceStandard: 'ilr',
    why: 'Continuity key for post-14 learners.',
    domains: ['education', 'employment'],
  },
  {
    name: 'nhs_number',
    title: 'NHS Number',
    type: 'identifier',
    description: 'The person\'s NHS Number.',
    required: false,
    pii: true,
    specialCategory: false,
    identifier: 'nhs-number',
    format: '10 digits with Mod-11 check',
    sourceStandard: 'nhs-data-dictionary',
    constraints: 'Cross-domain use requires an explicit legal gateway.',
    why: 'Near-universal for children; the leading candidate for a consistent child identifier.',
    domains: ['health', 'childrens-social-care', 'child-protection'],
  },
  {
    name: 'date_of_birth',
    title: 'Date of birth',
    type: 'date',
    description: 'The individual\'s date of birth.',
    required: false,
    pii: true,
    specialCategory: false,
    format: 'ISO 8601 (YYYY-MM-DD)',
    sourceStandard: 'iso-8601',
    why: 'Standard demographic; format with ISO 8601 to avoid ambiguity.',
    domains: ['education', 'childrens-social-care', 'child-protection', 'health'],
  },
  {
    name: 'sex',
    title: 'Sex',
    type: 'enum',
    description: 'Sex as recorded.',
    required: false,
    pii: true,
    specialCategory: false,
    codelist: 'CBDS / NHS Data Dictionary sex code',
    sourceStandard: 'cbds',
    why: 'Use the established code values rather than free text.',
    domains: ['education', 'childrens-social-care', 'health'],
  },
  {
    name: 'ethnicity',
    title: 'Ethnicity',
    type: 'enum',
    description: 'Ethnic group.',
    required: false,
    pii: true,
    specialCategory: true,
    codelist: 'DfE/CBDS ethnicity codes (or ONS census categories)',
    sourceStandard: 'cbds',
    constraints: 'Special-category data (UK GDPR Art.9) — needs an Art.9 condition.',
    why: 'Reuse the standard ethnicity codelist for comparability.',
    domains: ['education', 'childrens-social-care', 'health'],
  },

  // ---- Education-specific ----
  {
    name: 'fsm_eligibility',
    title: 'Free school meal eligibility',
    type: 'boolean',
    description: 'Whether the pupil is eligible for free school meals.',
    required: false,
    pii: true,
    specialCategory: false,
    sourceStandard: 'school-census',
    why: 'The standard disadvantage proxy used across DfE analysis.',
    domains: ['education'],
  },
  {
    name: 'sen_provision',
    title: 'SEN provision',
    type: 'enum',
    description: 'Special educational needs provision (e.g. SEN support, EHC plan).',
    required: false,
    pii: true,
    specialCategory: true,
    codelist: 'CBDS SEN provision codes',
    sourceStandard: 'sen2',
    why: 'Reuse SEN2/CBDS codes so it lines up with the EHC plan return.',
    domains: ['education'],
  },
  {
    name: 'attendance_mark',
    title: 'Attendance mark',
    type: 'enum',
    description: 'Session attendance mark.',
    required: false,
    pii: true,
    specialCategory: false,
    codelist: 'DfE attendance codes',
    sourceStandard: 'daily-attendance',
    why: 'Use the national attendance code set to align with the daily feed.',
    domains: ['education'],
  },

  // ---- Children's social care / child protection ----
  {
    name: 'legal_status',
    title: 'Legal status',
    type: 'enum',
    description: 'Legal status of a looked-after child.',
    required: false,
    pii: true,
    specialCategory: true,
    codelist: 'SSDA903 legal status codes',
    sourceStandard: 'ssda903',
    why: 'Reuse 903 codes so it integrates with the CLA return.',
    domains: ['childrens-social-care'],
  },
  {
    name: 'placement_type',
    title: 'Placement type',
    type: 'enum',
    description: 'Type of placement for a looked-after child.',
    required: false,
    pii: true,
    specialCategory: true,
    codelist: 'SSDA903 placement codes',
    sourceStandard: 'ssda903',
    why: 'Align with the established placement taxonomy.',
    domains: ['childrens-social-care'],
  },
  {
    name: 'referral_date',
    title: 'Referral date',
    type: 'date',
    description: 'Date of referral to children\'s social care.',
    required: false,
    pii: true,
    specialCategory: true,
    format: 'ISO 8601',
    sourceStandard: 'cin-census',
    why: 'Aligns with the CIN census timeline.',
    domains: ['childrens-social-care', 'child-protection'],
  },
  {
    name: 'cp_plan_flag',
    title: 'Child protection plan indicator',
    type: 'boolean',
    description: 'Whether the child is subject to a child protection plan.',
    required: false,
    pii: true,
    specialCategory: true,
    sourceStandard: 'cp-is',
    constraints: 'Highly sensitive — strict access control and a DPIA are required.',
    why: 'The flag CP-IS already shares; align rather than redefine.',
    domains: ['child-protection', 'childrens-social-care'],
  },
  {
    name: 'factors_at_assessment',
    title: 'Factors identified at assessment',
    type: 'array',
    description: 'The factors identified at the end of assessment.',
    required: false,
    pii: true,
    specialCategory: true,
    codelist: 'CIN census factors codelist',
    sourceStandard: 'cin-census',
    why: 'Reuse the CIN factors list rather than free text.',
    domains: ['childrens-social-care', 'child-protection'],
  },

  // ---- Health ----
  {
    name: 'snomed_code',
    title: 'Clinical code (SNOMED CT)',
    type: 'string',
    description: 'A SNOMED CT concept id for the coded clinical item.',
    required: false,
    pii: false,
    specialCategory: false,
    codelist: 'SNOMED CT',
    sourceStandard: 'snomed-ct',
    why: 'Make clinical content computable and interoperable.',
    domains: ['health'],
  },
  {
    name: 'event_datetime',
    title: 'Event date-time',
    type: 'datetime',
    description: 'When the clinical/health event occurred.',
    required: false,
    pii: false,
    specialCategory: false,
    format: 'ISO 8601 date-time',
    sourceStandard: 'fhir-uk-core',
    why: 'Event timing for FHIR-aligned resources.',
    domains: ['health'],
  },

  // ---- Local government ----
  {
    name: 'service_code',
    title: 'Local service code (LGSL)',
    type: 'enum',
    description: 'Local Government Services List code for the service.',
    required: false,
    pii: false,
    specialCategory: false,
    codelist: 'ESD LGSL',
    sourceStandard: 'esd-lgsl',
    why: 'Reuse the LGSL so services are comparable across councils.',
    domains: ['local-gov'],
  },

  // ---- Money (cross-cutting) ----
  {
    name: 'amount_gbp',
    title: 'Amount (GBP)',
    type: 'currency',
    description: 'A monetary amount in pounds sterling.',
    required: false,
    pii: false,
    specialCategory: false,
    unit: 'GBP',
    format: 'Decimal, 2 places; currency code ISO 4217',
    why: 'State currency and precision explicitly.',
    domains: ['cross-gov', 'local-gov', 'education', 'employment'],
  },
];

/** Templates offered for a domain: domain-specific ones plus the universal scaffolding. */
export function templatesForDomain(domain: Sector): FieldTemplate[] {
  return FIELD_TEMPLATES.filter((t) => t.domains.includes(domain));
}
