// Grounded knowledge base of UK / international government data standards.
//
// This is the engine's evidence. Entries are curated from primary sources
// (DfE, NHS England, ONS, W3C, standards bodies) and enriched by the
// data-standards research workflow. The engine reads this to propose
// identifiers, fields, formats and cadence, and to build the crosswalk.
//
// Reuse over reinvention is the through-line: the single biggest
// interoperability win is adopting an identifier or codelist that providers
// already hold, rather than minting a new one.

import type {
  IdentifierEntry,
  StandardEntry,
  Relationship,
  MethodEntry,
} from './types';
import { RESEARCH_CATALOG } from './researchData';

// ---------------------------------------------------------------------------
// Identifiers — the spine of interoperability
// ---------------------------------------------------------------------------

export const IDENTIFIERS: IdentifierEntry[] = [
  {
    id: 'upn',
    name: 'Unique Pupil Number (UPN)',
    scope: 'A pupil in the English state school system',
    owner: 'Department for Education',
    format: '13 characters: a check letter, 3-digit LA, 4-digit establishment, 1-digit year, 4-digit serial',
    sectors: ['education'],
    heldBy: 'Schools (in their MIS) and local authorities',
    caveat:
      'Legally restricted to educational purposes — it cannot be used as a cross-domain spine for health or social care. This is the core reason England lacks a single child identifier.',
    url: 'https://www.gov.uk/government/publications/unique-pupil-numbers',
  },
  {
    id: 'uln',
    name: 'Unique Learner Number (ULN)',
    scope: 'A post-14 learner (FE, skills, apprenticeships)',
    owner: 'Learning Records Service (ESFA)',
    format: '10-digit number',
    sectors: ['education', 'employment'],
    heldBy: 'Colleges, training providers, awarding organisations',
    url: 'https://www.gov.uk/government/collections/learning-records-service',
  },
  {
    id: 'urn',
    name: 'Unique Reference Number (URN)',
    scope: 'A school or educational establishment',
    owner: 'Department for Education (GIAS)',
    format: '6-digit number',
    sectors: ['education'],
    heldBy: 'GIAS — the authoritative register of schools',
    url: 'https://get-information-schools.service.gov.uk/',
  },
  {
    id: 'ukprn',
    name: 'UK Provider Reference Number (UKPRN)',
    scope: 'An education or training provider organisation',
    owner: 'UK Register of Learning Providers (UKRLP)',
    format: '8-digit number',
    sectors: ['education', 'cross-gov'],
    heldBy: 'GIAS, ESFA funding systems, UKRLP',
    url: 'https://www.ukrlp.co.uk/',
  },
  {
    id: 'la-estab',
    name: 'LA / Establishment number (LAESTAB / DfE number)',
    scope: 'A maintained school within a local authority',
    owner: 'Department for Education',
    format: '3-digit LA code + 4-digit establishment code (e.g. 938/4001)',
    sectors: ['education'],
    heldBy: 'Schools, LAs, GIAS',
  },
  {
    id: 'trn',
    name: 'Teacher Reference Number (TRN)',
    scope: 'A teacher / member of the school workforce',
    owner: 'Department for Education',
    format: '7-digit number',
    sectors: ['education'],
    heldBy: 'DfE Teaching Record, school MIS',
  },
  {
    id: 'nhs-number',
    name: 'NHS Number',
    scope: 'A person registered with the NHS in England, Wales or IoM (virtually all children)',
    owner: 'NHS England',
    format: '10-digit number with a Modulus-11 check digit (3-3-4 grouping)',
    sectors: ['health', 'childrens-social-care', 'child-protection', 'cross-gov'],
    heldBy: 'GP systems, the Personal Demographics Service, hospital systems, birth notifications',
    caveat:
      'Governed by NHS England. Being explored as the basis of a "consistent identifier" for children under the Children\'s Wellbeing and Schools Act — but cross-domain use needs an explicit legal gateway.',
    url: 'https://www.nhs.uk/nhs-services/online-services/find-nhs-number/',
  },
  {
    id: 'ods-code',
    name: 'Organisation Data Service code (ODS code)',
    scope: 'A health or care organisation, site or practitioner role',
    owner: 'NHS England (ODS)',
    format: 'Alphanumeric (e.g. a GP practice code like A81001)',
    sectors: ['health'],
    heldBy: 'All NHS and care systems',
    url: 'https://digital.nhs.uk/services/organisation-data-service',
  },
  {
    id: 'uprn',
    name: 'Unique Property Reference Number (UPRN)',
    scope: 'A unit of land or property in Great Britain',
    owner: 'GeoPlace / Ordnance Survey / local authorities (LLPG)',
    format: 'Numeric, up to 12 digits',
    sectors: ['local-gov', 'cross-gov', 'housing'],
    heldBy: 'Local Land & Property Gazetteers, OS AddressBase, most LA systems',
    caveat: 'An open identifier under the OS Data Hub — the canonical join key for anything address-based.',
    url: 'https://www.geoplace.co.uk/addresses-streets/data-and-resources/uprn',
  },
  {
    id: 'usrn',
    name: 'Unique Street Reference Number (USRN)',
    scope: 'A street',
    owner: 'GeoPlace',
    format: '8-digit number',
    sectors: ['local-gov', 'cross-gov'],
    heldBy: 'National Street Gazetteer, LA systems',
    url: 'https://www.geoplace.co.uk/addresses-streets/data-and-resources/usrn',
  },
  {
    id: 'gss-code',
    name: 'Government Statistical Service code (GSS / ONS geography code)',
    scope: 'A statistical or administrative geography (LA, ward, region, country)',
    owner: 'Office for National Statistics',
    format: '9-character code (e.g. E09000007 for Camden)',
    sectors: ['cross-gov', 'local-gov'],
    heldBy: 'ONS Open Geography Portal — the standard geography join key',
    url: 'https://geoportal.statistics.gov.uk/',
  },
  {
    id: 'companies-house-number',
    name: 'Company Registration Number (CRN)',
    scope: 'A registered company',
    owner: 'Companies House',
    format: '8 characters (digits, or 2 letters + 6 digits)',
    sectors: ['cross-gov', 'private'],
    heldBy: 'Companies House register and API',
    url: 'https://developer.company-information.service.gov.uk/',
  },
  {
    id: 'ni-number',
    name: 'National Insurance Number (NINO)',
    scope: 'An individual for tax, benefits and employment',
    owner: 'HMRC / DWP',
    format: '2 letters, 6 digits, 1 letter (e.g. QQ123456C)',
    sectors: ['employment', 'cross-gov'],
    heldBy: 'HMRC, DWP, employers',
    caveat: 'Strictly purpose-limited; not a general-purpose join key.',
  },
  {
    id: 'consistent-child-identifier',
    name: 'Consistent child identifier (proposed)',
    scope: 'A single number to follow a child across education, health and social care',
    owner: 'Department for Education (in development)',
    format: 'Undecided — NHS Number is the leading candidate',
    sectors: ['childrens-social-care', 'child-protection', 'education', 'health'],
    heldBy: 'Not yet operational; piloted (e.g. the Wigan identifier work)',
    caveat:
      'Legislated for under the Children\'s Wellbeing and Schools Act. Design choice is live: reuse NHS Number (already near-universal) vs. mint new. The interoperability case strongly favours reuse.',
  },
];

// ---------------------------------------------------------------------------
// Standards catalog
// ---------------------------------------------------------------------------

export const SEED_CATALOG: StandardEntry[] = [
  // ---- Education ----
  {
    id: 'cbds',
    name: 'Common Basic Data Set (CBDS)',
    owner: 'Department for Education',
    sector: 'education',
    description:
      'The dictionary of data items and business rules reused across DfE statutory collections. The closest thing England has to a shared education data dictionary.',
    dataCovered: 'Pupil, staff and establishment data items used by the school census and related returns',
    identifiers: ['upn', 'urn', 'la-estab'],
    formats: ['xml', 'csv'],
    collectionMethod: 'Underpins COLLECT-based statutory returns',
    frequency: 'Versioned annually',
    cadence: 'annual',
    publishing: 'Published as CBDS tables on GOV.UK',
    interoperability: 'A common data dictionary — the model to extend rather than reinvent within education',
    assurance: 'DfE-governed; each collection has validation rules',
    connectsTo: ['school-census', 'ctf', 'gias'],
    urls: ['https://www.gov.uk/government/collections/common-basic-data-set-cbds-tables'],
  },
  {
    id: 'school-census',
    name: 'School Census',
    owner: 'Department for Education',
    sector: 'education',
    description:
      'The termly statutory pupil-level census collected from schools via COLLECT, feeding the National Pupil Database.',
    dataCovered: 'Pupil characteristics, attendance, exclusions, free-school-meal eligibility, SEN',
    identifiers: ['upn', 'urn', 'la-estab'],
    keyFields: ['UPN', 'date of birth', 'sex', 'ethnicity', 'FSM eligibility', 'SEN provision'],
    formats: ['xml'],
    collectionMethod: 'MIS extract uploaded to COLLECT (statutory return)',
    frequency: 'Termly (autumn, spring, summer)',
    cadence: 'termly',
    publishing: 'Aggregates via Explore Education Statistics; micro-data into the NPD',
    interoperability: 'Uses CBDS items and UPN; the spine of pupil-level statistics',
    assurance: 'Statutory; extensive COLLECT validation and autumn/spring blade rules',
    connectsTo: ['cbds', 'npd', 'ees'],
    urls: ['https://www.gov.uk/guidance/complete-the-school-census'],
  },
  {
    id: 'gias',
    name: 'Get Information About Schools (GIAS)',
    owner: 'Department for Education',
    sector: 'education',
    description: 'The authoritative register of schools and educational establishments in England.',
    dataCovered: 'Establishment records: status, phase, type, trust, location, identifiers',
    identifiers: ['urn', 'ukprn', 'la-estab'],
    formats: ['csv', 'json'],
    collectionMethod: 'Register, maintained centrally; daily bulk extract',
    frequency: 'Daily',
    cadence: 'daily',
    publishing: 'Open daily CSV/JSON download (no rate-limited open API)',
    interoperability: 'The reference register every other education dataset should join to by URN/UKPRN',
    assurance: 'Authoritative source-of-truth register',
    connectsTo: ['school-census', 'ilr', 'ees'],
    urls: ['https://get-information-schools.service.gov.uk/'],
  },
  {
    id: 'ctf',
    name: 'Common Transfer File (CTF)',
    owner: 'Department for Education',
    sector: 'education',
    description:
      'The XML file used to transfer a pupil record between schools when a child moves.',
    dataCovered: 'Identity, attendance, assessment and SEN history',
    identifiers: ['upn'],
    formats: ['xml'],
    collectionMethod: 'School-to-school MIS transfer',
    frequency: 'On pupil move',
    cadence: 'ad-hoc',
    interoperability:
      'Works only cleanly between schools on the same MIS product; the child-protection file is deliberately excluded and moves manually within 5 days — a documented safeguarding gap.',
    assurance: 'DfE specification (CTF spec)',
    connectsTo: ['school-census', 'cbds'],
    urls: ['https://www.gov.uk/guidance/school-to-school-service-transfer-information'],
  },
  {
    id: 'ilr',
    name: 'Individualised Learner Record (ILR)',
    owner: 'Education and Skills Funding Agency',
    sector: 'education',
    description: 'The learner-level data collection for further education and skills, keyed on the ULN.',
    dataCovered: 'Learner, learning aim, funding and outcome data',
    identifiers: ['uln', 'ukprn'],
    formats: ['xml'],
    collectionMethod: 'In-year periodic returns to the Submit Learner Data service',
    frequency: 'Monthly in-year',
    cadence: 'monthly',
    publishing: 'Feeds funding and FE statistics',
    interoperability: 'ULN gives post-16 continuity; UKPRN ties to provider',
    assurance: 'ESFA validation + funding rules',
    connectsTo: ['ees', 'gias'],
    urls: ['https://www.gov.uk/government/collections/individualised-learner-record-ilr'],
  },
  {
    id: 'ees',
    name: 'Explore Education Statistics (EES)',
    owner: 'Department for Education',
    sector: 'education',
    description: 'The platform and open API DfE publishes official statistics through.',
    dataCovered: 'Published statistics datasets with a consistent data-table model and metadata',
    formats: ['csv', 'json'],
    metadataApproach: 'Consistent dataset + indicator + filter metadata, queryable via a public REST API',
    collectionMethod: 'Publishing platform (not a collection)',
    frequency: 'Per publication',
    publishing: 'Open REST API + bulk CSV/ZIP at api.education.gov.uk',
    interoperability: 'A model for machine-readable statistics publishing within gov',
    assurance: 'Code of Practice for Statistics',
    connectsTo: ['school-census', 'ilr'],
    urls: ['https://explore-education-statistics.service.gov.uk/', 'https://api.education.gov.uk/statistics/docs/'],
  },
  {
    id: 'npd',
    name: 'National Pupil Database (NPD)',
    owner: 'Department for Education',
    sector: 'education',
    description:
      'The longitudinal pupil-level database linking census, attainment, absence, exclusions and (with permissions) social-care and destinations data.',
    dataCovered: 'Linked pupil records across the school career and beyond',
    identifiers: ['upn'],
    collectionMethod: 'Assembled from statutory returns; access via the ONS Secure Research Service',
    publishing: 'Restricted micro-data under a strict application and Five Safes regime',
    interoperability: 'Shows the analytical value of a stable identifier (UPN) maintained over time',
    assurance: 'Secure Research Service / Five Safes governance',
    connectsTo: ['school-census', 'ssda903', 'ilr'],
    urls: ['https://www.gov.uk/guidance/apply-for-department-for-education-dfe-personal-data'],
  },
  {
    id: 'sen2',
    name: 'SEN2 — Education, Health and Care (EHC) plan return',
    owner: 'Department for Education',
    sector: 'education',
    description: 'The person-level statutory return on EHC plans and SEN.',
    dataCovered: 'EHC plan timeliness, placements, needs',
    identifiers: ['upn'],
    formats: ['xml', 'csv'],
    collectionMethod: 'Statutory return (person-level since 2023)',
    frequency: 'Annual',
    cadence: 'annual',
    connectsTo: ['school-census', 'ssda903'],
    urls: ['https://www.gov.uk/government/collections/statutory-guidance-special-educational-needs-and-disability-send'],
  },
  {
    id: 'daily-attendance',
    name: 'Pupil attendance data (daily feed)',
    owner: 'Department for Education',
    sector: 'education',
    description: 'Near-real-time daily attendance, fed automatically from school MIS via approved aggregators.',
    dataCovered: 'Session-level attendance marks',
    identifiers: ['upn', 'urn'],
    formats: ['json'],
    collectionMethod: 'Automated MIS feed (event/daily) via aggregators such as Wonde',
    frequency: 'Daily',
    cadence: 'daily',
    publishing: 'View Your Education Data dashboards',
    interoperability: 'Demonstrates the automated-feed model that reduces school burden vs. manual returns',
    connectsTo: ['school-census'],
    urls: ['https://www.gov.uk/guidance/share-your-daily-school-attendance-data'],
  },

  // ---- Children's social care & child protection ----
  {
    id: 'ssda903',
    name: 'Children Looked After return (SSDA903 / CLA)',
    owner: 'Department for Education',
    sector: 'childrens-social-care',
    description: 'The annual child-level return on looked-after children, running since 1992.',
    dataCovered: 'Care episodes, placements, legal status, health and education of looked-after children',
    keyFields: ['child id', 'date of birth', 'sex', 'ethnicity', 'legal status', 'placement type', 'episode dates'],
    formats: ['xml', 'csv'],
    collectionMethod: 'Annual statutory return extracted from LA case-management systems',
    frequency: 'Annual',
    cadence: 'annual',
    publishing: 'Aggregates via EES; micro-data via the ONS Secure Research Service',
    interoperability: 'Lacks a cross-domain child identifier — joins to health/education are hard',
    assurance: 'DfE validation rules',
    connectsTo: ['cin-census', 'sen2', 'd2i-chat'],
    urls: ['https://www.gov.uk/government/collections/children-in-care'],
  },
  {
    id: 'cin-census',
    name: 'Children in Need census (CIN)',
    owner: 'Department for Education',
    sector: 'childrens-social-care',
    description: 'The annual child-level census of referrals, assessments and children in need / on a protection plan.',
    dataCovered: 'Referrals, assessments, section 47 enquiries, CP plans, factors at assessment',
    formats: ['xml', 'csv'],
    collectionMethod: 'Annual statutory return from LA case-management systems',
    frequency: 'Annual',
    cadence: 'annual',
    interoperability: 'Annex A is the operational list LAs already produce; alignment lowers burden',
    connectsTo: ['ssda903', 'cp-is', 'd2i-chat'],
    urls: ['https://www.gov.uk/government/collections/children-in-need-census'],
  },
  {
    id: 'cp-is',
    name: 'Child Protection — Information Sharing (CP-IS)',
    owner: 'NHS England with local authorities',
    sector: 'child-protection',
    description:
      'A live service that lets unscheduled-care settings see if a child has a protection plan or is looked after, and notifies the LA when that child attends.',
    dataCovered: 'Protection-plan / looked-after flags and NHS-number-keyed notifications',
    identifiers: ['nhs-number'],
    formats: ['fhir', 'xml'],
    collectionMethod: 'Real-time exchange between LA and NHS systems',
    frequency: 'Real-time',
    cadence: 'real-time',
    interoperability:
      'The working example of an NHS-number-keyed, event-based LA↔NHS exchange — a pattern education has never built.',
    assurance: 'NHS England information standard',
    connectsTo: ['nhs-data-dictionary', 'digital-child-health-fhir'],
    urls: ['https://digital.nhs.uk/services/child-protection-information-sharing-service'],
  },
  {
    id: 'd2i-chat',
    name: 'Data to Insight (D2I) / ChAT',
    owner: 'Local authority sector, funded by DfE/MHCLG/Ofsted/ADCS',
    sector: 'childrens-social-care',
    description:
      'Sector-led analytical tools (notably the Children\'s Services Analysis Tool, ChAT) giving a national analytical view without national data custody.',
    dataCovered: 'Standardised analysis over the statutory children\'s-social-care returns',
    collectionMethod: 'Reuses existing returns (903/CIN)',
    interoperability: 'Proves a federated, sector-governed model — a precedent for adoption',
    connectsTo: ['ssda903', 'cin-census'],
    urls: ['https://www.datatoinsight.org/'],
  },

  // ---- Health ----
  {
    id: 'nhs-data-dictionary',
    name: 'NHS Data Model and Dictionary',
    owner: 'NHS England',
    sector: 'health',
    description: 'The authoritative reference for the data items, definitions and business rules used across the NHS.',
    dataCovered: 'Standard data elements, attributes and code sets for health and care',
    identifiers: ['nhs-number', 'ods-code'],
    metadataApproach: 'Formally governed data elements with classes and attributes',
    formats: ['xml'],
    publishing: 'Published online and via Information Standards Notices (DCB/ISN)',
    interoperability: 'The health analogue of CBDS — a fully governed data dictionary',
    assurance: 'Information Standards (DCB) approval route',
    connectsTo: ['snomed-ct', 'fhir-uk-core'],
    urls: ['https://www.datadictionary.nhs.uk/'],
  },
  {
    id: 'fhir-uk-core',
    name: 'FHIR UK Core',
    owner: 'NHS England with HL7 UK',
    sector: 'health',
    description: 'UK profiles on HL7 FHIR R4 — the modern API standard for exchanging health and care data.',
    dataCovered: 'Patients, encounters, observations, immunisations and more as FHIR resources',
    identifiers: ['nhs-number', 'ods-code'],
    formats: ['fhir', 'json', 'xml'],
    metadataApproach: 'Resource profiles, value sets and an implementation guide',
    collectionMethod: 'RESTful APIs and messaging',
    interoperability: 'The reference choice for real-time, resource-based health interoperability',
    assurance: 'NHS England API standards and conformance',
    connectsTo: ['snomed-ct', 'nhs-data-dictionary', 'prsb-healthy-child', 'digital-child-health-fhir'],
    urls: ['https://digital.nhs.uk/services/fhir-uk-core'],
  },
  {
    id: 'snomed-ct',
    name: 'SNOMED CT',
    owner: 'SNOMED International (UK Edition via NHS England)',
    sector: 'health',
    description: 'The comprehensive clinical terminology mandated across NHS care records.',
    dataCovered: 'Coded clinical concepts: findings, procedures, observations',
    formats: ['rdf'],
    metadataApproach: 'A poly-hierarchical concept ontology with stable concept ids',
    interoperability: 'The controlled vocabulary that makes clinical data computable across systems',
    assurance: 'Mandated NHS terminology',
    connectsTo: ['fhir-uk-core', 'nhs-data-dictionary'],
    urls: ['https://digital.nhs.uk/services/terminology-and-classifications/snomed-ct'],
  },
  {
    id: 'prsb-healthy-child',
    name: 'PRSB Healthy Child Record Standard',
    owner: 'Professional Record Standards Body',
    sector: 'health',
    description: 'A clinically-assured, FHIR-aligned standard for the content of a child health record.',
    dataCovered: 'Health-visiting and child-health-review record content',
    identifiers: ['nhs-number'],
    formats: ['fhir'],
    interoperability: 'Shows what a clinically-governed children\'s record standard looks like — education/social care has no equivalent body',
    assurance: 'PRSB clinical assurance process',
    connectsTo: ['digital-child-health-fhir', 'fhir-uk-core'],
    urls: ['https://theprsb.org/standards/healthychildrecordstandard/'],
  },
  {
    id: 'digital-child-health-fhir',
    name: 'Digital Child Health (DCH) FHIR standard',
    owner: 'NHS England',
    sector: 'health',
    description: 'Event-based FHIR messaging for birth notifications, immunisations and child-health events.',
    dataCovered: 'Child-health events shared between maternity, child-health and GP systems',
    identifiers: ['nhs-number'],
    formats: ['fhir'],
    collectionMethod: 'Event messaging',
    frequency: 'Real-time / on event',
    cadence: 'real-time',
    interoperability: 'The eventing pattern to emulate for cross-agency child data',
    connectsTo: ['cp-is', 'fhir-uk-core'],
    urls: ['https://digital.nhs.uk/developer/api-catalogue/digital-child-health-fhir'],
  },
  {
    id: 'dspt',
    name: 'Data Security and Protection Toolkit (DSPT)',
    owner: 'NHS England',
    sector: 'health',
    description: 'The annual self-assessment of data-security and information-governance standards for organisations handling health and care data.',
    dataCovered: 'Information-governance assurance (not a dataset)',
    interoperability: 'A reusable assurance gate for any provider touching health data',
    assurance: 'Mandated annual assertion',
    connectsTo: [],
    urls: ['https://www.dsptoolkit.nhs.uk/'],
  },

  // ---- Cross-government ----
  {
    id: 'dsa-catalogue',
    name: 'Data Standards Authority — standards catalogue',
    owner: 'Central Digital and Data Office (CDDO)',
    sector: 'cross-gov',
    description: 'The cross-government catalogue of recommended and mandated data standards.',
    dataCovered: 'Recommended standards for dates, names, addresses, country, currency, metadata',
    metadataApproach: 'Recommends DCAT-based metadata for cataloguing',
    interoperability: 'The first place to look before minting anything new in central government',
    assurance: 'Open Standards Board endorsement',
    connectsTo: ['gov-open-standards', 'govuk-registers', 'iso-8601'],
    urls: ['https://www.gov.uk/government/groups/data-standards-authority'],
  },
  {
    id: 'gov-open-standards',
    name: 'Open Standards for government',
    owner: 'Cabinet Office / DSA',
    sector: 'cross-gov',
    description: 'The compulsory open standards selected through the government\'s challenge-and-response process.',
    dataCovered: 'Selected document, data and interoperability standards',
    interoperability: 'Mandates openness and royalty-free standards for interoperability',
    assurance: 'Open Standards Board',
    connectsTo: ['dsa-catalogue'],
    urls: ['https://www.gov.uk/government/publications/open-standards-for-government'],
  },
  {
    id: 'govuk-registers',
    name: 'GOV.UK Registers',
    owner: 'Government Digital Service',
    sector: 'cross-gov',
    description: 'Authoritative lists of reference data (countries, territories, local authorities) maintained by a custodian.',
    dataCovered: 'Canonical reference data with stable codes',
    metadataApproach: 'Each register has a custodian and a stable schema',
    interoperability: 'Reuse a register instead of embedding your own codelist',
    connectsTo: ['iso-3166', 'gss-geography'],
    urls: ['https://www.registers.service.gov.uk/'],
  },
  {
    id: 'gdqf',
    name: 'Government Data Quality Framework',
    owner: 'Data Standards Authority / ONS',
    sector: 'cross-gov',
    description: 'The cross-government framework for managing and describing data quality.',
    dataCovered: 'The data-quality dimensions (completeness, uniqueness, timeliness, validity, accuracy, consistency)',
    interoperability: 'Gives a shared vocabulary for the quality clauses of a standard',
    assurance: 'The reference for quality assurance of a dataset',
    connectsTo: [],
    urls: ['https://www.gov.uk/government/publications/the-government-data-quality-framework'],
  },
  {
    id: 'atrs',
    name: 'Algorithmic Transparency Recording Standard (ATRS)',
    owner: 'CDDO / Responsible Technology Adoption Unit',
    sector: 'cross-gov',
    description: 'A standard template for public bodies to publish information about the algorithmic tools they use.',
    dataCovered: 'Algorithmic tool descriptions, data and oversight',
    interoperability: 'Relevant when a dataset will feed automated decision-making',
    connectsTo: [],
    urls: ['https://www.gov.uk/government/collections/algorithmic-transparency-recording-standard-hub'],
  },
  {
    id: 'ids',
    name: 'Integrated Data Service (IDS)',
    owner: 'Office for National Statistics',
    sector: 'cross-gov',
    description: 'A secure trusted research environment bringing together de-identified cross-government data for analysis.',
    dataCovered: 'Linked, de-identified government microdata',
    interoperability: 'A federation/TRE model for analysis without central custody',
    assurance: 'Five Safes governance',
    connectsTo: [],
    urls: ['https://integrateddataservice.gov.uk/'],
  },
  {
    id: 'gss-geography',
    name: 'ONS geography (GSS codes & Open Geography Portal)',
    owner: 'Office for National Statistics',
    sector: 'cross-gov',
    description: 'The standard codes and boundaries for UK statistical and administrative geographies.',
    dataCovered: 'Geography codes, names, lookups and boundaries',
    identifiers: ['gss-code'],
    formats: ['csv', 'json', 'rdf'],
    interoperability: 'The geography join key for any spatial dataset',
    connectsTo: ['govuk-registers', 'uprn-usrn-llpg'],
    urls: ['https://geoportal.statistics.gov.uk/'],
  },

  // ---- Local government ----
  {
    id: 'esd-lgsl',
    name: 'ESD Standards — Local Government Services List (LGSL/LGNL)',
    owner: 'iStandUK / Porism (LG Inform Plus)',
    sector: 'local-gov',
    description: 'Controlled lists that classify local-government services and navigation, enabling consistent service data across councils.',
    dataCovered: 'Service classification, metadata and a controlled vocabulary',
    metadataApproach: 'Controlled vocabularies with stable identifiers',
    interoperability: 'The reuse target for any local-service taxonomy',
    connectsTo: ['istanduk', 'open-referral-uk'],
    urls: ['https://www.esd.org.uk/'],
  },
  {
    id: 'istanduk',
    name: 'iStandUK',
    owner: 'iStandUK (local government)',
    sector: 'local-gov',
    description: 'The body coordinating data and information standards for UK local public services.',
    dataCovered: 'Local-government data standards and guidance',
    interoperability: 'The convening point for local-gov standards',
    connectsTo: ['esd-lgsl'],
    urls: ['https://istanduk.org/'],
  },
  {
    id: 'open-referral-uk',
    name: 'Open Referral UK',
    owner: 'Open Referral UK (with mySociety)',
    sector: 'local-gov',
    description: 'An open standard for publishing community-services directory data (the "what services exist" layer).',
    dataCovered: 'Services, organisations, locations and contacts',
    formats: ['json', 'csv'],
    metadataApproach: 'Human Services Data Specification (HSDS) profile',
    interoperability: 'The standard to adopt for VCS / social-prescribing directories',
    connectsTo: ['esd-lgsl'],
    urls: ['https://openreferraluk.org/'],
  },
  {
    id: 'openactive',
    name: 'OpenActive',
    owner: 'OpenActive (Open Data Institute)',
    sector: 'local-gov',
    description: 'An open standard for publishing data about physical-activity opportunities and sessions.',
    dataCovered: 'Activity sessions, schedules, places and availability',
    formats: ['json'],
    metadataApproach: 'schema.org-based modelling',
    interoperability: 'A proven sector-wide schema.org profile',
    connectsTo: ['schema-org-dataset'],
    urls: ['https://www.openactive.io/'],
  },
  {
    id: 'uprn-usrn-llpg',
    name: 'GeoPlace UPRN / USRN & the LLPG',
    owner: 'GeoPlace',
    sector: 'local-gov',
    description: 'The authoritative address and street identifiers and the Local Land & Property Gazetteer behind them.',
    dataCovered: 'Properties, streets and addresses',
    identifiers: ['uprn', 'usrn'],
    formats: ['csv'],
    interoperability: 'Reuse UPRN/USRN rather than matching on free-text addresses',
    connectsTo: ['gss-geography'],
    urls: ['https://www.geoplace.co.uk/'],
  },

  // ---- Metadata, publishing & international ----
  {
    id: 'dcat-ap',
    name: 'DCAT / DCAT-AP',
    owner: 'W3C / European Commission',
    sector: 'metadata',
    description: 'The W3C vocabulary (and EU application profile) for describing datasets in a catalogue.',
    dataCovered: 'Dataset-level metadata: title, publisher, themes, distributions, licence',
    formats: ['rdf', 'json'],
    metadataApproach: 'RDF vocabulary, serialisable as JSON-LD',
    interoperability: 'The standard for making a dataset discoverable in cross-gov catalogues (data.gov.uk)',
    connectsTo: ['dublin-core', 'schema-org-dataset', 'dsa-catalogue'],
    urls: ['https://www.w3.org/TR/vocab-dcat-3/'],
  },
  {
    id: 'csvw',
    name: 'CSV on the Web (CSVW)',
    owner: 'W3C',
    sector: 'metadata',
    description: 'A standard for adding machine-readable schema and metadata to CSV files.',
    dataCovered: 'Tabular schema, datatypes, foreign keys and annotations for CSV',
    formats: ['csv', 'json'],
    metadataApproach: 'A JSON metadata descriptor alongside the CSV',
    interoperability: 'Turns a plain CSV return into a validated, typed, self-describing dataset',
    connectsTo: ['frictionless', 'json-schema'],
    urls: ['https://www.w3.org/TR/tabular-data-primer/'],
  },
  {
    id: 'frictionless',
    name: 'Frictionless Data — Table Schema & Data Package',
    owner: 'Open Knowledge Foundation',
    sector: 'metadata',
    description: 'A lightweight, widely-tooled way to describe a table\'s schema (Table Schema) and bundle data with metadata (Data Package).',
    dataCovered: 'Field types, constraints, primary/foreign keys, and a dataset package descriptor',
    formats: ['json', 'csv'],
    metadataApproach: 'datapackage.json + Table Schema',
    interoperability: 'A pragmatic, validator-rich default for publishing tabular standards',
    connectsTo: ['csvw', 'json-schema'],
    urls: ['https://specs.frictionlessdata.io/'],
  },
  {
    id: 'json-schema',
    name: 'JSON Schema',
    owner: 'JSON Schema (IETF drafts)',
    sector: 'metadata',
    description: 'The standard for describing and validating the structure of JSON data.',
    dataCovered: 'Object structure, types, required fields, patterns and constraints',
    formats: ['json'],
    metadataApproach: 'A schema document validating instances',
    interoperability: 'The validation contract for any JSON or API-delivered dataset',
    connectsTo: ['frictionless', 'csvw'],
    urls: ['https://json-schema.org/'],
  },
  {
    id: 'schema-org-dataset',
    name: 'schema.org Dataset',
    owner: 'schema.org',
    sector: 'metadata',
    description: 'The vocabulary search engines and Google Dataset Search use to understand datasets.',
    dataCovered: 'Dataset description metadata for the open web',
    formats: ['json'],
    metadataApproach: 'JSON-LD embedded in pages',
    interoperability: 'Maximises external discoverability; maps to DCAT',
    connectsTo: ['dcat-ap'],
    urls: ['https://schema.org/Dataset'],
  },
  {
    id: 'dublin-core',
    name: 'Dublin Core (DCMI Metadata Terms)',
    owner: 'Dublin Core Metadata Initiative',
    sector: 'metadata',
    description: 'A small, stable set of metadata terms (title, creator, date, subject…) reused by most metadata standards.',
    dataCovered: 'Generic resource metadata',
    interoperability: 'The lingua franca DCAT and others build on',
    connectsTo: ['dcat-ap'],
    urls: ['https://www.dublincore.org/specifications/dublin-core/dcmi-terms/'],
  },
  {
    id: 'iso-11179',
    name: 'ISO/IEC 11179 — Metadata registries',
    owner: 'ISO/IEC',
    sector: 'metadata',
    description: 'The standard for defining data elements and running a metadata registry — the discipline behind a good data dictionary.',
    dataCovered: 'Data-element definitions: object class, property, representation, permissible values',
    interoperability: 'The method for writing precise, reusable field definitions',
    connectsTo: ['cbds', 'nhs-data-dictionary'],
    urls: ['https://www.iso.org/standard/78914.html'],
  },
  {
    id: 'iso-8601',
    name: 'ISO 8601 — Dates and times',
    owner: 'ISO',
    sector: 'metadata',
    description: 'The unambiguous YYYY-MM-DD date/time representation mandated by the DSA.',
    dataCovered: 'Date and time fields',
    interoperability: 'Removes date ambiguity — a free interoperability win',
    connectsTo: ['dsa-catalogue'],
    urls: ['https://www.gov.uk/government/publications/open-standards-for-government/date-times-and-time-stamps-standard'],
  },
  {
    id: 'iso-3166',
    name: 'ISO 3166 — Country codes',
    owner: 'ISO (via the GOV.UK country register)',
    sector: 'metadata',
    description: 'Standard codes for countries and territories; in gov, use the country register.',
    dataCovered: 'Country / territory fields',
    interoperability: 'Reuse the register rather than a bespoke country list',
    connectsTo: ['govuk-registers'],
    urls: ['https://www.iso.org/iso-3166-country-codes.html'],
  },
  {
    id: 'prov-o',
    name: 'PROV-O — Provenance',
    owner: 'W3C',
    sector: 'metadata',
    description: 'A vocabulary for describing the provenance of data — who produced it, from what, when.',
    dataCovered: 'Lineage and provenance metadata',
    formats: ['rdf'],
    interoperability: 'Underpins trust and assurance claims about a dataset',
    connectsTo: ['dcat-ap'],
    urls: ['https://www.w3.org/TR/prov-o/'],
  },
  {
    id: 'fair',
    name: 'FAIR data principles',
    owner: 'GO FAIR',
    sector: 'metadata',
    description: 'Principles that data be Findable, Accessible, Interoperable and Reusable.',
    dataCovered: 'A goal framework, not a serialization',
    interoperability: 'The yardstick a good standard should satisfy',
    connectsTo: ['dcat-ap', 'five-star-open-data'],
    urls: ['https://www.go-fair.org/fair-principles/'],
  },
  {
    id: 'five-star-open-data',
    name: '5-Star Open Data',
    owner: 'Tim Berners-Lee / W3C',
    sector: 'metadata',
    description: 'A maturity scale from "available" to "linked open data".',
    dataCovered: 'A publishing-maturity scale',
    interoperability: 'A simple way to set and communicate a publishing ambition',
    connectsTo: ['fair'],
    urls: ['https://5stardata.info/'],
  },
];

// ---------------------------------------------------------------------------
// Relationships — the interoperability crosswalk graph
// ---------------------------------------------------------------------------

export const RELATIONSHIPS: Relationship[] = [
  { from: 'school-census', to: 'cbds', nature: 'depends-on', note: 'Built from CBDS data items' },
  { from: 'school-census', to: 'gias', nature: 'shares-identifier', note: 'URN / LA-Estab' },
  { from: 'school-census', to: 'npd', nature: 'feeds', note: 'Pupil micro-data into the NPD' },
  { from: 'school-census', to: 'ees', nature: 'publishes-via', note: 'Aggregates published via EES' },
  { from: 'ctf', to: 'school-census', nature: 'shares-identifier', note: 'UPN' },
  { from: 'ilr', to: 'gias', nature: 'shares-identifier', note: 'UKPRN' },
  { from: 'ilr', to: 'ees', nature: 'publishes-via' },
  { from: 'sen2', to: 'school-census', nature: 'shares-identifier', note: 'UPN' },
  { from: 'sen2', to: 'ssda903', nature: 'aligns-with', note: 'Overlapping vulnerable-child cohort' },
  { from: 'daily-attendance', to: 'school-census', nature: 'aligns-with', note: 'Same attendance concepts, different cadence' },
  { from: 'ssda903', to: 'cin-census', nature: 'aligns-with', note: 'Same children, different lens' },
  { from: 'cin-census', to: 'cp-is', nature: 'aligns-with', note: 'CP-plan children' },
  { from: 'cp-is', to: 'digital-child-health-fhir', nature: 'aligns-with', note: 'NHS Number eventing pattern' },
  { from: 'd2i-chat', to: 'ssda903', nature: 'depends-on' },
  { from: 'd2i-chat', to: 'cin-census', nature: 'depends-on' },
  { from: 'fhir-uk-core', to: 'snomed-ct', nature: 'depends-on', note: 'Codes resources with SNOMED' },
  { from: 'fhir-uk-core', to: 'nhs-data-dictionary', nature: 'aligns-with' },
  { from: 'prsb-healthy-child', to: 'fhir-uk-core', nature: 'profiles' },
  { from: 'digital-child-health-fhir', to: 'fhir-uk-core', nature: 'profiles' },
  { from: 'cp-is', to: 'nhs-data-dictionary', nature: 'depends-on' },
  { from: 'csvw', to: 'json-schema', nature: 'aligns-with' },
  { from: 'frictionless', to: 'csvw', nature: 'aligns-with' },
  { from: 'frictionless', to: 'json-schema', nature: 'depends-on', note: 'Table Schema constraints' },
  { from: 'dcat-ap', to: 'dublin-core', nature: 'depends-on' },
  { from: 'dcat-ap', to: 'schema-org-dataset', nature: 'aligns-with' },
  { from: 'schema-org-dataset', to: 'dcat-ap', nature: 'aligns-with' },
  { from: 'open-referral-uk', to: 'esd-lgsl', nature: 'aligns-with' },
  { from: 'openactive', to: 'schema-org-dataset', nature: 'profiles' },
  { from: 'esd-lgsl', to: 'istanduk', nature: 'depends-on' },
  { from: 'uprn-usrn-llpg', to: 'gss-geography', nature: 'aligns-with' },
  { from: 'gss-geography', to: 'govuk-registers', nature: 'aligns-with' },
  { from: 'govuk-registers', to: 'iso-3166', nature: 'depends-on' },
  { from: 'iso-8601', to: 'dsa-catalogue', nature: 'aligns-with' },
  { from: 'cbds', to: 'iso-11179', nature: 'aligns-with', note: 'Data-element discipline' },
  { from: 'nhs-data-dictionary', to: 'iso-11179', nature: 'aligns-with' },
  { from: 'fair', to: 'dcat-ap', nature: 'aligns-with' },
];

// ---------------------------------------------------------------------------
// Methods — how to design, assure and get a standard adopted
// ---------------------------------------------------------------------------

export const METHODS: MethodEntry[] = [
  {
    id: 'reuse-before-mint',
    title: 'Reuse before you mint',
    category: 'interoperability',
    summary:
      'Before defining a new field, identifier or codelist, search existing standards and registers. Reusing UPN, NHS Number, UPRN, GSS codes or a GOV.UK register is the single biggest interoperability and adoption win.',
    appliesTo: 'Every field',
    source: 'Open Standards Principles',
  },
  {
    id: 'minimum-viable-model',
    title: 'Minimum viable data model + extensions',
    category: 'schema-design',
    summary:
      'Define a small mandatory core that everyone can supply, with optional extensions and profiles for richer cases. Lower burden drives adoption; profiles preserve interoperability.',
    appliesTo: 'Schema shape',
    source: 'W3C Data on the Web Best Practices',
  },
  {
    id: 'iso-11179-definitions',
    title: 'Write precise data-element definitions',
    category: 'schema-design',
    summary:
      'For each field give an object class, property, representation and permissible values (ISO/IEC 11179). Ambiguous definitions are the main cause of inconsistent data.',
    appliesTo: 'Field definitions',
    source: 'ISO/IEC 11179',
  },
  {
    id: 'controlled-vocab',
    title: 'Prefer controlled vocabularies to free text',
    category: 'schema-design',
    summary:
      'Wherever a value can be constrained, point to a published codelist or register and govern it with a release cycle. Free text where a codelist exists destroys comparability.',
    appliesTo: 'Enumerated fields',
  },
  {
    id: 'iso-8601-dates',
    title: 'Use ISO 8601 dates and explicit units',
    category: 'schema-design',
    summary: 'Mandate YYYY-MM-DD and state units explicitly. Removes a whole class of avoidable errors.',
    appliesTo: 'Date and measure fields',
    source: 'DSA standards',
  },
  {
    id: 'semver',
    title: 'Version with SemVer and a deprecation policy',
    category: 'governance',
    summary:
      'Give the standard a version, change log and a clear deprecation window. Consumers must be able to depend on stability and anticipate breaking change.',
    appliesTo: 'The standard as a whole',
  },
  {
    id: 'machine-and-human',
    title: 'Publish machine- and human-readable together',
    category: 'metadata',
    summary:
      'Ship a validatable schema (JSON Schema / Table Schema / CSVW) alongside prose. Tooling enforces conformance; prose drives understanding and adoption.',
    appliesTo: 'Publication',
    source: 'Frictionless / CSVW',
  },
  {
    id: 'conformance-validation',
    title: 'Provide conformance rules and a validator',
    category: 'assurance',
    summary:
      'State testable conformance rules and give providers a way to validate before they submit. Validation at source is cheaper than correction downstream.',
    appliesTo: 'Assurance',
  },
  {
    id: 'lawful-basis-first',
    title: 'Pin the lawful basis and run a DPIA',
    category: 'legal',
    summary:
      'Identify the UK GDPR Article 6 (and Article 9 for special-category) basis before collecting, and complete a Data Protection Impact Assessment for anything sensitive or about children.',
    appliesTo: 'Personal data',
    source: 'ICO Data Sharing Code',
  },
  {
    id: 'collect-once',
    title: 'Collect once, use many times',
    category: 'adoption',
    summary:
      'Map what providers already hold and how, then collect only the delta. Reusing an existing extract (e.g. an automated MIS feed) beats a new manual return for both burden and quality.',
    appliesTo: 'Collection design',
  },
  {
    id: 'crosswalk-overlaps',
    title: 'Crosswalk to overlapping standards',
    category: 'interoperability',
    summary:
      'Where another standard covers some of the same ground, publish an explicit mapping. A crosswalk lets data flow between standards instead of trapping it.',
    appliesTo: 'Interoperability',
  },
  {
    id: 'governance-owner',
    title: 'Name an owner and a governance route',
    category: 'governance',
    summary:
      'Standards rot without stewardship. Name the owning body, the change process and how challenges are handled (the Open Standards Board / a PRSB-style assurance body).',
    appliesTo: 'Sustainability',
  },
  {
    id: 'federate-dont-centralise',
    title: 'Federate analysis; don\'t centralise custody',
    category: 'governance',
    summary:
      'The Data to Insight and IDS precedents show you can get a national analytical view without a single national database. Centralised "totality" stores (ContactPoint) carry heavy proportionality risk.',
    appliesTo: 'Architecture & trust',
  },
  {
    id: 'dcat-catalogue',
    title: 'Describe the dataset with DCAT metadata',
    category: 'metadata',
    summary:
      'Wrap the dataset in DCAT(-AP) catalogue metadata so it is discoverable and consistently described across government catalogues.',
    appliesTo: 'Discoverability',
    source: 'DCAT-AP / DSA',
  },
  {
    id: 'provenance',
    title: 'Record provenance and quality',
    category: 'assurance',
    summary:
      'State where each part comes from (PROV-O) and describe quality against the Government Data Quality Framework dimensions, so consumers can judge fitness for use.',
    appliesTo: 'Trust',
    source: 'GDQF / PROV-O',
  },
  {
    id: 'adopt-existing-provider-standards',
    title: 'Meet providers where they already are',
    category: 'adoption',
    summary:
      'If providers already hold the data in another standard (e.g. an MIS export, a FHIR record), design the new standard as a mapping/profile of that rather than a parallel ask.',
    appliesTo: 'Adoption',
  },
];

// A combined catalog accessor — seed entries, merged at runtime with any
// research-enriched entries via mergeCatalog().
export function mergeCatalog(extra: StandardEntry[] = []): StandardEntry[] {
  const byId = new Map<string, StandardEntry>();
  for (const s of SEED_CATALOG) byId.set(s.id, s);
  for (const s of extra) {
    if (!s || !s.id) continue;
    const cur = byId.get(s.id);
    if (cur) {
      byId.set(s.id, {
        ...s,
        ...cur, // seed wins on curated fields
        urls: Array.from(new Set([...(cur.urls || []), ...(s.urls || [])])),
        connectsTo: Array.from(new Set([...(cur.connectsTo || []), ...(s.connectsTo || [])])),
      });
    } else {
      byId.set(s.id, s);
    }
  }
  return Array.from(byId.values());
}

// Seed (hand-verified) entries plus any additional standards from the research
// pass. Seed wins on shared ids, so this only broadens coverage.
export const CATALOG: StandardEntry[] = mergeCatalog(RESEARCH_CATALOG);

export function standardById(id: string): StandardEntry | undefined {
  return CATALOG.find((s) => s.id === id);
}
export function identifierById(id: string): IdentifierEntry | undefined {
  return IDENTIFIERS.find((i) => i.id === id);
}
