// Research-enriched catalog entries.
//
// The seed catalog in knowledge.ts is hand-verified. This file holds ADDITIONAL
// standards surfaced by the structured data-standards research pass that were
// not already in the seed — normalised to the local Sector union and kept
// concise. Merged on top of the seed via mergeCatalog(); seed entries win on
// any shared id, so this only ever adds coverage, never overrides.

import type { StandardEntry } from './types';

export const RESEARCH_CATALOG: StandardEntry[] = [
  {
    id: 'find-and-use-standards',
    name: 'DfE Find and Use Standards (data standards register)',
    owner: 'Department for Education',
    sector: 'education',
    description:
      "DfE's register of recommended data standards for the education sector — the first place to look before defining a new education data item.",
    dataCovered: 'Recommended formats for common education data items (dates, names, identifiers, phases)',
    interoperability: 'A sector data-standards catalogue — reuse from here rather than minting new.',
    connectsTo: ['cbds', 'gias'],
    urls: ['https://www.gov.uk/guidance/data-standards'],
  },
  {
    id: 'school-workforce-census',
    name: 'School Workforce Census',
    owner: 'Department for Education',
    sector: 'education',
    description: 'The annual individual-level census of the school workforce, keyed on the Teacher Reference Number.',
    dataCovered: 'Staff demographics, role, pay, absence and qualifications',
    identifiers: ['trn'],
    formats: ['xml'],
    collectionMethod: 'Statutory return via COLLECT',
    frequency: 'Annual',
    cadence: 'annual',
    connectsTo: ['cbds', 'gias'],
    urls: ['https://www.gov.uk/guidance/school-workforce-census'],
  },
  {
    id: 'nccis',
    name: 'NCCIS (CCIS) — 16-17 participation tracking',
    owner: 'Department for Education',
    sector: 'education',
    description: 'The monthly management-information return tracking the activity (education, employment, NEET) of 16–17 year olds.',
    dataCovered: 'Participation status and contact for young people, keyed on the Client Caseload Information System standard',
    identifiers: ['uln'],
    formats: ['xml'],
    collectionMethod: 'Monthly return from CCIS client systems',
    frequency: 'Monthly',
    cadence: 'monthly',
    connectsTo: ['ilr'],
    urls: ['https://www.gov.uk/government/publications/nccis-management-information-requirement'],
  },
  {
    id: 'mhsds',
    name: 'Mental Health Services Data Set (MHSDS)',
    owner: 'NHS England',
    sector: 'health',
    description: 'A patient-level secondary-uses data set covering people in contact with mental-health, learning-disability and autism services.',
    dataCovered: 'Referrals, contacts, assessments and outcomes',
    identifiers: ['nhs-number', 'ods-code'],
    formats: ['csv', 'xml'],
    collectionMethod: 'Monthly submission to the Bureau Service Portal',
    frequency: 'Monthly',
    cadence: 'monthly',
    assurance: 'An approved NHS information standard (DCB)',
    connectsTo: ['nhs-data-dictionary'],
    urls: ['https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/mental-health-services-data-set'],
  },
  {
    id: 'dcb0129',
    name: 'Information Standards (DCB) approval route',
    owner: 'NHS England',
    sector: 'health',
    description: 'The governance route by which a health data standard becomes a formally approved Information Standard (an ISN/DCB notice with conformance dates).',
    dataCovered: 'Standards governance (not a dataset)',
    assurance: 'The formal assurance gate for any NHS data standard',
    interoperability: 'The health analogue of the Open Standards Board process',
    connectsTo: ['nhs-data-dictionary'],
    urls: ['https://digital.nhs.uk/data-and-information/information-standards'],
  },
  {
    id: 'orgref-companies-house',
    name: 'Companies House register & API',
    owner: 'Companies House',
    sector: 'cross-gov',
    description: 'The authoritative register of UK companies, with an open API keyed on the company registration number.',
    dataCovered: 'Company identity, status, officers and filings',
    identifiers: ['companies-house-number'],
    formats: ['json'],
    publishing: 'Open REST API and bulk data',
    interoperability: 'The reference register for any company-identifying field',
    connectsTo: ['govuk-registers'],
    urls: ['https://developer.company-information.service.gov.uk/'],
  },
  {
    id: 'inspire',
    name: 'INSPIRE / ISO 19115 geographic metadata',
    owner: 'European Commission / ISO (UK implementation via DEFRA)',
    sector: 'metadata',
    description: 'The standard for describing and sharing spatial datasets and services, used for UK geospatial open data.',
    dataCovered: 'Geospatial dataset metadata and services',
    formats: ['rdf', 'xml'],
    metadataApproach: 'ISO 19115 / 19139 metadata profiles',
    interoperability: 'The geospatial counterpart to DCAT for location data',
    connectsTo: ['dcat-ap', 'gss-geography'],
    urls: ['https://www.gov.uk/guidance/inspire-metadata'],
  },
  {
    id: 'open-data-certificate',
    name: 'ODI Open Data Certificate',
    owner: 'Open Data Institute',
    sector: 'metadata',
    description: 'A framework that rates how well an open dataset is published — legally, practically, technically and socially.',
    dataCovered: 'A publishing-quality assessment (not a serialization)',
    interoperability: 'A way to set and evidence a publishing-quality bar',
    connectsTo: ['five-star-open-data', 'fair'],
    urls: ['https://theodi.org/insights/tools/open-data-certificate/'],
  },
  {
    id: 'ons-harmonised',
    name: 'ONS / GSS Harmonised Standards',
    owner: 'Office for National Statistics (GSS)',
    sector: 'cross-gov',
    description: 'Harmonised concepts, questions and output categories (e.g. ethnicity, disability, sex, national identity) for use across government data collection.',
    dataCovered: 'Standard question wording and code categories for demographic and social data',
    metadataApproach: 'Published harmonised principles with definitive code lists',
    interoperability: 'Reuse harmonised categories so demographic data is comparable across datasets',
    connectsTo: ['gss-geography', 'gdqf'],
    urls: ['https://gss.civilservice.gov.uk/policy-store/?keyword=harmonisation'],
  },
  {
    id: 'gov-security-classifications',
    name: 'Government Security Classifications Policy (GSCP)',
    owner: 'Cabinet Office',
    sector: 'cross-gov',
    description: 'The OFFICIAL / SECRET / TOP SECRET classification scheme and handling caveats that govern how data must be protected.',
    dataCovered: 'Classification and handling rules (not a dataset)',
    assurance: 'Sets the protective-marking and handling clause every standard needs',
    connectsTo: ['dspt'],
    urls: ['https://www.gov.uk/government/publications/government-security-classifications'],
  },
  {
    id: 'digital-economy-act',
    name: 'Digital Economy Act 2017 (Part 5) — data-sharing powers',
    owner: 'DSIT / Cabinet Office',
    sector: 'cross-gov',
    description: 'The statutory gateways and codes of practice that permit specified public-service data sharing between government bodies.',
    dataCovered: 'A legal basis for data sharing (not a dataset)',
    assurance: 'The lawful gateway that can underpin cross-domain sharing (e.g. a consistent child identifier)',
    connectsTo: ['consistent-child-identifier'],
    urls: ['https://www.gov.uk/government/collections/digital-economy-act-2017-part-5-codes-of-practice'],
  },
  {
    id: 'govuk-one-login',
    name: 'GOV.UK One Login & the Digital Identity (DIATF) trust framework',
    owner: 'Government Digital Service',
    sector: 'cross-gov',
    description: 'The single sign-on and identity-assurance framework for government services.',
    dataCovered: 'Identity assurance and authentication',
    interoperability: 'The reference for identity where a dataset involves verified individuals or staff',
    connectsTo: [],
    urls: ['https://www.sign-in.service.gov.uk/'],
  },
  {
    id: 'iso-codelists',
    name: 'ISO codelists — 4217 (currency), 639 (language), 5218 (sex)',
    owner: 'ISO',
    sector: 'metadata',
    description: 'Stable international code lists for currency, language and the representation of human sex — reuse rather than inventing local codes.',
    dataCovered: 'Currency, language and sex/gender coded fields',
    interoperability: 'Free, unambiguous codelists for common fields',
    connectsTo: ['iso-3166', 'govuk-registers'],
    urls: ['https://www.iso.org/standards.html'],
  },
  {
    id: 'openapi',
    name: 'OpenAPI Specification (OAS 3.x)',
    owner: 'OpenAPI Initiative (Linux Foundation)',
    sector: 'metadata',
    description: 'The standard for describing a REST API contract, mandated by GOV.UK API technical standards.',
    dataCovered: 'API endpoints, request/response schemas and authentication',
    formats: ['json'],
    metadataApproach: 'An OpenAPI document describing the API',
    interoperability: 'The contract that lets providers (incl. vendors) integrate against an API-delivered standard',
    collectionMethod: 'rest-api',
    connectsTo: ['json-schema'],
    urls: ['https://spec.openapis.org/oas/latest.html'],
  },
  {
    id: 'wcag-accessibility',
    name: 'WCAG 2.2 & the Public Sector Bodies Accessibility Regulations',
    owner: 'W3C / Cabinet Office (GDS)',
    sector: 'metadata',
    description: 'The accessibility requirements that any published standard, tool or data service must meet.',
    dataCovered: 'Accessibility of the human-readable standard and any service around it',
    assurance: 'A legal requirement for public-sector digital publications',
    connectsTo: [],
    urls: ['https://www.w3.org/TR/WCAG22/'],
  },
  {
    id: 'ocds',
    name: 'Open Contracting Data Standard (OCDS)',
    owner: 'Open Contracting Partnership',
    sector: 'cross-gov',
    description: 'An open standard for publishing structured data across the public-procurement lifecycle.',
    dataCovered: 'Tenders, awards, contracts and spend',
    formats: ['json'],
    metadataApproach: 'A JSON Schema-defined release/record model',
    interoperability: 'The reuse target for any procurement or contracts dataset',
    connectsTo: ['json-schema', 'companies-house-number'],
    urls: ['https://standard.open-contracting.org/'],
  },
  {
    id: 'ap-census',
    name: 'Alternative Provision Census',
    owner: 'Department for Education',
    sector: 'education',
    description: 'The statutory return covering pupils placed in alternative provision and (formerly) pupil referral units.',
    dataCovered: 'Pupils in alternative provision, placements and characteristics',
    identifiers: ['upn'],
    formats: ['xml'],
    collectionMethod: 'Statutory return via COLLECT',
    frequency: 'Annual',
    cadence: 'annual',
    connectsTo: ['cbds', 'school-census'],
    urls: ['https://www.gov.uk/guidance/alternative-provision-census'],
  },
  {
    id: 'cme-cnis',
    name: 'Children Missing Education / Children Not in School registers',
    owner: 'Department for Education / local authorities',
    sector: 'education',
    description: 'Data standards for tracking children missing education and the new Children Not in School registers.',
    dataCovered: 'Children outside mainstream education and home-educated children',
    identifiers: ['upn'],
    interoperability: 'A growing safeguarding-relevant collection needing an identifier that crosses school moves',
    connectsTo: ['school-census', 'ssda903'],
    urls: ['https://www.gov.uk/government/publications/children-missing-education'],
  },
  {
    id: 'csds',
    name: 'Community Services Data Set (CSDS / CYPHS)',
    owner: 'NHS England',
    sector: 'health',
    description: 'The patient-level data set for community health services, including children and young people (health visiting, school nursing).',
    dataCovered: 'Community-health referrals, contacts and child-health reviews',
    identifiers: ['nhs-number', 'ods-code'],
    formats: ['csv', 'xml'],
    collectionMethod: 'Monthly submission',
    frequency: 'Monthly',
    cadence: 'monthly',
    connectsTo: ['nhs-data-dictionary', 'prsb-healthy-child'],
    urls: ['https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/community-services-data-set'],
  },
  {
    id: 'ncmp',
    name: 'National Child Measurement Programme (NCMP)',
    owner: 'NHS England / OHID',
    sector: 'health',
    description: "The annual programme measuring the height and weight of children in Reception and Year 6.",
    dataCovered: 'Child height, weight and BMI at two school points',
    identifiers: ['nhs-number', 'upn'],
    collectionMethod: 'Annual measurement in schools',
    frequency: 'Annual',
    cadence: 'annual',
    interoperability: 'A rare dataset that legitimately spans school and health populations',
    connectsTo: ['school-census', 'csds'],
    urls: ['https://digital.nhs.uk/services/national-child-measurement-programme'],
  },
  {
    id: 'nspl',
    name: 'National Statistics Postcode Lookup (NSPL / ONSPD)',
    owner: 'Office for National Statistics',
    sector: 'cross-gov',
    description: 'The lookup that maps postcodes to statistical and administrative geographies.',
    dataCovered: 'Postcode-to-geography lookups',
    identifiers: ['gss-code'],
    formats: ['csv'],
    interoperability: 'Resolve postcodes to standard geographies rather than storing free-text areas',
    connectsTo: ['gss-geography', 'uprn-usrn-llpg'],
    urls: ['https://geoportal.statistics.gov.uk/'],
  },
];
