// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import { getCredential } from '$lib/integrations/credentials';
import { createDAVClient } from 'tsdav';
import { registerIntegrationAdapter } from '$lib/integrations/registry';

registerIntegrationAdapter({
  integrationType: "apple-calendar",
  resolveOptions: async (fieldName: string, credentialId: string) => {
  switch (fieldName) {
    case "calendar": {
      const cred = await getCredential<'basic'>(credentialId);
            if (!cred) return [];
            const client = await createDAVClient({
              serverUrl: 'https://caldav.icloud.com',
              credentials: { username: cred.payload.username, password: cred.payload.password },
              authMethod: 'Basic',
              defaultAccountType: 'caldav',
            });
            const calendars = await client.fetchCalendars();
            return calendars.map((c: any) => ({ value: c.url, label: c.displayName || c.url }));
    }
    default:
      throw new Error(`Unknown resource-picker fieldName: ${fieldName}`);
  }
},
  testCredential: async (credentialId: string) => {
  const cred = await getCredential<'basic'>(credentialId);
      if (!cred) throw new Error('Credential not found');
      const client = await createDAVClient({
        serverUrl: 'https://caldav.icloud.com',
        credentials: { username: cred.payload.username, password: cred.payload.password },
        authMethod: 'Basic',
        defaultAccountType: 'caldav',
      });
      await client.fetchCalendars();
},
});
