// Wordle Race valid guesses (6346): every five-letter lowercase a–z word the
// system Hunspell dictionary (/usr/share/hunspell/en_US.dic, SCOWL-derived)
// generates, base words plus their affix expansions (plurals, past tenses) run
// through en_US.aff — so "cakes" and "tried" are guessable though never secret.
// British spellings the US dictionary lacks were added (fibre, metre, odour,
// mould, ochre, kerbs, tyres), slurs and the crudest words were taken out, and
// every word in ANSWERS is included.
//
// Sorted, space-separated to keep the module small; split once at load.

export const ALLOWED: readonly string[] = `
  aalii abaca aback abaft abamp abase abash abate abbes abbey abbot abeam abele abets abhor abide
  abies abler abmho abode abohm about above abuts abuzz abysm abyss acari accel acerb ached aches
  achoo acids acing acini acmes acned acorn acred acres acrid acted actin actor acute adage adapt
  addax added adder addle adept adieu adits adman admen admin admit admix adobe adopt adore adorn
  adown adult adust adzes aecia aedes aegis aerie aeron affix afire afoot afore afoul afrit after
  again agama agape agate agave agent agger aggie aggro agile aging agios agist agita aglet agley
  aglow agone agony agora agree agric agron ahead aided aider aides ailed aimed aioli aired airts
  aisle aitch akees akene alack alarm alary alate album alder aldol aleph alert algae algal algid
  algin algor alias alibi alien align alike alive alkyd alkyl allay allee alley allot allow alloy
  allyl aloes aloft aloha aloin alone along aloof aloud alpha altar alter altos alula alums amahs
  amain amass amaze amber ambit amble ambos ambry amend ament amice amide amine amino amiss amity
  amnio among amour ample amply amuse ancon anear anele anent angel anger angle angry angst anile
  anils anima anime anion anise ankhs ankle ankus annal annas annex annoy annul anoas anode anole
  anons anted antes antic antiq antis antre antsy anvil apace apart apeak apery aphid aphis apian
  aping apish apnea aport appel apple apply apron apses apsis apter aptly aquas araks arbor arced
  archt ardeb ardor areal areas areca arena arete argal argil argol argon argot argue arias arils
  arise armed armet armor aroid aroma arose arras array arris arrow arsed arsis arson artel artsy
  arums ascot ascus asdic ashed ashen ashes aside asked asker askew aspen asper aspic assai assay
  asses asset assoc aster astir atilt atlas atman atoll atoms atomy atone atony atria atrip attar
  attic audio audit auger aught augur aulic aulos aunts aural aurar auras auric aurum autos auxin
  avail avast avens avers avert avian avion avoid avoir avows await awake award aware awash awful
  awing awned awoke axial axils axing axiom axles axons ayahs ayins azide azine azoic azole azote
  azoth azure baaed babas babel babes babul baccy backs bacon badge badly bagel baggy bahts bails
  bairn baits baiza baize baked baker bakes balas balds baled baler bales balks balky balls bally
  balms balmy balsa banal bands bandy banes bangs banjo banks banns barbs barde bards bared barer
  bares barfs barge baric barit barks barms barmy barns baron barre barye basal based baser bases
  basic basil basin basis basks basso baste batch bated bates bathe baths batik baton batty bauds
  bawds bawdy bawls bayed bazar beach beads beady beaks beams beamy beano beans beard bears beast
  beats beaus beaut bebop becks bedel bedew bedim beech beefs beefy beeps beers beery beets befit
  befog began begat beget begin begot begum begun beige being belay belch belga belie bells belly
  below belts bemas bench bends bendy benne bents beret bergs berks berms berry berth beryl beset
  besom besot bests betas betel beths betta bevel bevvy bezel bhaji bhang bialy bible bicep biddy
  bides bidet bield biers biffs bifid bight bigot bijou biked biker bikes bilbo bilge bilks bills
  bimah binal binds bines binge bingo biome biota biped bipod birch birds birls birrs birth bises
  bison biter bites bitts bitty blabs black blade blags blahs blain blame bland blank blare blase
  blast blate blats blaze bleak blear bleat blebs bleed bleep blend bless blimp blind bling blini
  blink blips bliss blitz bloat blobs block blocs blogs bloke blond blood bloom bloop blots blown
  blows blowy blued bluer blues bluet bluey bluff blunt blurb blurs blurt blush board boars boart
  boast boats boded bodes bodge boffo bogey boggy bogie bogle bogon bogus boils boink bolas boles
  bolls bolos bolts bolus bombe bombs bonce bonds boned bones bongo bongs bonks bonne bonny bonus
  bonze boobs booed books booms boong boons boors boost booth boots boozy borak borax bored borer
  bores boric borne boron bosky boson bossy botch botel bothy bough boule bound bouse bouts bovid
  bowed bower bowls bowse boxed boxen boxer boxes boyar boyla bozos brace brach bract brads braes
  brags braid brail brain brake brand brant brash brass brats brave bravo brawl brawn braxy brays
  braze bread break bream brede breed breve brews bribe brick bride brief brier brigs brill brims
  brine bring brink briny brisk brits broad broch broil broke bronc brood brook broom brose broth
  brown brows bruin bruit brume brunt brush brute bubal bucko bucks buddy budge buffo buffs buggy
  bugle buhls build built bulbs bulge bulgy bulks bulky bulla bulls bully bumph bumps bumpy bunch
  bunco bungs bunks bunny bunts buoys buran burbs buret burgh burgs burin burka burls burly burns
  burnt burps burro burrs burry bursa burse burst busby bused buses bushy busks busts busty buteo
  butte butts butty butut butyl buxom buyer bwana bylaw byres bytes byway cabal cabby caber cabin
  cable cabob cacao cache cacti cadet cadge cadre cafes caffs caged cager cages cagey caird cairn
  caked cakes calks calla calls calms calve calyx camel cameo campo camps campy canal candy caned
  caner canes canna canny canoe canon canso canst canto cants canty caped caper capes capon capos
  caput carat carbs cards cared carer cares caret cargo carks carny carob carol carom carpi carps
  carry carse carte carts carve cased cases casks casts catch cater catty cauda caulk cauls cause
  caved caver caves cavie cavil cawed cease cecal cecum cedar ceded ceder cedes cedis ceiba celeb
  cella cello cells celom cense cento cents ceorl cered ceres ceria ceric ceros certs cesta chads
  chafe chaff chain chair chalk champ chant chaos chape chaps chard chare charm charr chars chart
  chary chase chasm chats chaws cheap cheat check cheek cheep cheer chefs chela chert chess chest
  chews chewy chiao chick chide chief child chili chill chimb chime chimp china chine ching chink
  chino chins chips chirk chirm chirp chirr chits chive chivy chock chocs choir choke choli chomp
  chook chops chord chore chose chows chron chubs chuck chufa chuff chugs chump chums chunk churl
  churn churr chute chyle chyme ciaos cider cigar cilia cimex cinch circa cirri cited cites civet
  civic civil clack clade claim clamp clams clang clank clans claps claro clash clasp class clave
  clavi claws clays clean clear cleat cleek clefs cleft clepe clerk clews click cliff climb clime
  cline cling clink clips clits cloak clock clods clogs clomb clomp clone clonk clops close cloth
  clots cloud clout clove clown cloys clubs cluck clued clues clump clung clunk clvii clxii clxiv
  clxix clxvi coach coact coals coaly coast coati coats cobia coble cobra cocci cocks cocoa cocos
  codas coded coder codes codex codon coeds cogon cohos coifs coign coils coins coirs coked cokes
  colas colds coles coley colic colly colon color colts colza comas combe combo combs comdg comer
  comes comet comfy comic comma compo comps conch coned cones conga conic conks conns contd conte
  conto contr cooed cooee cooks cools coomb coons coops coots copal copay coped coper copes copra
  copse coral cords cored corer cores corgi coria corks corms corns cornu corny corps corse cosec
  coset coste costs cotes cotta couch cough could count coupe coups court couth coven cover coves
  covet covey covin cowed cower cowls coxae coxed coxes coyer coyly coypu cozen craal crabs crack
  craft crags crake cramp crams crane crank crape crapy crash crass crate crave crawl craws crays
  craze crazy creak cream credo creed creek creel creep crepe crept cress crest crews cribs crick
  cried crier cries crime crimp crine crisp croak crock croft crone cronk crony crook croon crops
  cross croup crowd crown crows croze cruck crude cruel cruet cruft crumb crump cruse crush crust
  crwth crypt cryst cubby cubeb cubed cuber cubes cubic cubit cuffs cuing cukes culch culet culex
  culls cully culms culpa cults cumin cunts cupel cuppa curbs curch curds curdy cured curer cures
  curet curia curie curio curls curly curry curse curve curvy cusec cushy cusks cusps cutch cuter
  cutey cutie cutin cutis cutty cutup cycad cycle cylix cymar cymas cymes cynic cysts cyton czars
  daces dacha dadas daddy dagos dahls daily dairy daisy dales dally daman damar dames damns damps
  dance dandy dangs danio dared darer dares daric darky darns darts dated dater dates datum daube
  daubs daunt davit dawns dazed dazes dding deals dealt deans dears deary death debag debar debit
  debts debug debus debut decaf decal decay decks decor decoy decry dedal deeds deems deeps defer
  defog degas deice deify deign deism deist deity dekko delay delft delis dells delta delve demit
  demob demon demos demur denar denim denom dense dents depot depth derby deriv derma derry desex
  desks deter detox deuce devil dewan dhobi dhole dhoti dhows dials diary diazo diced dicer dices
  dicey dicks dicot dicta didst diets diffs dight digit diked dikes dills dilly dimer dimes dimly
  dinar dined diner dines dinge dingo dings dingy dinky dints diode dippy dipso direr dirge dirks
  dirty disco discs dishy disks distr ditch ditsy ditto ditty divan divas dived diver dives divot
  divvy diwan dizen dizzy dobby dobla dobra dobro docks dodge dodgy dodos doers doffs doges doggo
  doggy dogie dogma doily doing dolce doled doles dolls dolor dolts domed domes donas donee donga
  dongs donne donor dooms doors doozy doped doper dopes dopey dorks dorky dorms dorty dosed doses
  doted doter dotes dotty doubt douce dough douma douse doves dowdy dowel dower dowie downs downy
  dowse doyen dozed dozen dozer dozes drabs draff draft drags drain drake drama drams drank drape
  drawl drawn draws drays dread dream drear dregs dress dried drier dries drift drill drink drips
  drive droit droll drone drool droop drops dross drove drown drubs drugs druid drums drupe druse
  dryad dryer dryly duads duals ducal ducat duchy ducks ducts duded dudes duels duets duffs dukes
  dulia dulls dully dulse dumbo dummy dumps dumpy dunce dunes dungs dunks duomo duped duper dupes
  duple duppy durra durst durum dusky dusts dusty dutch duvet dwarf dweeb dwell dwelt dyads dyers
  dying dykes dynes eager eagle eagre eared earls early earns earth eased easel eases eaten eater
  eaves ebbed ebony echos eclat edema edged edger edges edict edify edits educe educt eerie effed
  egads egest egged egger egret eider eidos eight eikon eject eking eland elate elbow elder elect
  elegy elemi elfin elide elite elope elude elute elver email embay embed ember embow embus emcee
  emend emirs emits emmer emoji emote empty enact enate ended endow endue enema enemy engin enjoy
  ennui ensue enter entry envoi envoy eosin epact epees ephah ephod ephor epics epoch epode epoxy
  equal equip equiv erase ergot ernes erode erose erred error eruct erugo erupt esker essay ester
  estop ether ethic ethos ethyl etnas etude etuis euros evade evens event evert every evict evils
  evite evoke ewers exact exalt exams excel exeat execs exert exile exine exist exits exons expat
  expel expos extol extra exude exult exurb eyras eyrir fable faced facer faces facet facts faddy
  faded fader fades fadge faena faffs fagot fails faint fairs fairy faith faked faker fakes fakir
  falls false famed fancy fango fangs fanon faqir farad farce farci farcy fared farer fares farms
  farts fasts fatal fated fates fatly fatwa faugh fault fauna fauns fauve faves favor favus fawns
  faxed faxes fayer fazed fazes fears feast feats fecal fecit feeds feels feeze feign feint felid
  fells felly felon felts femme femur fence fends fenny feoff feral feria fermi ferns ferny ferry
  fests fetch feted fetes fetid fetor feuar feuds fever fewer feyly fiats fiber fibre fiche fichu
  ficus fidge fiefs field fiend fiery fifer fifes fifth fifty fight filar filch filed filer files
  filet fills filly films filmy filth filum final finch finds fined finer fines finis finks finny
  fired firer fires firms firry first firth fiscs fishy fists fitly fiver fives fixed fixer fixes
  fizzy fjeld fjord flags flail flair flake flaky flame flank flans flaps flare flash flask flats
  flaws flawy flays fleam fleas fleck fleer flees fleet flesh flews flick flied flier flies fling
  flint flips flirt flite flits float flock flocs floes flogs flong flood floor flops flora flory
  floss flour flout flown flows flubs flues fluff fluid fluke fluky flume flump flung flunk fluor
  flush flute fluty flyby flyte foals foams foamy focal focus foehn foggy foils foist folds folia
  folic folie folio folks folly fonts foods fools foots footy foray forby force fordo fords fores
  forge forgo forks forme forms forte forth forts forty forum fossa fosse fouls found fount fours
  fovea fowls foxed foxes foyer frack frags frail frame franc frank fraps frats fraud frays freak
  freed freer frees fremd frena fresh frets friar fried fries frigs frill frisk frith frize frizz
  frock frogs frond frons front frore frosh frost froth frown froze fruit frump fryer fubsy fucks
  fucus fudge fuels fugal fuggy fugue fulls fully fumed fumes funds fungi fungo funks funky funny
  furan furls furor furry furze furzy fused fusee fuses fusil fussy fusty futon fuzzy gable gadid
  gaffe gaffs gaily gains gaits galah galas galea gales galls galop gamba gamed gamer games gamic
  gamin gamma gammy gamps gamut ganef gangs ganja ganof gaped gapes gappy garbs garth gases gasps
  gassy gated gater gates gauds gaudy gauge gaunt gaurs gauss gauze gauzy gavel gawks gawky gawps
  gayer gazed gazer gazes geans gears gecko geeks geeky geese geest gelds gelid gemmy gemot genes
  genet genic genie genii genip genit genoa genre genro gents genus geode geoid gerah germs germy
  gesso getup ghats ghazi ghees ghost ghoul ghyll giant gibed giber gibes giddy gifts gigot gigue
  gilds gills gilts gimel gimps gimpy gipon girds girls girly giros girth girts gites given giver
  gives gizmo glace glade glads glair gland glans glare glary glass glaze gleam glean glebe glede
  gleet glens glias glide glint glitz gloam gloat globe globs gloms gloom glory gloss glove glows
  gloze glued glues gluey glume gluon gluts glyph gnarl gnash gnats gnaws gnome goads goals goats
  godly goers gofer going golds golem golfs golly gonad gongs gonif gonks goods goody gooey goofs
  goofy gooks goons goose goosy gopak goral gored gores gorge gorps gorse goths gouge gourd gouty
  gowan gowns goyim grabs grace grade grads graft grail grain grams grand grans grant grape graph
  grasp grass grate grave gravy grays graze great grebe greed green greet greps gride grids grief
  grift grill grime grimy grind grins gripe grips grist grith grits groan groat groks groom grope
  gross grosz grots group grout grove growl grown grows grubs gruel grues gruff grume grump grunt
  guaco guano guans guard guars guava gucks guess guest guide guild guile guilt guise gulag gulas
  gulch gules gulfs gulls gully gulps gumbo gumma gummy gunge gungy gunky guppy gurge gurus gushy
  gussy gusto gusts gusty gutsy gutta gutty guyed guyot gyral gyres gyron gyros gyrus gyved gyves
  habit hacek hacks hades hadst hafiz hafts haiku hails hairs hairy hajes hajji hakes hakim halal
  haled haler hales halls halms halon halos halts halve hamal hames hammy hamza hance hands handy
  hangs hanks haole haply happy hards hardy hared hares harks harms harps harpy harsh harts hasps
  haste hasty hatch hated hater hates haugh haulm hauls haunt haven haver haves havoc hawed hawks
  hawse hayed hazan hazed hazel hazer hazes hdqrs heads heady heals heaps heard hears heart heath
  heats heave heavy heder hedge heeds heels hefts hefty heirs heist helix hello hells helms helot
  helps helve hemal hemic hemin hence henge henna herbs herby herds heres heron hertz heths hewed
  hewer hexad hexed hexer hexes hexyl hicks hided hider hides highs hight hijab hiked hiker hikes
  hills hilly hilts hilum hinds hinge hings hinny hints hippo hippy hired hirer hires hitch hived
  hives hoard hoars hoary hobby hobos hocks hocus hoers hoick hoist hoked hokes hokey hokku hokum
  holds holed holes holey holly homed homes homos honed honer hones honey honks honky honor hoods
  hooey hoofs hooks hooky hoops hoots hoped hopes horah horal horas horde horme horns horol horse
  horst hosed hoses hosta hosts hotel hotly hough hound houri hours house hovel hover howls hubby
  huffs huffy huger hulas hulks hulky hulls human humic humid humor humph humps humpy humus hunch
  hunks hunky hunts hurds hurls hurry hurst hurts husks husky hussy hutch hydra hydro hyena hying
  hymen hymns hyoid hyped hyper hypes hypha hypos hyrax hyson iambi iambs ichor icier icily icing
  icons ictus ideal ideas idiom idled idler idles idols idyll igloo ihram ileac ileal ileum ileus
  iliac ilium illus image imago imams imbue imide imine immix impel imper imply inane inapt inbox
  inced incur incus indef index indic indie induc inept inert infer infin infix infra ingle ingot
  inion inked inkle inlay inlet inner inorg input inset instr intel inter intis intro inure inurn
  ioctl iodic ionic iotas irade irate irked irons irony irreg isles islet issei issue istle itchy
  items ivied ivies ivory ixtle izard jabot jacal jacks jaded jades jaggy jails jakes jalap jambs
  jammy japan japed japer japes jatos jaunt jawed jazzy jeans jebel jeeps jeers jello jells jelly
  jemmy jerid jerks jerky jests jetty jewel jibed jibes jiffs jiffy jilts jingo jinks jinni jived
  jiver jives jivey jocko jocks joeys johns joins joint joist joked joker jokes jokey jolly jolts
  jolty jorum joule joust jowls jowly joyed judge jugal jugum juice juicy jujus julep jumbo jumps
  jumpy junco junks junta jupon jural jurat jurel juror jutty kafir kaiak kails kakis kalif kalis
  kalpa kanji kanzu kaons kaphs kapok kappa kaput karat karma karst karts kasha kauri kavas kayak
  kayos kazoo kebab kedge keels keens keeps kenaf kendo kente kepis kerbs kerne ketch kevel keyed
  khaki khans kheda khoum kiang kibes kicks kicky kikes kills kilns kilos kilts kinas kinds kines
  kings kinin kinks kinos kiosk kited kites kitty kiwis klong kloof kluge klutz knack knaps knave
  knead kneed kneel knees knell knelt knife knish knits knobs knock knoll knots knout known knows
  knurl koala koans kobos kohls koine kolas kooks kooky kopje korma koses kotos kraal krait krill
  krona krone kroon kudos kudus kudzu kukri kulak kurus kvass kyats kyles kylix label labia labor
  laced lacer laces lacks laded laden lades ladle lagan lairs laity laker lakes lamas lambs lamed
  lamer lames lamia lamps lanai lance lands lanes lanky lapel lapin lapse larch lards lardy lares
  large largo larks larum larva lased laser lases lasso lasts latch lated later latex lathe lathi
  laths lathy latke latte lauds laugh lavas laved laver laves lawns laxer laxly layer layup lazar
  lazed lazes leach leads leafs leafy leaks leaky leans leaps leapt learn lease leash least leave
  ledge leech leeks leers leery lefts legal leges leggy leman lemma lemon lemur lends lenis lento
  lepta lethe letup levee level lever levin lexer lexis liana liard liars libel liber libra licit
  licks lidos liens lifer lifts ligan liger light liked liken liker likes lilac lilos lilts limbo
  limbs limed limen limes limey limit limns limos limps lindy lined linen liner lines lingo lings
  linin links lints linty lions lipid lippy lisle lisps lists litas liter lithe litho litre lived
  liven liver lives livid livre llama llano loach loads loafs loams loamy loans loath lobar lobby
  lobed lobes local locks locos locum locus loden lodes lodge loess lofts lofty loges loggy logia
  logic login logon logos loins lolls lolly loner longe longs looby looks looms loons loony loops
  loopy loose loots loped loper lopes loppy loran lords loris lorry losel loser loses lotas lotic
  lotus lough loupe lours louse lousy louts loved lover loves lovey lowed lower lowly loyal luaus
  lubed lubes lubra lucid lucks lucky lucre ludic luffa luffs luged luges lulls lulus lumen lumps
  lumpy lunar lunch lunge lungi lungs lupus lurch lured lures lurex lurgy lurid lurks lushy lusts
  lusty lutes luxes lweis lxvii lying lymph lyres lyric lyses lysin lysis lyssa lytic lytta macaw
  maced maces macho macle macro madam madly mages magic magma magus maids mails maims mains maize
  major maker makes makos malar males malls malts malty mamas mamba mamey manas manat maned manes
  manga mange mango mangy mania manic manky manly manna manor manse manta manuf maple maras march
  marcs mares marka marks marls marly marry marsh marts maser masks mason massy masts match mated
  mater mates matey matin matte matzo mauls maund mauve maven maxed maxes maxim maxis maybe mayor
  mayst mazer mazes meals mealy means meant meany meats meaty medal media medic meets meiny melds
  melee melic melon melts memes memos mends menus meows mercy meres merge merit merry mesas mesic
  mesne meson messy metal meted meter metes meths metic metis metre metro mewed mewls mezzo micks
  micro middy midge midis midst miens miffs miffy might miked mikes mikva milch miler miles milfs
  milia milit milks milky mills milos milts mimed mimer mimes mimic mince minds mined miner mines
  mingy minim minis minke minks minor mints minty minus mired mires mirin mirth mirza misdo miser
  mists misty miter mites mitis mitts mixed mixer mixes mneme moans moats mocha mocks modal model
  modem modes moggy mogul mohur moils moire moist mokes molal molar molas molds moldy moles molls
  molts monad monas monde money mongo monks month mooch moods moody mooed moons moony moors moose
  moots moped moper mopes mopey moral morel mores morns morph mosey mossy motel motes motet moths
  mothy motif motor motte motto moues mould mound mount mourn mouse mousy mouth moved mover moves
  movie mowed mower moxie mucin mucks mucky mucor mucro mucus muddy mudra muffs mufti muggy mujik
  mulch mulct mules muley mulla mulls multi mummy mumps munch mungs muons mural murex murks murky
  murre mused muser muses mushy music musky mussy musth musts musty muted muter mutes mutts muzak
  muzzy myall mycol mynas myrrh myths naans nabob nacho nacre nadir naevi naiad naifs nails naira
  naive naker nakfa named namer names nanny napes nappe nappy narcs nards nares naris narky nasal
  nasty natal natch nates natty naval navar navel naves navig navvy nawab neaps nears neath necks
  needs needy negus neigh neper neral nerds nerdy nerve nervy nests netty neume never nevus newel
  newer newly newsy newts nexus ngwee nicer niche nicks nidus niece niffy nifty night nihil nimbi
  nimby nines ninja ninny ninon ninth nipas nippy nisei nisus niter nitid nitro nitty nival nixed
  nixes nobby noble nobly nocks nodal noddy nodes nodus noels nohow noise noisy nomad nomen nonce
  nones nonet nooks nooky noons noria norms north nosed noses notch noted notes notum nouns novae
  novas novel noway nubby nuder nudes nudge nuked nukes nulls numbs numen numis nurse nutty nyala
  nylon nymph oaken oakum oared oases oasis oasts oaten oaths obeah obeli obese obeys obits objet
  oboes oboli occas occur ocean ocher ochre ocker ocrea octad octal octan octet oculi odder oddly
  odeon odeum odium odors odour offal offed offer often ogeed ogham ogive ogled ogler ogles ogres
  ohmic oiled oiler oinks okapi okays okras olden older oldie oleic olein oleum olive ollas ology
  omasa omber omega omens omits onion onset ontic oohed oomph ootid oozed oozes opahs opals opens
  opera opine oping opted optic orals orang orate orbit orcas order oread organ oriel orlop ornis
  orris osier osmic other ottar otter ought ounce ouphe ousel ousts outdo outed outer outgo outre
  ouzel ouzos ovals ovary ovate ovens overs overt ovine ovoid ovolo ovule owing owlet owned owner
  oxbow oxide oxime ozone paced pacer paces pacha packs pacts paean paeon paged pages pails pains
  paint pairs paisa paled paleo paler pales palls pally palms palmy palsy pampa panda paned panel
  panes panga pangs panic panne pansy panto pants papal papas paper paras parch pared parer pares
  pareu parka parks parky parol parrs parry parse parts party parve pashm passe pasta paste pasts
  pasty patch paten pates paths patin patio patly pause pavan paved paves pavid pavis pawed pawls
  pawns paxes payed payee payer peace peach peags peaks peaky peals peans pearl pears peart peaty
  pebas pecan pecks pedal peeks peels peens peeps peers peeve pekan pekes pekoe pelts pence pends
  penna penne penni penny peons peony peppy perch perdu peril peris perks perky perms perse pervs
  pesky pesos pesto pests pesty petal petty pewee pewit phage phase pheon phial phish phlox phone
  phons phony photo phots phren phyla phyle piano picks picky picot picul piece piers pieta piety
  piggy piing pikas piked piker pikes pilaf pilch piled pilei piles pills pilot pimps pinch pined
  pines piney pings pinko pinks pinna pinny pinon pinta pints pinup pions pious piped pipes pipit
  pique pirog piste pitas pitch piths pithy piton pitta pivot pixel pixie pizza place plage plaid
  plain plait plane plank plans plant plash plasm plate plats platy playa plays plaza plead pleas
  pleat plebe plebs plena plica plied plier plies ploce plods plonk plops plots plows ploys pluck
  plugs plumb plume plump plums plumy plunk plush poach pocks pocky poddy poems poesy poets pogey
  pogge poilu point poise poked poker pokes pokey polar poled poler poles polio polis polit polka
  polls polyp polys pomes pommy ponce poncy ponds pones pongs pooch poods pooed poofs poohs pooka
  pools poons poops popes poppa poppy popup porch pored porer pores porgy ports posed poser poses
  posit posse posts potto potty pouch poufs poult pound pours pouts pouty power poxes prams prana
  prang prank prase prate prats prawn prays preen preps presa press prexy preys price pride pried
  prier pries prigs prime primp prink print prion prior prism privy prize probe prods proem profs
  prole promo proms prone prong proof propr props prose prosy proud prove prowl prows proxy prude
  prune psalm pseud pshaw psoas pubes pubis pucka pucks pudgy puffs puffy puked pukes pukka pulas
  puled puler pules pulls pulps pulpy pulse pumas pumps punch pungs pungy punks punts pupae pupal
  pupil puppy puree purer purge purls purrs purse pursy pushy putto putts putty pwned pygmy pylon
  pyoid pyres pyxes pyxie pzazz qibla qophs quack quads quaff quail quake quaky quale qualm quant
  quark quart quash quasi quass quays quean queen quell quern query quest queue quick quids quiet
  quiff quill quilt quine quins quint quips quipu quire quirk quirt quite quits quoin quoit quota
  quote quoth rabbi rabid raced racer races racks racon radar radii radio radix radon rafts ragas
  raged rages ragga ragis raids rails rains rainy raise rajah rajes raked raker rakes rales rally
  ramen ramie ramps rance ranch ranee range rangy ranks rants raped raper rapes rapid rared rarer
  rares rasps raspy ratal ratan rated ratel rater rates rathe ratio ratty raved ravel raven raver
  raves ravin rawer rayon razed razee razes razor reach react reads ready realm reals reams reaps
  rearm rears reata reave rebec rebel rebid rebus rebut recap recce recon recti recto recur recut
  redan redid redly redux redye reeds reedy reefs reeks reeky reels reest reeve refer refit refix
  refry regal regex reify reign reins reive rejig relax relay relic remap remex remit remix renal
  rends renew renin rents reorg repay repel reply repps repro reran rerun resat reset resew resin
  resit resow rests retch retie retro retry reuse revel revet revue rewed rheas rheum rhino rhomb
  rhumb rhyme rials riant riata riced ricer rices ricks rider rides ridge ridgy riels rifer riffs
  rifle rifts right rigid rigor riled riles rille rills rimed rimes rinds rings rinks rinse riots
  ripen riper risen riser rises rishi risks risky rites ritzy rival rived riven river rives rivet
  riyal roads roams roans roars roast robed robes robin roble robot rocks rodeo rogue roils roily
  roles rolls roman romps ronde rondo roods roofs rooks rooky rooms roomy roose roost roots roped
  ropes roque roses rosin rotas rotls rotor roues rouge rough round rouse roust route routs roved
  rover roves rowdy rowed rowel rower royal rubel rubes ruble ruche rucks rudds ruddy ruder ruffs
  rugby ruing ruins ruled ruler rules rumal rumba rumen rummy rumor rumps runes rungs runic runny
  runts runty rupee rural ruses rushy rusks rusts rusty ruths rutty saber sabin sable sabot sabra
  sabre sacks sacra sades sadhu sadly safer safes sagas sager sages saggy saiga sails saint saith
  saker sakes salad salep sales salmi salol salon salpa salsa salts salty salve salvo samba sambo
  sames samey sands saner sapid sapor sappy saran sards saris sarky saros sasin sassy satay sated
  satem sates satin satyr sauce saucy sauna saury saute saved saver saves savor savvy sawed sawer
  saxes sayer scabs scads scags scald scale scalp scaly scamp scams scans scant scape scare scarf
  scarp scars scary scats scend scene scent schmo schwa scion scoff scold scone scoop scoot scope
  score scorn scour scout scowl scows scrag scram scrap scree scrim scrip scrod scrog scrub scrum
  scuba scudo scuds scuff scull sculp scums scups scurf scuta scute scuts seals seams seamy sears
  seats sebum secco sects sedan sedge sedgy sedum seeds seedy seeks seels seems seeps seers segno
  segue seise seism seize selah sells semis sends senna sense sente sepal sepia sepoy septa septs
  serai serer serfs serif serin serow serum serve servo setae setts setup seven sever sewan sewed
  sewer sexed sexes sexts shack shade shads shady shaft shags shahs shake shako shaky shale shall
  shame shams shank shape shard share shark sharp shave shawl shawm shays sheaf shear sheds sheen
  sheep sheer sheet shelf shell shend shewn shews shied shier shies shift shill shims shine shins
  shiny ships shire shirk shirr shirt shits shive shivs shoal shoat shock shoes shone shook shool
  shoos shoot shops shore short shote shots shout shove shown shows showy shred shrew shrub shrug
  shuck shuns shunt shush shuts shyer shyly sibyl sicko sicks sided sides sidle siege sieve sifts
  sighs sight sigil sigma signs sikas silds silks silky sills silly silos silts silty simar simba
  since sines sinew singe sings sinks sinus sired siren sires sisal sises sitar sited sites situs
  sixes sixth sixty sizar sized sizer sizes skald skate skean skeet skegs skein skelp skeps skews
  skids skied skier skies skiff skill skimp skims skink skins skint skips skirl skirr skirt skite
  skits skive skoal skosh skuas skulk skull skunk slabs slack slags slain slake slams slang slant
  slaps slash slate slats slaty slays sleds sleek sleep sleet slept slews slice slick slide slier
  slime slims slimy sling slink slips slits slobs sloes slogs sloop slope slops slosh sloth slots
  slows slubs slued slues sluff slugs slump slums slung slunk slurp slurs slush sluts slyly slype
  smack small smalt smarm smart smash smaze smear smell smelt smews smile smirk smite smock smogs
  smoke smoko smoky smolt smote smuts snack snafu snags snail snake snaky snaps snare snarf snark
  snarl snath sneak sneck sneer snick snide sniff snipe snips snits snobs snogs snood snook snoop
  snoot snore snort snots snout snows snowy snubs snuff snugs soaks soaps soapy soars soave sober
  socks socle sodas sofar sofas softa softy soggy soils solan solar soldo soled soles solid solon
  solos solus solve somas sonar sonde sones songs sonic sonly sooth sooty sopor soppy sorbs sorer
  sores sorgo sorry sorts sorus sough souks souls sound soups soupy sours souse south sowed sower
  space spade spahi spake spall spams spang spans spare spark spars spasm spate spats spawn spays
  speak spear speck specs speed spell spend spent speos spews spica spice spics spicy spied spiel
  spier spies spiff spike spiky spile spill spine spins spiny spire spiry spite spits spitz spivs
  splat splay split spoil spoke spoof spook spool spoon spoor spore sport spots spout sprag sprat
  spray spree sprig sprit sprog sprue spuds spued spues spume spumy spurn spurs spurt sputa squab
  squad squat squaw squib squid sruti stabs stacc stack staff stage stags stagy staid stain stair
  stake stale stalk stall stamp stand stane stang stank staph stare stark stars start stash state
  stats stave stays stdio stead steak steal steam steed steel steep steer stela stele stems steno
  stent steps stere stern stets stews stich stick sties stiff stile still stilt sting stink stint
  stipe stirk stirs stoat stock stoic stoke stole stoma stomp stone stony stood stook stool stoop
  stope stops store stork storm story stoss stoup stout stove stows strap straw stray strep strew
  stria strip strop strow stroy strum strut stubs stuck studs study stuff stull stump stung stunk
  stuns stunt stupa stupe style styli suave sucks sucre sudor sudsy suede suety sugar suing suint
  suite suits sulci sulfa sulks sulky sumac summa sumps sunny sunup super suppl supra surah sural
  suras surds surer surfs surge surgy surly surra sushi sutra swabs swage swags swale swamp swank
  swans swaps sward swarm swart swash swath swats sways swear sweat swede sweep sweet swell swept
  swift swigs swill swims swine swing swink swipe swirl swish swizz swoon swoop sword swore sworn
  swots swung sycee sylph syncs synod synop synth syrup sysop tabby tabes tabla table taboo tabor
  tacet tache tacit tacks tacky tacos taffy tafia taiga tails taint takas taken taker takes talas
  taler tales talks talky tally talon taluk talus tamed tamer tames tamis tamps tango tangs tangy
  tanka tanks tansy tanto tapas taped taper tapes tapir tapis tardy tared tares targe tarns taros
  tarot tarps tarry tarsi tarts tarty tasks tasse taste tasty tater tatty taunt taupe tawny taxed
  taxer taxes taxis taxon tayra tazza teach teaks teals teams tears teary tease teats techs techy
  teddy teems teens teeny teeth teleg telex telic tells telly tempo temps tempt tench tends tenet
  tenge tenia tenne tenno tenon tenor tense tenth tents tepee tepid terce terms terns terse testa
  tests testy teths tetra texts thane thank thaws thebe theca thees theft thegn their theme theol
  there therm these theta thews thewy thick thief thigh thill thing think thins thiol third thole
  thorn thorp those thous three threw throb throe throw thrum thuds thugs thuja thumb thump thuya
  thyme tiara tibia tical ticks tidal tided tides tiers tiffs tiger tight tigon tilde tiled tiler
  tiles tills tilth tilts timed timer times timid tinct tinea tined tines tinge tings tinny tints
  tipsy tired tires titan titch titer tithe titis title tizzy toads toady toast today toddy toeas
  toffs togas toile toils tokay toked token tokes tolan tolar tolls tolly tolus tolyl tombs tomes
  tonal toned toner tones tonga tongs tonic tonne tonus tools tooth toots topaz toped topee toper
  topes topic topog toque torch torii torrs torse torsk torso torte torts torus total toted totem
  toter totes touch tough tours touts towed towel tower towns toxic toxin toyed trace track tract
  trade trail train trait trams traps trash trass trave trawl trays tread treas treat treed treen
  trees treks trend tress trews treys triad trial tribe trice trick tried trier tries trike trill
  trims trine trios tripe trips trite troat troll tromp trona trons troop trope troth trots trout
  trove trows troys truce truck trued truer trues trugs trull truly trunk truss trust truth tryma
  tryst tubal tubas tubby tubed tuber tubes tucks tufts tufty tulip tulle tumid tummy tunas tuned
  tuner tunes tunic tunny tuple tuque turbo turds turfs turfy turns turps tushy tusks tutor tutti
  tutty tutus tuxes twang twats tweak tweed tween tweet twerk twerp twice twigs twill twine twink
  twins twirl twist twits twixt tying tykes typal typed types typos tyres tyros udder uhlan ukase
  ulcer ulema ulnae ulnar ultra umbel umber umbra umiak umped unapt unarm unary unbar unbid unbox
  uncap uncle uncut under undid undue unfed unfit unfix unify union unite units unity unjam unlay
  unlit unman unmet unpeg unpen unpin unrig unsay unset unsex untie until unwed unwon unzip upend
  upped upper upset urban uredo urged urger urges urial usage users usher using usual usurp usury
  uteri utile utter uveas uvula vagal vague vagus vales valet valid valor valse value valve vamps
  vampy vanda vanes vaped vapes vapid vapor varas varia varix varus varve vases vasts vasty vatic
  vault vaunt vedic veeps veers veery vegan veges veils veins veiny velar velds velum venae venal
  vends venge venin venom vents venue verbs verge versa verse verso verst vertu verve vesta vests
  vetch veter vexed vexes vials viand vibes vicar viced vices video views viewy vigil vigor viler
  villa villi vimen vines vinic vinyl viola viols viper viral vireo virga virtu virus visas vised
  vises visit visor vista vitae vital vitta vivas vivid vixen vocab vocal vogue voice voids voile
  volar voles volts volva vomer vomit voted voter votes vouch vouge vowed vowel vower vulva vying
  wacke wacks wacky waded wader wades wadge wadis wafer wafts waged wager wages wagon wahoo waifs
  wails wains waist waits waive waked waken wakes waled wales walks walls waltz wands waned wanes
  wanks wanly wants wards wares warez warms warns warps warts warty washy wasps waste watch water
  watts waved waver waves waxed waxen waxes wazoo weald weals weans wears weary weave webby weber
  wedge weeds weedy weeks weens weeny weeps weepy weest wefts weigh weird weirs wekas welds wells
  welly welsh welts wends wersh wetly whack whale whams whaps wharf whats wheal wheat wheel wheen
  whelk whelm whelp whens where whets which whiff while whims whine whins whiny whips whipt whirl
  whirs whish whisk whist white whits whity whole whomp whoop whops whorl whose whoso whsle whups
  wicks widen wider wides widow width wield wight wikis wilds wiled wiles wills wilts wimps wimpy
  wince winch winds windy wined wines wings winks winos winze wiped wiper wipes wired wirer wires
  wirra wised wiser wises wisps wispy witch withe withy witty wived wives wizen woald wodge woken
  wolds wolfs woman wombs wonks wonky woods woody wooed wooer woofs wools woops woozy words wordy
  works world worms wormy worry worse worst worth would wound woven wowed wrack wraps wrath wreak
  wreck wrens wrest wring wrist write writs wrong wrote wroth wrung wryer wryly wurst wussy xcvii
  xebec xenia xenon xeric xerox xrefs xterm xviii xxiii xxvii xxxii xxxiv xxxix xxxvi xylem xylol
  yacht yakka yamen yanks yapok yapon yappy yards yarns yawed yawls yawns yawps yeahs yeans yearn
  years yeast yeggs yells yelps yenta yeses yetis yield yobbo yodel yodle yogic yogis yoked yokel
  yokes yolks yonks young yours youth yowls yucca yucky yukky yulan yummy yurts zaire zamia zappy
  zarfs zayin zazen zebec zebra zebus zeros zests zesty zetas zibet zilch zincs zines zings zingy
  zippy zitis zloty zonal zoned zones zooid zooms zorch zoril
`
  .trim()
  .split(/\s+/);
