// Categories — the cards' prompts, one per line of a card.
//
// Curated by hand for a family table: every one is something a child could
// answer and nothing needs an adult's knowledge or an adult's mind. Each reads
// as the start of an answer ("An animal" → "Badger"), sentence case, no full
// stop. Distinct by design: the dealer takes a card's worth at random, so two
// near-twins would land on one card sooner or later.

export const CATEGORIES: readonly string[] = [
  // Living things
  "An animal",
  "A bird",
  "A fish or sea creature",
  "An insect or bug",
  "A pet",
  "A farm animal",
  "A zoo animal",
  "A dog breed",
  "A dinosaur",
  "A flower",
  "A tree",
  "A plant",
  "Something with wings",
  "Something with four legs",
  "Something that lives in water",
  "Something with a shell",
  // Food and drink
  "A food",
  "A fruit",
  "A vegetable",
  "A drink",
  "A dessert",
  "A breakfast food",
  "A sandwich filling",
  "A pizza topping",
  "A snack",
  "A sweet or chocolate",
  "A flavour of ice cream",
  "Something you bake",
  "Something on a picnic",
  "Something in a lunchbox",
  "A cheese",
  "A kind of bread or cake",
  "A food from another country",
  "A soup",
  "Something sour",
  "Something spicy",
  "Something sweet",
  // People and names
  "A girl's name",
  "A boy's name",
  "A name for a pet",
  "A famous person",
  "A cartoon character",
  "A superhero",
  "A villain",
  "A character from a book",
  "A job",
  "Someone who wears a uniform",
  "A family member",
  "A king or queen",
  "A footballer",
  "A singer or band",
  "A fairy-tale character",
  // Places
  "A country",
  "A city",
  "A capital city",
  "A place in the UK",
  "A river",
  "A mountain or mountain range",
  "An island",
  "A place in a town",
  "A shop",
  "A holiday destination",
  "Somewhere you go on a school trip",
  "A room in a house",
  "Something at the beach",
  "Something at the park",
  "Something at a zoo",
  "Something at a funfair",
  "Something in a supermarket",
  "Something in space",
  "Something at a wedding",
  // Things around us
  "Something in a kitchen",
  "Something in a bathroom",
  "Something in a bedroom",
  "Something in a classroom",
  "Something in a garden",
  "Something in a toolbox",
  "Something in a pencil case",
  "Something in a school bag",
  "Something in your pocket",
  "Something in a fridge",
  "Something in a car",
  "Something on a farm",
  "Something in a hospital",
  "Something in a castle",
  "Something in the sky",
  "Something in the sea",
  "Something in a forest",
  "Furniture",
  "A kitchen gadget",
  "A tool",
  "A toy",
  "A board game or card game",
  "A video game",
  "A musical instrument",
  "A vehicle",
  "Something with wheels",
  "Something with buttons",
  "Something with a screen",
  "Something that needs batteries",
  "Something made of wood",
  "Something made of metal",
  "Something made of glass",
  "Something made of paper",
  "Something you plug in",
  // Describing things
  "Something cold",
  "Something hot",
  "Something round",
  "Something square",
  "Something soft",
  "Something hard",
  "Something sticky",
  "Something smelly",
  "Something loud",
  "Something quiet",
  "Something tiny",
  "Something huge",
  "Something heavy",
  "Something light",
  "Something fast",
  "Something slow",
  "Something red",
  "Something green",
  "Something blue",
  "Something yellow",
  "Something white",
  "Something shiny",
  "Something that bounces",
  "Something that grows",
  "Something that floats",
  "Something that melts",
  "Something that breaks",
  "Something you can fold",
  "Something that makes you laugh",
  "Something scary",
  "Something that comes in pairs",
  "Something with a tail",
  "Something with stripes",
  "Something with spots",
  // Doing things
  "A sport",
  "A game played outside",
  "A hobby",
  "A dance",
  "A way to travel",
  "Something you do at school",
  "Something you do at the weekend",
  "Something you do in the morning",
  "Something you do on holiday",
  "Something you can throw",
  "Something you can catch",
  "Something you can climb",
  "Something you wear",
  "Something you wear on your feet",
  "Something you wear on your head",
  "Something you wear in winter",
  "Something you take on holiday",
  "Something you collect",
  "Something you give as a present",
  "A reason to be late",
  "An excuse for not doing homework",
  "A word you say when you're happy",
  // Words and ideas
  "A colour",
  "A shape",
  "A number word",
  "A month or day of the week",
  "A school subject",
  "A language",
  "A word with double letters",
  "A word ending in -ing",
  "A thing you shout",
  "A kind of weather",
  "A season or holiday",
  "Something at a birthday party",
  "Something at Christmas",
  "Something at Halloween",
  "A film",
  "A TV show",
  "A song",
  "A book",
  "A website or app",
  "A brand",
  "A car maker",
  "Something in a library",
  "A body part",
  "An emotion",
  "Something in a museum",
  "A magic word or spell",
];
