import { GOVERNANCE } from '../schemas';
import type { Draft } from './store';

/** Render source text as quoted data, never Markdown directives or HTML. */
const safe = (s: string) => s.replace(/[<>&`*_[\]#]/g, c => `&#${c.charCodeAt(0)};`).replace(/\n/g, '\n> ');
export function reportMarkdown(title: string, snapshot: Draft, run: unknown): string {
  const source = snapshot.source!; const candidate = snapshot.candidate!;
  return `# Policy Incentives Lab — ${safe(title)}\n\n${GOVERNANCE}\n\n${source.synthetic ? '**SYNTHETIC EXAMPLE — no real policy or organisation.**' : 'User-declared public source.'}\n\n## Source metadata\n\nTitle: ${safe(source.title)}\n\nPublisher: ${safe(source.publisher)}\n\nPublication date: ${source.publication_date ?? 'Unknown'}\n\nURL (metadata only; not fetched): ${safe(source.source_url || 'Not supplied')}\n\nSHA-256: ${source.document_hash}\n\n## Source evidence\n\n${candidate.evidence.map(e => `### ${e.id}\n\n${safe(e.location)} · ${e.explicit_or_inferred} · confidence: ${e.confidence}\n\n> ${safe(e.quotation)}\n`).join('\n')}\n## Assumptions\n\n${candidate.game.assumptions.map(a => `- ${a.id}: ${safe(a.statement)} — ${JSON.stringify(a.value_or_range)}; ${safe(a.source)}; ${a.confidence}; ${a.approval_status.status}`).join('\n')}\n\n## Approved model and item approvals\n\n\`\`\`json\n${JSON.stringify(candidate.game, null, 2).replaceAll('`', '\\u0060')}\n\`\`\`\n\n## Deterministic calculations and run configuration\n\n\`\`\`json\n${JSON.stringify(run, null, 2).replaceAll('`', '\\u0060')}\n\`\`\`\n\n## Hypotheses — not findings\n\n${snapshot.hypotheses.map(h => `- ${safe(h.statement)} References: ${[...h.evidence_refs, ...h.assumption_refs].join(', ')}. Limitation: ${safe(h.limitation)}`).join('\n') || 'No red-team hypotheses recorded.'}\n\n## Recommendations for review\n\nCompare intended outcomes against the calculated outcome ranges. Consider auditing reward rules, monitoring cost shifting and testing safeguards as separately approved scenarios. These are review prompts, not established policy recommendations.\n\n## Fiscal, distributional and operational limitations\n\nEffects outside explicitly approved outcome metrics are unknown. No legal, financial or operational assurance is implied.\n\n${candidate.game.model_limitations.map(s => `- ${safe(s)}`).join('\n')}\n\n## Extraction audit\n\n${snapshot.attempts.map(a => `- ${a.task}; ${a.prompt_version}; ${a.model}; ${a.timestamp}; ${a.error ? 'validation failed' : 'validated'}`).join('\n')}\n\nRaw responses, original source sections and complete audit history are included in the JSON export.\n`;
}
