/** Routes in the Main grant catalogue now served by SR-Jkai-Core. */
export const EXTRACTED_ROUTE_IDS = [
  '/jkai',
  '/jkai/intel',
  '/jkai/intel/entities',
  '/jkai/intel/entities/[id]',
  '/jkai/intel/mail',
  '/jkai/intel/notes',
  '/jkai/intel/notes/[id]',
  '/jkai/intel/search',
  '/jkai/intel/timeline',
  '/api/jkai/attachments',
  '/api/jkai/attachments/[id]',
  '/api/jkai/conversations',
  '/api/jkai/conversations/[id]',
  '/api/jkai/conversations/[id]/messages',
  '/api/jkai/events',
  '/api/jkai/intel/entities',
  '/api/jkai/intel/entities/[id]',
  '/api/jkai/intel/entity-card',
  '/api/jkai/intel/evidence-network',
  '/api/jkai/intel/mail',
  '/api/jkai/intel/network',
  '/api/jkai/intel/network/paths',
  '/api/jkai/intel/notes',
  '/api/jkai/intel/notes/[id]',
  '/api/jkai/knowledge/search',
  '/api/workflows/orchestrator/chat',
  '/api/workflows/orchestrator/chat/active',
  '/api/workflows/orchestrator/chat/presence',
  '/api/workflows/orchestrator/chat/stream',
] as const;
