// sources.ts — the flat citation list rendered in the layout footer. Every factual
// claim in the lib content traces to one of these.
export interface Source { org: string; what: string; url: string }

export const SOURCES: Source[] = [
  { org: 'DfE', what: '“Every Child Achieving and Thriving” White Paper (CP 1508-I) — the verbatim data-spine commitment, p.98', url: 'https://assets.publishing.service.gov.uk/media/69972c02bfdab2546272c007/Every_child_achieving_and_thriving_print_ready_version.pdf' },
  { org: 'DfE', what: 'White paper HTML version — digital commitments (spine, School Profiles, digital ISPs)', url: 'https://www.gov.uk/government/publications/every-child-achieving-and-thriving/every-child-achieving-and-thriving-html-version' },
  { org: 'GOV.UK', what: 'Bett 2026 Education Secretary speech — “a new data spine and open data standards”', url: 'https://www.gov.uk/government/speeches/education-secretary-speech-at-the-bett-show-2026' },
  { org: 'Schools Week', what: 'White paper key policies — data spine coverage', url: 'https://schoolsweek.co.uk/schools-white-paper-the-key-schools-policies/' },
  { org: 'Browne Jacobson', what: 'White paper legal analysis — spine “the most far-reaching proposal”', url: 'https://www.brownejacobson.com/insights/every-child-achieving-and-thriving-schools-white-paper-explained' },
  { org: 'techUK', what: 'What the white paper signals for edtech — fragmentation and standards warnings', url: 'https://www.techuk.org/resource/what-the-schools-white-paper-signals-for-technology-in-education.html' },
  { org: 'defenddigitalme', what: 'White paper response — data drivers, spine critique', url: 'https://defenddigitalme.org/2026/02/26/every-child-achieving-and-thriving-data-drivers-and-our-response/' },
  { org: 'defenddigitalme', what: 'NPD distribution 2026 review — 2,385+ distributions since 2012, and proposed fixes', url: 'https://defenddigitalme.org/2026/04/15/national-pupil-data-distribution-a-2026-review-and-how-to-fix-it/' },
  { org: 'defenddigitalme', what: 'State of Data 2020 — census scope (~400 items/child/year), parental awareness', url: 'https://defenddigitalme.org/research/the-state-of-data-2020/' },
  { org: 'defenddigitalme', what: 'CWSA SUI analysis — NHS number, s.16LA–LD mechanics, confidence-clause critique', url: 'https://defenddigitalme.org/2025/06/14/nhs-number-to-be-national-id-mandated-in-childrens-wellbeing-and-schools-bill/' },
  { org: 'defenddigitalme', what: 'Nationality school-census collection and the Home Office MoU', url: 'https://defenddigitalme.org/2016/12/15/children-school-census-nationality/' },
  { org: 'defenddigitalme', what: 'LRS/Trustopia breach chronology', url: 'https://defenddigitalme.org/the-learner-records-service-data-breach-and-ico-audit-a-connected-chronology/' },
  { org: 'defenddigitalme', what: 'Statutory code of practice on children’s data — campaign status', url: 'https://defenddigitalme.org/2025/03/03/a-code-of-practice-on-childrens-data-and-education-whats-next/' },
  { org: 'Schools Week', what: 'ICO audit of the DfE — 139 recommendations, breaches found (2020)', url: 'https://schoolsweek.co.uk/dfe-broke-pupil-data-protection-laws-damning-ico-audit-reveals/' },
  { org: 'GOV.UK', what: 'DfE ICO audit closure summary', url: 'https://www.gov.uk/government/publications/department-for-education-dfe-data-protection-ico-audit-closure-summary' },
  { org: 'Commons Library', what: 'ContactPoint briefing (SN/SP/5171) — cost, scope, switch-off', url: 'https://researchbriefings.files.parliament.uk/documents/SN05171/SN05171.pdf' },
  { org: 'NHS Digital', what: 'NHS Spine — 44,000+ systems, 26,000 organisations; PDS; national applications', url: 'https://digital.nhs.uk/services/spine' },
  { org: 'NHS Digital', what: 'National Record Locator — pointers, not records (FHIR API)', url: 'https://digital.nhs.uk/developer/api-catalogue/national-record-locator-fhir/v2.8.0' },
  { org: 'NHS Digital', what: 'CP-IS — child-protection information sharing keyed on NHS number', url: 'https://digital.nhs.uk/services/child-protection-information-sharing-service/support-for-technical-or-data-issues/cp-is-nhs-number-matching-information' },
  { org: 'e-Estonia', what: 'X-Road — federated exchange, once-only, citizen-visible access logs', url: 'https://e-estonia.com/solutions/interoperability-services/x-road/' },
  { org: 'Computer Weekly', what: 'GOV.UK Verify — PAC findings: “failed its users”, 48% success, 27 services', url: 'https://www.computerweekly.com/news/252462967/Govuk-Verify-has-failed-users-and-its-leaders-lack-accountability-say-MPs' },
  { org: 'NCRR (Aarhus)', what: 'Danish CPR — universal civil registration since 1968, register linkage', url: 'https://ncrr.au.dk/danish-registers/the-danish-civil-registration-system-cpr' },
  { org: 'Government of NL', what: 'BSN — citizen service number, used as the education number', url: 'https://www.government.nl/topics/personal-data/citizen-service-number-bsn' },
  { org: 'NZ Ministry of Education', what: 'National Student Number — lifetime learner identifier from first enrolment', url: 'https://www.education.govt.nz/our-work/about-us/education-new-zealand/about-national-student-numbers' },
  { org: 'Bond University', what: 'Australia’s USI — lifetime unique student identifier', url: 'https://bond.edu.au/current-students/study-information/enrolment/unique-student-identifier-usi' },
  { org: 'GOV.UK', what: 'Share your daily school attendance data — the live feed, mandatory 2024/25', url: 'https://www.gov.uk/guidance/share-your-daily-school-attendance-data' },
  { org: 'DfE', what: 'Principles for daily data collection and DfE use', url: 'https://assets.publishing.service.gov.uk/media/6511356b2f404b0014c3d820/Requesting_daily_data_from_state-funded_schools_principles_for_collection_and_DfE_use__1_.pdf' },
  { org: 'OSR', what: 'Code of Practice case study — rapidly standing up automated attendance collection', url: 'https://code.statisticsauthority.gov.uk/case-studies/rapidly-setting-up-an-automated-data-collection/' },
  { org: 'GOV.UK', what: 'Attendance “similar schools” reports — algorithmic transparency record', url: 'https://www.gov.uk/algorithmic-transparency-records/dfe-attendance-reports-using-similar-schools' },
  { org: 'GOV.UK', what: 'Education Record app — national rollout, £30m/yr claimed saving', url: 'https://www.gov.uk/government/news/government-modernises-exam-records-with-new-app' },
  { org: 'Commons Library', what: 'Free School Meals (Automatic Registration) Bill briefing (CBP-10206)', url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-10206/' },
  { org: 'EPI', what: 'Unregistered FSM-eligible pupils — scale of missed entitlement', url: 'https://epi.org.uk/wp-content/uploads/2025/03/FSM-report-March-2025_PDF.pdf' },
  { org: 'Devon County Council', what: 'FSM opt-out auto-award pilot — 1,000+ eligible unregistered pupils found', url: 'https://www.devon.gov.uk/children-families-education/education/school-meals/free-school-meals-opt-out-auto-award/' },
  { org: 'RCPCH', what: 'NHS number as single unique identifier — position statement (pro, with safeguards)', url: 'https://www.rcpch.ac.uk/resources/nhs-number-single-unique-identifier-children-position-statement' },
  { org: 'GOV.UK', what: 'MacAlister Independent Review of Children’s Social Care — SUI recommendation', url: 'https://www.gov.uk/government/publications/independent-review-of-childrens-social-care-final-report' },
  { org: 'CYP Now', what: 'Children’s Wellbeing and Schools Act 2026 — Royal Assent coverage', url: 'https://www.cypnow.co.uk/content/news/childrens-wellbeing-and-schools-act-becomes-law' },
  { org: 'Children’s Commissioner', what: '“Connecting the dots” — the case for a unique child identifier', url: 'https://www.childrenscommissioner.gov.uk/blog/connecting-the-dots-the-importance-of-sharing-data-on-children-and-families/' },
  { org: 'ICO', what: 'Data (Use and Access) Act 2025 — what it means for organisations', url: 'https://ico.org.uk/about-the-ico/what-we-do/legislation-we-cover/data-use-and-access-act-2025/the-data-use-and-access-act-2025-what-does-it-mean-for-organisations/' },
  { org: 'GOV.UK', what: 'Five Safes framework — data ethics guidance', url: 'https://www.gov.uk/data-ethics-guidance/the-five-safes-framework' },
  { org: 'ONS', what: 'Secure Research Service — accredited access to DfE data', url: 'https://www.ons.gov.uk/aboutus/whatwedo/statistics/requestingstatistics/secureresearchservice' },
  { org: 'Bennett Institute', what: 'OpenSAFELY and the Five Safes — query-not-copy in practice', url: 'https://www.bennett.ox.ac.uk/blog/2023/03/the-five-safes-framework-and-applying-it-to-opensafely/' },
  { org: 'GDS', what: 'Privacy-enhancing technologies for data sharing (2025)', url: 'https://gds.blog.gov.uk/2025/10/09/using-privacy-enhancing-technologies-to-enable-international-data-sharing/' },
  { org: 'ADR UK', what: 'LEO — Longitudinal Education Outcomes flagship dataset', url: 'https://www.adruk.org/data-access/flagship-datasets/longitudinal-education-outcomes/' },
  { org: 'ADR UK', what: 'DfE Data Access and Engagement Programme', url: 'https://www.adruk.org/our-work/browse-all-projects/department-for-education-data-access-and-engagement-programme/' },
  { org: 'WhichMIS', what: 'MIS market share, autumn 2025 census — Arbor/SIMS/Bromcom', url: 'https://www.whichmis.com/mis-stats-from-the-october-census/' },
  { org: 'Groupcall', what: 'Xporter — MIS data broker in 20,000+ UK schools', url: 'https://groupcall.com/product/xporter' },
  { org: 'GOV.UK', what: 'DfE external data shares — quarterly registers', url: 'https://www.gov.uk/government/publications/dfe-external-data-shares' },
  { org: 'GOV.UK', what: 'Unique Pupil Numbers — guide', url: 'https://www.gov.uk/government/publications/unique-pupil-numbers' },
  { org: 'UCAS', what: 'Unique Learner Number — LRS, lifetime from 14+', url: 'https://www.ucas.com/article/unique-learner-number-uln' },
  { org: 'Schools Week', what: 'FFT Datalab — ~8,000 pupils “disappeared” from rolls in a year', url: 'https://schoolsweek.co.uk/fft-education-datalab-almost-8000-pupils-disappeared-from-schools-last-year/' },
  { org: 'EdTech Innovation Hub', what: 'DfE’s £200k Director General for Digital — spine + SUI in scope', url: 'https://www.edtechinnovationhub.com/news/englands-dfe-creates-200000-digital-and-ai-role-covering-data-cyber-estates-and-school-safety' },
  { org: 'Government Transformation', what: 'DfE digital strategy — 271 systems to 57 service lines', url: 'https://www.government-transformation.com/transformation/department-for-education-sets-transformative-data-technology-strategy' },
  { org: 'ASCL', what: 'Schools white paper — sector response', url: 'https://www.ascl.org.uk/News/Our-news-and-press-releases/ASCL-comment-on-schools-white-paper-(1)' },
  { org: 'LGA', what: 'FSM automatic registration — briefing', url: 'https://www.local.gov.uk/parliament/briefings-and-responses/free-school-meals-automatic-registration-eligible-children-bill' },
  { org: 'GAO', what: 'Privacy-enhancing technologies survey (SMPC, DP, federated, synthetic)', url: 'https://www.gao.gov/products/gao-26-109063' },
];
