<script lang="ts">
  import StoryMasthead from '../components/StoryMasthead.svelte';
  import FrameStream from './components/FrameStream.svelte';
  import { WATCHDOG, STREAM_CONSTANTS } from '../lib/chat';
  import { app } from '../lib/appState.svelte';

  const eli = $derived(app.narrative === 'eli5');
  let tier = $state(3);
</script>

<svelte:head>
  <title>Conversation — the assistant and its engine · The Engine Room</title>
  <meta name="description" content="How a chat turn is actually run: an external agent runtime, a translation layer, and the streaming problems that only appear once a reply arrives in pieces." />
</svelte:head>

<section class="pe-route wide">
  <StoryMasthead
    kicker="Section 2 · Conversation"
    title="The assistant, and the engine underneath it"
    thesis="The chat replies on this site are not generated by this site. A dedicated agent runtime owns the conversation, its tools and its session state; the site translates that runtime's frame stream back into the exact event vocabulary its own interface already spoke. That one decision — keep the interface, replace the engine — is what makes everything else in this section necessary, and it is where all the interesting bugs live."
    thesisEli5="The chat you see is not powered by the website itself. A separate, specialised program does the thinking, and the website acts as a translator, an accountant and a safety net between it and your screen. Almost every hard problem here comes from that translation."
    asks={[
      'What happens to an interface when you replace the engine behind it?',
      'Why does one answer arrive as several messages, and why does that matter?',
      'How do you tell "thinking hard" apart from "hung" when both look like silence?',
    ]}
  />

  <h2 class="pe-h2">Replace the engine, keep the dashboard</h2>
  <p class="pe-prose cols">
    <span>The site originally ran its own reasoning loop in-process. It had to re-implement tool orchestration,
      memory, skills, sub-agent delegation and session state — all of it work that a dedicated agent runtime already
      does properly. So the chat was cut over to one.</span>
    <span>The non-obvious part is that the cutover was made <b>invisible to the interface</b>. Rather than rewrite the
      browser client to speak the runtime's native protocol, the server translates its outbound frames into the event
      vocabulary the existing chat already consumed. Fourteen frame kinds in; twenty event variants out.</span>
    <span>The payoff is that both engines can drive the same interface and the switch is a flag. The old loop is
      still on disk, dormant, roughly eleven hundred lines of it — kept precisely because a rollback that requires a
      rewrite is not a rollback.</span>
    <span>The price is that the site can no longer instrument the model call directly. Cost, throughput and liveness
      all have to be reconstructed from the outside, from a stream of frames, which is why so much of this section is
      about a stream of frames.</span>
  </p>

  <h2 class="pe-h2">One answer, several messages</h2>
  <p class="pe-prose" style="max-width:82ch">
    {#if eli}
      The reply does not arrive in one piece. It comes in chunks, and mixed in with those chunks are the system's own
      "still working" notes — travelling down exactly the same wire. Tell them apart wrongly and a progress note can
      wipe out the answer. That is not hypothetical: it happened.
    {:else}
      The runtime opens a fresh message id at every tool boundary, so one reply arrives as a chain of segments. It
      also interleaves its own status bubbles on the same text channel, re-editing them in place. Step the real
      sequence through both accumulators and watch what a flat one does.
    {/if}
  </p>

  <FrameStream />

  <div class="er-lesson">
    <span class="el-lab">The best kind of bug — the fix that broke something else</span>
    <p>Routing the progress filler off the text channel was correct, and it immediately created a second fault. The
      four-minute idle watchdog had been getting reset, <b>entirely by accident</b>, by that periodic filler arriving.
      Nobody designed it as a liveness signal; it just happened to be one. Remove it and any genuinely silent
      stretch — a rate-limit backoff, a long provider prefill — now trips a watchdog that used to be quietly held open.</p>
    <p>This is an <b>accidental invariant</b>: behaviour the system depended on that nothing declared and no test
      covered. They are only discoverable by breaking them, which is a good argument for fixing one thing at a time
      and watching what else moves.</p>
  </div>

  <h2 class="pe-h2">Silence is ambiguous</h2>
  <p class="pe-prose" style="max-width:82ch">
    A turn that has produced nothing for four minutes might be broken, or might be a sub-agent halfway through a long
    job, or might be waiting for a human who has gone to bed. Treating those identically means either killing real
    work or hanging forever on dead work. So the timeout is chosen by what the turn is actually doing.
  </p>

  <div class="ladder">
    {#each WATCHDOG as w, i}
      <button class="rung" class:on={tier === i} onclick={() => (tier = i)}>
        <span class="r-tier">{w.tier}</span>
        <span class="r-times"><b>{w.idle}</b> idle · <b>{w.hard}</b> hard</span>
      </button>
    {/each}
  </div>
  <div class="ladder-why">
    <span class="lw-lab">Why</span>
    <p>{WATCHDOG[tier].why}</p>
  </div>

  <h2 class="pe-h2">The numbers that keep a stream honest</h2>
  <div class="consts">
    {#each STREAM_CONSTANTS as c}
      <div class="c">
        <b>{c.v}</b>
        <span class="c-k">{c.k}</span>
        <span class="c-why">{c.why}</span>
      </div>
    {/each}
  </div>

  <div class="ds-grid two">
    <div class="ds-card">
      <span class="ds-kicker">Reconnection</span>
      <h3>Resume, never replay</h3>
      <p class="ds-body">Consumers <b>append</b> deltas. So replaying a job's buffer after a dropped connection
        silently doubled the reply — and invisibly, because the server accumulates separately, which is exactly why
        "a reload fixes it" was such a misleading symptom. Every published frame now carries its buffer index as the
        stream's event id, so the browser's native resume header picks up precisely where it stopped. That is what
        makes a twelve-second gap detector safe to run at all.</p>
    </div>
    <div class="ds-card">
      <span class="ds-kicker">The throughput meter</span>
      <h3>Measuring the wait, not just the typing</h3>
      <p class="ds-body">Most tokens-per-second readouts measure only the pleasant part. This one counts reply
        tokens, reasoning deltas and the arguments the model generated for its tool calls — and deliberately includes
        the waiting. Whole-bubble swaps are excluded because they would double-count; sub-agent frames are excluded
        because a delegate runs inside a parent that is already paused. The result is a materially lower number on
        tool-heavy turns, which is the honest one.</p>
    </div>
    <div class="ds-card">
      <span class="ds-kicker">A signal that lies</span>
      <h3>Nobody is watching</h3>
      <p class="ds-body">Deciding whether to escalate a finished long-running turn to a phone requires knowing if
        anyone is still looking. Subscriber count cannot answer it: the stream closes about ten milliseconds after a
        terminal event, so by the time the escalation grace period elapses the count is zero <b>whether or not</b>
        someone is sitting there. Presence is therefore tracked separately, on its own heartbeat with its own expiry.
        The obvious signal was not merely imprecise — it was systematically wrong at exactly the moment it was needed.</p>
    </div>
    <div class="ds-card">
      <span class="ds-kicker">Translation, in prose</span>
      <h3>Machinery, rewritten into English</h3>
      <p class="ds-body">The runtime interleaves a raw tool log into the text stream, so lines naming internal tool
        identifiers get persisted as part of the reply. A pure string transform rewrites them into sentences — eighty-eight
        tool-specific phrasings — behind two false-positive guards, because without them a genuine reply that happens
        to begin with a summary marker gets mangled into machine-speak. The guard list had to be widened once, after
        it turned out the runtime uses a different glyph per tool.</p>
    </div>
  </div>

  <a class="pe-next" href="/projects/engine-room/models">Next — how a model gets chosen, and what it costs →</a>
</section>

<style>
  .ladder { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 8px; margin: 14px 0 0; }
  .rung { display: flex; flex-direction: column; gap: 4px; text-align: left; cursor: pointer;
    border: 1px solid rgba(28,22,17,0.2); border-radius: var(--radius-round); background: rgba(255,255,255,0.5); padding: 10px 13px;
    transition: background 0.13s, border-color 0.13s; }
  .rung:hover { background: rgba(255,255,255,0.8); border-color: rgba(28,22,17,0.36); }
  .rung.on { background: var(--accent-ink); border-color: var(--accent-ink); }
  .r-tier { font-family: 'DM Sans', sans-serif; font-size: 13.5px; font-weight: 600; color: var(--text-primary); }
  .r-times { font-family: 'JetBrains Mono', monospace; font-size: 10px; color: rgba(28,22,17,0.6); }
  .r-times b { color: var(--accent); font-weight: 600; }
  .rung.on .r-tier, .rung.on .r-times { color: #fff; }
  .rung.on .r-times b { color: #ffd9b8; }

  .ladder-why { margin-top: 9px; border-left: 3px solid var(--accent-ink); background: var(--accent-ink-tint-12);
    border-radius: 0 var(--radius-round) var(--radius-round) 0; padding: 10px 14px; }
  .lw-lab { font-family: 'JetBrains Mono', monospace; font-size: 9px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--accent-ink); }
  .ladder-why p { margin: 4px 0 0; font-size: 13.5px; line-height: 1.58; color: rgba(28,22,17,0.78); max-width: 88ch; }

  .consts { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 9px; margin: 14px 0; }
  .c { border: 1px solid rgba(28,22,17,0.15); border-radius: var(--radius-round); background: rgba(255,255,255,0.5); padding: 10px 12px;
    display: flex; flex-direction: column; gap: 2px; }
  .c b { font-family: 'JetBrains Mono', monospace; font-size: 16px; font-weight: 600; color: var(--accent); line-height: 1.1; }
  .c-k { font-size: 12px; color: var(--text-primary); }
  .c-why { font-size: 11px; line-height: 1.45; color: rgba(28,22,17,0.58); margin-top: 3px; }
</style>
