<script lang="ts">
  import { onMount } from 'svelte';
  interface Mention{id:string;surface:string;excerpt:string|null;proposed_type:string;reason:string;note_title:string|null;candidates:Array<{id:string;name:string;detail:string;score:number;reason:string}>}
  let assertions=$state<Array<{id:string;predicate:string;value:unknown;current_value:unknown;name:string;source:string|null}>>([]);
  let mentions=$state<Mention[]>([]),message=$state(''),busy=$state(false);
  async function load(){try{const r=await fetch('/api/jkai/intel/mentions');if(!r.ok)throw new Error('Unable to load unresolved mentions');const body=await r.json();mentions=body.mentions;assertions=body.assertions??[];}catch(e){message=e instanceof Error?e.message:'Load failed';}}
  async function decide(id:string,action:string,entityId?:string){busy=true;try{const r=await fetch('/api/jkai/intel/mentions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,entityId})});if(!r.ok)throw new Error((await r.json()).message??'Review failed');await load();message='Review saved';}catch(e){message=e instanceof Error?e.message:'Review failed';}finally{busy=false;}}
  onMount(load);
</script>
<section><h2>Unresolved mentions ({mentions.length})</h2><p>Source references awaiting an identity decision. New entities and existing links both retain the original evidence.</p>
{#if message}<p role="status">{message}</p>{/if}
{#each mentions as m}<article><strong>{m.surface}</strong> · {m.proposed_type}<p>{m.note_title??'Untitled source'} · {m.reason}</p><blockquote>{m.excerpt??'No source span verified — inspect the note before creating an entity.'}</blockquote><div class="actions">{#each m.candidates as c}<div class="candidate"><a href={`/jkai/intel/entities/${c.id}`}>{c.name}</a><p>{c.detail}</p><button disabled={busy} onclick={()=>decide(m.id,'link',c.id)} title={c.reason}>Link this entity (score {c.score.toFixed(2)})</button></div>{/each}<button disabled={busy||!m.excerpt} onclick={()=>decide(m.id,'create')}>Create distinct entity</button><button disabled={busy} onclick={()=>decide(m.id,'reject')}>Reject extraction</button></div></article>{/each}
{#if assertions.length}<h2>Conflicting property evidence ({assertions.length})</h2>{#each assertions as a}<article><strong>{a.name} · {a.predicate}</strong><p>Current: {JSON.stringify(a.current_value)}<br/>Source says: {JSON.stringify(a.value)}</p><p>{a.source??'Source not recorded'}</p><div class="actions"><button disabled={busy} onclick={()=>decide(a.id,'accept-assertion')}>Accept source value</button><button disabled={busy} onclick={()=>decide(a.id,'reject-assertion')}>Keep current value</button></div></article>{/each}{/if}
</section>
<style>section{padding:1rem 0;border-top:1px solid var(--line-strong)}h2{font-size:var(--fs-body-lg)}article{padding:1rem 0;border-top:1px solid var(--line)}p,blockquote{line-height:1.5;overflow-wrap:anywhere}blockquote{border-left:2px solid var(--accent-ink);padding-left:1rem;margin:1rem 0}.candidate{max-width:24rem;overflow-wrap:anywhere}.actions{display:flex;gap:.5rem;flex-wrap:wrap}button{font:inherit;background:var(--surface-card);color:var(--text-primary);border:1px solid var(--line-strong);padding:.5rem;cursor:pointer}button:disabled{opacity:.5}</style>
