/** Publication metadata only. Real policy text is never bundled as a fixture. */
export const POLICY_EXAMPLES = [
  { id: 'soft-drinks', title: 'Soft Drinks Industry Levy', publisher: 'HM Revenue & Customs', publication_date: '2016-12-05', source_url: 'https://www.gov.uk/government/publications/soft-drinks-industry-levy/soft-drinks-industry-levy', topic: 'Health · tax', question: 'How might a charge change what businesses make and what customers buy?', edition: 'Historical policy paper' },
  { id: 'plastic-packaging', title: 'Introduction of a new plastic packaging tax', publisher: 'HM Revenue & Customs', publication_date: '2020-11-12', source_url: 'https://www.gov.uk/government/publications/introduction-of-a-new-plastic-packaging-tax/introduction-of-a-new-plastic-packaging-tax', topic: 'Environment · tax', question: 'Would businesses change materials, raise prices, or find another response?', edition: 'Historical policy paper' },
  { id: 'deposit-return', title: 'Deposit Return Scheme for drinks containers: joint policy statement', publisher: 'Department for Environment, Food & Rural Affairs', publication_date: '2024-04-25', source_url: 'https://www.gov.uk/government/publications/deposit-return-scheme-for-drinks-containers-policy-statements/deposit-return-scheme-for-drinks-containers-joint-policy-statement', topic: 'Recycling · delivery', question: 'Who needs to cooperate for a deposit-and-return system to work?', edition: 'Historical joint statement' },
  { id: 'biodiversity', title: 'Understanding biodiversity net gain', publisher: 'Department for Environment, Food & Rural Affairs', publication_date: '2023-02-21', source_url: 'https://www.gov.uk/guidance/understanding-biodiversity-net-gain', topic: 'Planning · environment', question: 'How might different ways to meet a requirement change people’s choices?', edition: 'Living guidance; check the version you load' },
] as const;
export type PolicyExample = typeof POLICY_EXAMPLES[number];
export const EXAMPLES_CHECKED = '2026-09-09';
