// Default scene — a deliberately rich set so the metaphor reads instantly.
// Multiple sources, some confluences (strands merging into other strands first),
// varied collection cadences and user counts.

import type { StrandConfig } from './types';

export const DEFAULT_CONFIG: StrandConfig[] = [
  // --- Confluence A: web behavioural ---
  {
    id: 'web-pageviews',
    name: 'Web pageviews',
    colour: '#b95431',
    startDate: '2018-03-01',
    mergeDate: '2021-09-01',
    mergeInto: 'web-behaviour',
    users: 420,
    frequency: 240,
    frequencyPeriod: 'day',
  },
  {
    id: 'web-clicks',
    name: 'Click events',
    colour: '#c98a2a',
    startDate: '2019-06-12',
    mergeDate: '2021-09-01',
    mergeInto: 'web-behaviour',
    users: 380,
    frequency: 180,
    frequencyPeriod: 'day',
  },
  {
    id: 'web-behaviour',
    name: 'Web behaviour (merged)',
    colour: '#9b3a55',
    startDate: '2021-09-01',
    mergeDate: '2024-04-01',
    mergeInto: 'spine',
    users: 90,
    frequency: 24,
    frequencyPeriod: 'day',
  },

  // --- Confluence B: CRM ---
  {
    id: 'crm-deals',
    name: 'CRM deals',
    colour: '#4a6b8a',
    startDate: '2017-01-15',
    mergeDate: '2022-02-15',
    mergeInto: 'crm-unified',
    users: 180,
    frequency: 12,
    frequencyPeriod: 'week',
  },
  {
    id: 'crm-contacts',
    name: 'CRM contacts',
    colour: '#6b8aa8',
    startDate: '2017-01-15',
    mergeDate: '2022-02-15',
    mergeInto: 'crm-unified',
    users: 320,
    frequency: 36,
    frequencyPeriod: 'week',
  },
  {
    id: 'crm-unified',
    name: 'CRM unified',
    colour: '#3d4f6e',
    startDate: '2022-02-15',
    mergeDate: '2024-09-01',
    mergeInto: 'spine',
    users: 70,
    frequency: 3,
    frequencyPeriod: 'day',
  },

  // --- Direct-to-spine sources ---
  {
    id: 'support-tickets',
    name: 'Support tickets',
    colour: '#6a8f4f',
    startDate: '2019-11-01',
    mergeDate: '2023-06-01',
    mergeInto: 'spine',
    users: 240,
    frequency: 1,
    frequencyPeriod: 'day',
  },
  {
    id: 'billing',
    name: 'Billing & invoicing',
    colour: '#8a6f3a',
    startDate: '2016-04-01',
    mergeDate: '2025-01-15',
    mergeInto: 'spine',
    users: 540,
    frequency: 1,
    frequencyPeriod: 'month',
  },
  {
    id: 'survey-nps',
    name: 'NPS surveys',
    colour: '#7a4a8c',
    startDate: '2020-08-01',
    mergeDate: '2024-11-15',
    mergeInto: 'spine',
    users: 150,
    frequency: 1,
    frequencyPeriod: 'quarter',
  },
  {
    id: 'product-telemetry',
    name: 'Product telemetry',
    colour: '#356b6b',
    startDate: '2021-02-01',
    mergeDate: '2025-08-01',
    mergeInto: 'spine',
    users: 880,
    frequency: 144,
    frequencyPeriod: 'day',
  },
];
