// Generated by scripts/sync-workflow-tool-descriptors.mjs from SR-Workflows; do not edit handlers here.
import { EXPRESSION_SYNTAX } from '$lib/workflows/expressions';
import { AMEND_OPS_DESCRIPTION } from '$lib/canvas/amend-validate.server';
import { registerWorkflowTool } from '../workflow-service';

registerWorkflowTool({
  name: 'workflow_build_from_spec',
  description:
    'Build a NEW canvas (workflow) from an EXPLICIT JSON spec — name, trigger, nodes, edges. ' +
    'PREFER workflow_generate UNLESS the user dictated exact node types and config: this tool takes your spec verbatim, ' +
    'so every config shape is a guess you are making, whereas workflow_generate grounds itself in the live node registry, ' +
    'plans, runs a critic round, then verifies and self-heals before saving. Reach for this one when you need precise ' +
    'control over an exact DAG the user specified. ' +
    'Use this when the user has confirmed the design you proposed in chat. ' +
    'DESIGN-FIRST WORKFLOW: Before calling this tool, you MUST have written out the design ' +
    'in chat (numbered nodes with type+label+config, edge wiring) and the user must have ' +
    'said yes/build it/ship it. Never call this tool with a guess at the design — every ' +
    'config field must be intentional. ' +
    'Each node is inserted into the canvas one at a time with a small delay, and the ' +
    'canvas page auto-refreshes between inserts so the user can watch the build live if ' +
    'they have the URL open. ' +
    'The tool emits the canvas URL on its very first progress event so the user can open it ' +
    'before the build finishes. ' +
    'CRITICAL: paste `data.summaryMarkdown` VERBATIM as your reply when the tool returns. ' +
    'It contains the canvas link, the description, every node with its actual saved config, ' +
    'the flow diagram, and any "Needs attention" issues that need fixing on the canvas. ' +
    'Do NOT rewrite it, summarise it, or construct your own URL.',
  parameters: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
        description: 'Short canvas name (will be slugified for the URL).',
      },
      description: {
        type: 'string',
        description: 'One-line human description of what the canvas does.',
      },
      trigger: {
        type: 'object',
        description:
          'How the workflow fires. type ∈ {manual, cron, webhook, event}. For cron, set config.expression to a 5-field cron string (e.g. "*/15 * * * *"). For event, set config.eventType. For webhook, set config.secret — external callers HMAC-sign timestamp.body with SHA-256.',
        properties: {
          type: { type: 'string' },
          config: { type: 'object' },
        },
      },
      nodes: {
        type: 'array',
        description:
          'The non-trigger nodes that do the work. Each node: { id (spec-local, used by edges), type (registered node type), label, config, position? }. The trigger node is auto-inserted — do NOT include a node with type="trigger" yourself.',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            type: { type: 'string' },
            label: { type: 'string' },
            config: { type: 'object' },
            position: { type: 'object' },
          },
        },
      },
      edges: {
        type: 'array',
        description:
          'Wiring between nodes. Each edge: { from (spec id), to (spec id), sourceHandle? (e.g. "true"/"false" on conditional), targetHandle? }. Use "trigger" as a special source id to wire from the auto-inserted trigger node; if you omit a trigger edge, one is added to the first non-chat node automatically.',
        items: {
          type: 'object',
          properties: {
            from: { type: 'string' },
            to: { type: 'string' },
            sourceHandle: { type: 'string' },
            targetHandle: { type: 'string' },
          },
        },
      },
      attach_chat_node: {
        type: 'boolean',
        description:
          'When true (default), inserts a `chat` node alongside the trigger so the user can continue talking to you from the canvas. Set false only if the workflow really has no chat interaction.',
      },
    },
    required: ['name', 'nodes'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_list',
  description:
    'List existing workflows with their names, descriptions, and schedule status. ' +
    'Compact by default — returns only the identifying fields (id, name, description, trigger, updatedAt) to keep token usage low. ' +
    'Pass verbose:true to return the full rows including heavy columns (notifications, createdAt).',
  parameters: {
    type: 'object',
    properties: {
      verbose: { type: 'boolean', description: 'Set true to return full rows including heavy columns; defaults to compact identifying fields only' },
    },
    required: [],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_delete',
  destructive: true,
  description:
    'Permanently delete a workflow by ID. This CASCADES — all nodes, edges, run history, chat messages and audit log for the canvas are wiped and CANNOT be recovered. ' +
    'Only call this when the user has explicitly asked to delete that specific workflow by name or id. ' +
    'You MUST pass confirmName matching the workflow\'s exact current name so the user cannot be wiped out by a misinterpreted request. ' +
    'If you are on a canvas and the user asks to "start over" or "clear", DO NOT delete — use workflow_remove_node / workflow_remove_edge instead.',
  parameters: {
    type: 'object',
    properties: {
      id: { type: 'string', description: 'Workflow ID to delete' },
      confirmName: {
        type: 'string',
        description: 'Must exactly match the workflow\'s current `name` (e.g. "canvas:scraptest"). Safety check — call workflow_inspect first to read the name.',
      },
    },
    required: ['id', 'confirmName'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_inspect',
  description: 'Full structural view of a workflow — metadata, all nodes (type, label, config), all edges (connections), schedules, and last 5 execution runs',
  parameters: {
    type: 'object',
    properties: { id: { type: 'string', description: 'Workflow ID (`workflowId` is accepted too — the toolset uses both spellings)' } },
    required: ['id'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_get_run',
  description: 'Drill into a specific workflow execution run — per-node inputs, outputs, errors, timing, and logs',
  parameters: {
    type: 'object',
    properties: { runId: { type: 'string', description: 'Run ID (from workflow_inspect recentRuns)' } },
    required: ['runId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_get_generation_log',
  description: 'Replay how the orchestrator built a workflow — the tool-calling sequence (search_nodes, use_node, connect_nodes, finalize) with reasoning',
  parameters: {
    type: 'object',
    properties: { workflowId: { type: 'string', description: 'Workflow ID (`id` is accepted too — the toolset uses both spellings)' } },
    required: ['workflowId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_update_metadata',
  description: 'Rename a workflow, update its description, or change its trigger config',
  parameters: {
    type: 'object',
    properties: {
      id: { type: 'string', description: 'Workflow ID (`workflowId` is accepted too — the toolset uses both spellings)' },
      name: { type: 'string', description: 'New name' },
      description: { type: 'string', description: 'New description' },
      trigger: { type: 'object', description: 'New trigger config (e.g. {"type":"manual"})' },
    },
    required: ['id'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_update_node',
  description:
    "Update a workflow node's config, label, or type. When changing type, the new type must exist in the node registry. " +
    'To REMOVE a config key entirely (not just set it to a new value), either pass it as `null` in `config` or list its name in `removeConfigKeys`. ' +
    'Setting a key to `null` and leaving the key in the saved config used to be an LLM trap — now both paths actually delete.',
  parameters: {
    type: 'object',
    properties: {
      nodeId: { type: 'string', description: 'Node ID' },
      config: {
        type: 'object',
        description:
          'Patch merged into existing config. To remove a key, set it to null (e.g. `{ value: null }`) — the merged result drops the key entirely.',
      },
      removeConfigKeys: {
        type: 'array',
        items: { type: 'string' },
        description: 'Explicit list of config keys to delete after the merge. Use this when you want to be unambiguous about removal.',
      },
      label: { type: 'string', description: 'New label' },
      type: { type: 'string', description: 'New node type — must match a registered type (e.g. "whatsapp", "llm-call", "code-execute"). Use workflow_list_node_types to see all valid types.' },
    },
    required: ['nodeId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_add_node',
  description: 'Add a new node to a workflow. The type must match a registered node type exactly — typos (e.g. "code-exec" instead of "code-execute", or "whatsapp-message" instead of "whatsapp") will be rejected because the canvas cannot render them. Call workflow_list_node_types first if you are unsure which type to use.',
  parameters: {
    type: 'object',
    properties: {
      workflowId: { type: 'string', description: 'Workflow ID (`id` is accepted too — the toolset uses both spellings)' },
      type: { type: 'string', description: 'Node type — must match a registered type exactly. Examples: "manual-trigger", "whatsapp", "llm-call", "code-execute", "http-request", "conditional", "data-store". Call workflow_list_node_types to see the full list.' },
      label: { type: 'string', description: 'Display label for the node' },
      config: { type: 'object', description: 'Node configuration (see node definition for its configSchema)' },
      position: { type: 'object', description: '{ x, y } canvas position', properties: { x: { type: 'number' }, y: { type: 'number' } } },
    },
    required: ['workflowId', 'type', 'label'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_list_node_types',
  description:
    'List registered workflow node types with their labels, categories and descriptions. This is the authoritative list — anything not in it will be rejected by workflow_add_node / workflow_update_node. ' +
    'PASS A `query` describing what you need ("whatsapp", "scrape a page", "run python") — the unfiltered catalogue is 88 types and costs ~5k tokens, a filtered one costs a few hundred. ' +
    'Only omit `query` when you genuinely need to survey everything.',
  parameters: {
    type: 'object',
    properties: {
      query: {
        type: 'string',
        description:
          'Case-insensitive filter over type, label, category and description. Space-separated words are OR-ed, so "email whatsapp notify" returns every messaging node.',
      },
      category: {
        type: 'string',
        description: 'Exact category filter (e.g. "control", "integration"). Combine with query to narrow further.',
      },
    },
    required: [],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_describe_node',
  description:
    'Get the FULL detail for one or more node types — config schema (every field with type, required flag, enum values and defaults), input/output ports, usage guidance and example configs. ' +
    'Call this after workflow_list_node_types when you need the exact config keys before adding or updating nodes. ' +
    'PASS EVERY TYPE YOU PLAN TO USE IN ONE CALL: `types: ["llm-call","whatsapp","conditional"]`. A six-node build should cost one list + one describe, not seven round-trips. ' +
    'This returns the same grounding the orchestrator sees in its Node Registry — use it instead of guessing config shapes and getting rejected at write time.',
  parameters: {
    type: 'object',
    properties: {
      types: {
        type: 'array',
        items: { type: 'string' },
        description: 'Registered node types to describe, e.g. ["llm-call", "http-request", "conditional"]. Preferred over `type` — ask for everything the planned workflow needs at once.',
      },
      type: {
        type: 'string',
        description: 'Single registered node type. Accepted for convenience; prefer `types` when you need more than one.',
      },
    },
    required: [],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_remove_node',
  description: 'Remove a node from a workflow (also removes all connected edges)',
  parameters: {
    type: 'object',
    properties: { nodeId: { type: 'string', description: 'Node ID to remove' } },
    required: ['nodeId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_add_edge',
  description: 'Connect two nodes in a workflow',
  parameters: {
    type: 'object',
    properties: {
      workflowId: { type: 'string', description: 'Workflow ID (`id` is accepted too — the toolset uses both spellings)' },
      sourceNodeId: { type: 'string', description: 'Source node ID' },
      targetNodeId: { type: 'string', description: 'Target node ID' },
      sourceHandle: { type: 'string', description: 'Source handle (e.g. "success", "error"). Omit for default.' },
      targetHandle: { type: 'string', description: 'Target handle. Omit for default.' },
    },
    required: ['workflowId', 'sourceNodeId', 'targetNodeId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_remove_edge',
  description: 'Remove a connection between workflow nodes',
  parameters: {
    type: 'object',
    properties: { edgeId: { type: 'string', description: 'Edge ID' } },
    required: ['edgeId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_update_edge',
  description: "Change an edge's routing — reconnect to different nodes or change handles",
  parameters: {
    type: 'object',
    properties: {
      edgeId: { type: 'string', description: 'Edge ID' },
      sourceNodeId: { type: 'string', description: 'New source node ID' },
      targetNodeId: { type: 'string', description: 'New target node ID' },
      sourceHandle: { type: 'string', description: 'New source handle' },
      targetHandle: { type: 'string', description: 'New target handle' },
    },
    required: ['edgeId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_amend',
  description:
    'Apply several canvas edits as ONE atomic change — the tool to reach for when an amendment is more than a single node config tweak. ' +
    'Rewiring a branch is add-node + remove-edge + add-edge + add-edge; run as separate tool calls a failure halfway leaves a dangling node and a severed branch on a canvas nobody is looking at. Here either all of it lands or none of it does. ' +
    'Every write is version-checked, audited and visible in the canvas inspector history, and update ops return a before-image you can feed back to workflow_update_node to undo. ' +
    'Prefer this over workflow_generate for changing an existing canvas: generate REPLACES the whole graph and loses node ids, run history and layout.',
  parameters: {
    type: 'object',
    properties: {
      workflowId: { type: 'string', description: 'Workflow ID to amend' },
      ops: {
        type: 'array',
        items: { type: 'object' },
        description: AMEND_OPS_DESCRIPTION,
      },
      reason: {
        type: 'string',
        description: "Why, in the user's own words. Stored on every audit row this amend writes.",
      },
    },
    required: ['workflowId', 'ops'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_add_schedule',
  description: 'Add a cron schedule to a workflow',
  parameters: {
    type: 'object',
    properties: {
      workflowId: { type: 'string', description: 'Workflow ID (`id` is accepted too — the toolset uses both spellings)' },
      type: { type: 'string', description: 'Schedule type (e.g. "cron")' },
      config: { type: 'object', description: 'Schedule config. For cron, set the 5-field cron string as { "expression": "0 8 * * *" } (daily at 8am). "cron" is accepted as an alias. Times are interpreted in Europe/London (so "0 8" means 8am the owner\'s time, all year) unless you set { "timezone": "..." } to an IANA zone.' },
    },
    required: ['workflowId', 'type', 'config'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_update_schedule',
  description: 'Enable/disable a schedule or change its cron config',
  parameters: {
    type: 'object',
    properties: {
      scheduleId: { type: 'string', description: 'Schedule ID' },
      enabled: { type: 'boolean', description: 'Enable or disable' },
      config: { type: 'object', description: 'New schedule config' },
    },
    required: ['scheduleId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_remove_schedule',
  description: 'Remove a schedule from a workflow',
  parameters: {
    type: 'object',
    properties: { scheduleId: { type: 'string', description: 'Schedule ID' } },
    required: ['scheduleId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_run',
  description:
    'Trigger a workflow run on behalf of the user. Creates a manual run, fires the engine, and returns the runId. ' +
    'When `awaitMs` is set (max 600000 = 10 min), the call BLOCKS until the run completes/fails or the timeout elapses, ' +
    'and returns the full run + node executions inline. When unset, returns immediately and the run continues in the background — ' +
    'pair with workflow_get_run to inspect later, or call workflow_subscribe to receive results in a future iteration.',
  parameters: {
    type: 'object',
    properties: {
      id: { type: 'string', description: 'Workflow ID to run' },
      input: {
        type: 'object',
        description: 'Optional initial input passed to the trigger node. Defaults to {}.',
      },
      selfHealing: {
        type: 'boolean',
        description: 'If true (default), the engine attempts to auto-heal node config errors. Set false for strict test runs.',
      },
      mode: {
        type: 'string',
        enum: ['live', 'test'],
        description: "'test' = a TEST run: pinned steps use their saved output, steps that send/write/book are stubbed (not run), nothing is announced, and `input` defaults to a sample payload. Use it to try a workflow safely. Default 'live'.",
      },
      awaitMs: {
        type: 'number',
        description: 'Max milliseconds to wait for completion (max 600000). When set, the call returns the full run result.',
      },
    },
    required: ['id'],
  },
  category: 'Workflows',
  toolset: 'workflows',
  producesLongRunningTask: { kind: 'workflow_run', idPath: 'runId', cadenceSeconds: 30 }
});

registerWorkflowTool({
  name: 'workflow_subscribe',
  description:
    'Subscribe a JKAI build to a workflow. When the workflow next runs to completion (via schedule, manual trigger, event, or another tool call), ' +
    'the result is queued as a pending delivery and surfaced at the top of the build\'s next iteration prompt. ' +
    'Use this when the builder needs an asynchronous data source it can react to without blocking the current iteration.',
  parameters: {
    type: 'object',
    properties: {
      buildId: { type: 'string', description: 'Build ID to receive deliveries' },
      workflowId: { type: 'string', description: 'Workflow whose run completions should be delivered' },
    },
    required: ['buildId', 'workflowId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_unsubscribe',
  description: 'Remove a workflow subscription from a build.',
  parameters: {
    type: 'object',
    properties: {
      buildId: { type: 'string' },
      workflowId: { type: 'string' },
    },
    required: ['buildId', 'workflowId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_clear_data_store',
  destructive: true,
  description:
    'Clear entries from a workflow\'s data store. Use this to enable smoother test runs of pipelines that dedupe via stored "seen" keys. ' +
    'Three modes (pick one): pass `keys` to wipe specific keys (e.g. ["seen_urls"]), `all: true` to wipe every key for the workflow, ' +
    'or `sinceLastNRuns` to wipe entries written/updated during the last N completed runs. ' +
    'Always confirm with the user before calling — this is destructive within the workflow\'s scoped store.',
  parameters: {
    type: 'object',
    properties: {
      workflowId: { type: 'string', description: 'Workflow ID whose data store should be cleared' },
      keys: {
        type: 'array',
        items: { type: 'string' },
        description: 'Specific store keys to delete. Mutually exclusive with `all` and `sinceLastNRuns`.',
      },
      all: {
        type: 'boolean',
        description: 'When true, delete every data-store row for this workflow.',
      },
      sinceLastNRuns: {
        type: 'number',
        description: 'Delete data-store rows whose updatedAt is on/after the start time of the Nth most recent run.',
      },
    },
    required: ['workflowId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_lint',
  description:
    'Run a static linter over a workflow\'s nodes/edges before triggering a run. Catches the common authoring mistakes: ' +
    'unsupported template syntax, unknown config keys, code-execute body issues, and {{input.X}} references that don\'t match the upstream schema. ' +
    'Returns issues with severity. Call this after any structural edit to catch failures cheaply, before workflow_run.',
  parameters: {
    type: 'object',
    properties: {
      workflowId: { type: 'string', description: 'Workflow ID to lint' },
    },
    required: ['workflowId'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});

registerWorkflowTool({
  name: 'workflow_generate',
  description:
    'Generate (or modify) a complete workflow from a natural-language request using the in-repo rich generator. ' +
    'PREFER THIS over hand-authoring a DAG with workflow_build_from_spec / workflow_add_node when the user describes what they want in prose. ' +
    'The generator grounds itself in the live node registry, plans the nodes + wiring, runs a critic-revision round, then verifies and self-heals the result before saving — so you get a correct, runnable workflow instead of guessing config shapes yourself. ' +
    'Pass `prompt` with the full request (e.g. "every morning at 8am, fetch my Hacker News front page and WhatsApp me the top 5 titles"). ' +
    'Omit `workflowId` to create a brand-new canvas; pass an existing `workflowId` to regenerate/modify that workflow in place. ' +
    'Returns the workflowId, canvas URL, a human summary, and the final verification status. ' +
    'If `verificationPassed` is false, the workflow was saved but has blocking errors you must resolve with workflow_update_node before telling the user it is done.',
  parameters: {
    type: 'object',
    properties: {
      prompt: {
        type: 'string',
        description:
          'The natural-language workflow request — what should the workflow do, when should it fire, and what should it produce. Be specific; the generator builds directly from this.',
      },
      workflowId: {
        type: 'string',
        description:
          'Optional. When provided, the generator modifies THIS existing workflow (its current nodes/edges are replaced with the regenerated graph). Omit to create a new canvas.',
      },
    },
    required: ['prompt'],
  },
  category: 'Workflows',
  toolset: 'workflows'
});
