#!/usr/bin/env bash
#
# Push the Voice Card out to the prompt stacks that do not share this repo's
# filesystem.
#
#   scripts/sync-voice.sh [--check]
#
# --check writes nothing and exits non-zero if any destination is out of date.
#
# WHY THIS EXISTS. The card lives in data/voice/ and SvelteKit surfaces read it
# directly. Two other things write in John's voice and cannot see that file:
# Claude Code (and the builder it drives), and the sr-docs content tree. Before
# this script those two had either a stale copy of his voice or none at all.
# One generator, three destinations, so they cannot drift apart again.
#
# /jkai CHAT IS NOT A DESTINATION HERE. Its voice used to be written into the
# retired gateway's own SKILL.md on this box; it now lives in data/prompts/ in
# this repo and ships with an ordinary deploy.
#
# HOMESERV ONLY, and it needs no rsync line in ci-release.sh. Every destination
# is a path on this box; nothing here runs on the VPS. (New scripts usually DO
# need their own rsync line — ci-release.sh syncs scripts/ by allow-list — so
# the absence of one here is deliberate, not an oversight.)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

CARD="data/voice/voice-card.json"
[[ -f "$CARD" ]] || { echo "No $CARD. Run scripts/build-voice-card.ts first." >&2; exit 1; }

CLAUDE_SKILL_DIR="$HOME/.claude/skills/john-voice"
SRDOCS_PAGE="$HOME/sr-docs/content/internal/design-system/john-voice.md"

BEGIN='<!-- VOICE:BEGIN — generated by strange_rambling_svelte/scripts/sync-voice.sh. Do not edit by hand. -->'
END='<!-- VOICE:END -->'

changed=0

# Render a register's block via the same code the app uses, so what Claude is
# told is byte-identical to what the SvelteKit surfaces are told.
render() {
  npx tsx --eval "
    import { readFileSync } from 'node:fs';
    import { renderVoiceBlock } from './src/lib/voice/block.ts';
    import { parseExemplar } from './src/lib/voice/card.ts';
    import { readdirSync } from 'node:fs';
    const card = JSON.parse(readFileSync('$CARD', 'utf8'));
    const dir = 'data/voice/exemplars';
    const exemplars = readdirSync(dir).filter(f => f.endsWith('.md')).sort()
      .map(f => parseExemplar(f, readFileSync(dir + '/' + f, 'utf8')))
      .filter(Boolean);
    const wanted = card.registers['$1'].exemplarIds ?? [];
    const byId = new Map(exemplars.map(e => [e.id, e]));
    const ordered = wanted.map(id => byId.get(id)).filter(Boolean);
    process.stdout.write(renderVoiceBlock(card, '$1', ordered, { exemplars: $2 }));
  "
}

write_if_changed() {
  local path="$1" content="$2" label="$3"
  # Both sides through command substitution so trailing newlines are stripped
  # identically — comparing a raw string against $(cat) reports every file as
  # changed forever, which makes --check useless.
  if [[ -f "$path" ]] && [[ "$(cat "$path")" == "$(printf '%s' "$content")" ]]; then
    echo "  = $label unchanged"
    return
  fi
  changed=1
  if (( CHECK_ONLY )); then
    echo "  ! $label OUT OF DATE"
    return
  fi
  mkdir -p "$(dirname "$path")"
  printf '%s' "$content" > "$path"
  echo "  + $label written"
}

echo "==> Rendering blocks from $CARD"
CHAT_BLOCK="$(render chat 0)"
PROSE_BLOCK="$(render public-prose 2)"

# --- 1. Claude Code --------------------------------------------------------
echo "==> Claude Code ($CLAUDE_SKILL_DIR)"
claude_skill="---
name: john-voice
description: Use when writing ANY prose that will appear as John's own words — blog posts, project pages, docs, release notes, commit messages, or replies on his behalf. Generated from his measured corpus; do not edit by hand.
---

# Writing as John

$BEGIN

$PROSE_BLOCK

$END

## Chat and short replies

$CHAT_BLOCK

## Where this comes from

Generated by \`strange_rambling_svelte/scripts/sync-voice.sh\` from
\`data/voice/voice-card.json\`, which is measured from the blog posts tagged
\`authorship='human'\`. Edit the card or the exemplars and re-run the script —
hand edits here are overwritten.

The plan and the reasoning live in
\`strange_rambling_svelte/docs/plans/2026-08-19-writing-voice-system.md\`.
"
write_if_changed "$CLAUDE_SKILL_DIR/SKILL.md" "$claude_skill" "john-voice skill"

# --- 2. sr-docs ------------------------------------------------------------
echo "==> sr-docs ($SRDOCS_PAGE)"
if [[ ! -d "$HOME/sr-docs/content" ]]; then
  echo "  ! sr-docs not found — skipping"
else
  updated_date="$(git log -1 --format=%cs -- "$CARD" 2>/dev/null || echo '')"
  [[ -n "$updated_date" ]] || updated_date="$(git log -1 --format=%cs 2>/dev/null || echo '1970-01-01')"
  srdocs="---
title: \"Writing as John\"
summary: \"The measured voice: how his prose actually behaves, what the automated writers are told, and where the rules disagree with the evidence.\"
audience: both
visibility: internal
tags: [design-system, brand, voice, writing]
status: published
updated: $updated_date
---

$BEGIN

## Public prose

$PROSE_BLOCK

## Chat

$CHAT_BLOCK

$END

## How this is made

Measured from the blog posts tagged \`authorship='human'\` that clear the prose floor,
then rendered by the same code the site's own prompts use, so this page cannot drift from
what the models are actually told.

Regenerate with \`strange_rambling_svelte/scripts/sync-voice.sh\`. Hand edits are
overwritten; change the card or the exemplars instead.
"
  write_if_changed "$SRDOCS_PAGE" "$srdocs" "sr-docs page"
fi

# --- done -------------------------------------------------------------------
if (( CHECK_ONLY )); then
  (( changed )) && { echo; echo "Out of date. Run without --check."; exit 1; }
  echo; echo "Everything up to date."
  exit 0
fi

if (( changed )); then
  echo
  echo "Commit the sr-docs page in ~/sr-docs."
  echo "The CHAT voice is not synced here — it lives in data/prompts/ in this"
  echo "repo and ships with a normal deploy."
else
  echo; echo "Nothing changed."
fi
