#!/usr/bin/env bash
#
# Push the Voice Card out to the prompt stacks that do not share this repo's
# filesystem.
#
#   scripts/sync-voice.sh [--check]
#
# --check writes nothing and exits non-zero if any destination is out of date.
#
# WHY THIS EXISTS. The card lives in data/voice/ and SvelteKit surfaces read it
# directly. Three other things write in John's voice and cannot see that file:
# the Hermes agent behind /jkai chat, Claude Code (and the builder it drives),
# and the sr-docs content tree. Before this script those three had either a
# stale copy of his voice or none at all. One generator, four destinations, so
# they cannot drift apart again.
#
# HOMESERV ONLY, and it needs no rsync line in ci-release.sh. Every destination
# is a path on this box; nothing here runs on the VPS. (New scripts usually DO
# need their own rsync line — ci-release.sh syncs scripts/ by allow-list — so
# the absence of one here is deliberate, not an oversight.)
#
# THE HERMES EDIT DOES NOT TAKE EFFECT UNTIL A RESTART. Editing a SKILL.md has
# no effect on live /jkai chat until `systemctl --user restart jkai-hermes`;
# this script does it for you and says so. Skipping it looks exactly like bad
# prompt engineering and has burned a day before.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

CARD="data/voice/voice-card.json"
[[ -f "$CARD" ]] || { echo "No $CARD. Run scripts/build-voice-card.ts first." >&2; exit 1; }

HERMES_SKILL="$HOME/.hermes-jkai/skills/jkai-general/SKILL.md"
CLAUDE_SKILL_DIR="$HOME/.claude/skills/john-voice"
SRDOCS_PAGE="$HOME/sr-docs/content/internal/design-system/john-voice.md"

BEGIN='<!-- VOICE:BEGIN — generated by strange_rambling_svelte/scripts/sync-voice.sh. Do not edit by hand. -->'
END='<!-- VOICE:END -->'

changed=0

# Render a register's block via the same code the app uses, so what Hermes and
# Claude are told is byte-identical to what the SvelteKit surfaces are told.
render() {
  npx tsx --eval "
    import { readFileSync } from 'node:fs';
    import { renderVoiceBlock } from './src/lib/voice/block.ts';
    import { parseExemplar } from './src/lib/voice/card.ts';
    import { readdirSync } from 'node:fs';
    const card = JSON.parse(readFileSync('$CARD', 'utf8'));
    const dir = 'data/voice/exemplars';
    const exemplars = readdirSync(dir).filter(f => f.endsWith('.md')).sort()
      .map(f => parseExemplar(f, readFileSync(dir + '/' + f, 'utf8')))
      .filter(Boolean);
    const wanted = card.registers['$1'].exemplarIds ?? [];
    const byId = new Map(exemplars.map(e => [e.id, e]));
    const ordered = wanted.map(id => byId.get(id)).filter(Boolean);
    process.stdout.write(renderVoiceBlock(card, '$1', ordered, { exemplars: $2 }));
  "
}

write_if_changed() {
  local path="$1" content="$2" label="$3"
  # Both sides through command substitution so trailing newlines are stripped
  # identically — comparing a raw string against $(cat) reports every file as
  # changed forever, which makes --check useless.
  if [[ -f "$path" ]] && [[ "$(cat "$path")" == "$(printf '%s' "$content")" ]]; then
    echo "  = $label unchanged"
    return
  fi
  changed=1
  if (( CHECK_ONLY )); then
    echo "  ! $label OUT OF DATE"
    return
  fi
  mkdir -p "$(dirname "$path")"
  printf '%s' "$content" > "$path"
  echo "  + $label written"
}

echo "==> Rendering blocks from $CARD"
CHAT_BLOCK="$(render chat 0)"
PROSE_BLOCK="$(render public-prose 2)"

# --- 1. Hermes -------------------------------------------------------------
#
# The voice goes into jkai-general, the always-loaded router, NOT a skill of its
# own. Hermes truncates every skill description to 60 characters and is told to
# load anything "even partially relevant", so a `jkai-voice` skill would either
# be routed past when it mattered or loaded for everything. Voice applies to
# every reply, so it belongs in the prompt that is always present.
echo "==> Hermes ($HERMES_SKILL)"
if [[ ! -f "$HERMES_SKILL" ]]; then
  echo "  ! jkai-general not found — skipping Hermes" >&2
else
  section="$BEGIN
## Voice — how John writes, and how you write to him

$CHAT_BLOCK
$END"
  # Replace between the markers if they are there, append if not. Done in
  # python because the block contains every character bash would try to expand.
  updated="$(SECTION="$section" BEGIN="$BEGIN" END="$END" python3 - "$HERMES_SKILL" <<'PY'
import os, sys
src = open(sys.argv[1], encoding='utf-8').read()
begin, end, section = os.environ['BEGIN'], os.environ['END'], os.environ['SECTION']
if begin in src and end in src:
    a, b = src.index(begin), src.index(end) + len(end)
    out = src[:a] + section + src[b:]
else:
    out = src.rstrip('\n') + '\n\n' + section + '\n'
sys.stdout.write(out)
PY
)"
  write_if_changed "$HERMES_SKILL" "$updated" "jkai-general voice section"
fi

# --- 2. Claude Code --------------------------------------------------------
echo "==> Claude Code ($CLAUDE_SKILL_DIR)"
claude_skill="---
name: john-voice
description: Use when writing ANY prose that will appear as John's own words — blog posts, project pages, docs, release notes, commit messages, or replies on his behalf. Generated from his measured corpus; do not edit by hand.
---

# Writing as John

$BEGIN

$PROSE_BLOCK

$END

## Chat and short replies

$CHAT_BLOCK

## Where this comes from

Generated by \`strange_rambling_svelte/scripts/sync-voice.sh\` from
\`data/voice/voice-card.json\`, which is measured from the blog posts tagged
\`authorship='human'\`. Edit the card or the exemplars and re-run the script —
hand edits here are overwritten.

The plan and the reasoning live in
\`strange_rambling_svelte/docs/plans/2026-08-19-writing-voice-system.md\`.
"
write_if_changed "$CLAUDE_SKILL_DIR/SKILL.md" "$claude_skill" "john-voice skill"

# --- 3. sr-docs ------------------------------------------------------------
echo "==> sr-docs ($SRDOCS_PAGE)"
if [[ ! -d "$HOME/sr-docs/content" ]]; then
  echo "  ! sr-docs not found — skipping"
else
  updated_date="$(git log -1 --format=%cs -- "$CARD" 2>/dev/null || echo '')"
  [[ -n "$updated_date" ]] || updated_date="$(git log -1 --format=%cs 2>/dev/null || echo '1970-01-01')"
  srdocs="---
title: \"Writing as John\"
summary: \"The measured voice: how his prose actually behaves, what the automated writers are told, and where the rules disagree with the evidence.\"
audience: both
visibility: internal
tags: [design-system, brand, voice, writing]
status: published
updated: $updated_date
---

$BEGIN

## Public prose

$PROSE_BLOCK

## Chat

$CHAT_BLOCK

$END

## How this is made

Measured from the blog posts tagged \`authorship='human'\` that clear the prose floor,
then rendered by the same code the site's own prompts use, so this page cannot drift from
what the models are actually told.

Regenerate with \`strange_rambling_svelte/scripts/sync-voice.sh\`. Hand edits are
overwritten; change the card or the exemplars instead.
"
  write_if_changed "$SRDOCS_PAGE" "$srdocs" "sr-docs page"
fi

# --- restart ---------------------------------------------------------------
if (( CHECK_ONLY )); then
  (( changed )) && { echo; echo "Out of date. Run without --check."; exit 1; }
  echo; echo "Everything up to date."
  exit 0
fi

if (( changed )); then
  echo "==> Restarting jkai-hermes (a SKILL.md edit does nothing until this happens)"
  if systemctl --user restart jkai-hermes 2>/dev/null; then
    echo "  + jkai-hermes restarted"
  else
    echo "  ! could not restart jkai-hermes — do it by hand:" >&2
    echo "      systemctl --user restart jkai-hermes" >&2
  fi
  echo
  echo "Commit the Hermes edit in ~/.hermes-jkai (it is its own repo) and the"
  echo "sr-docs page in ~/sr-docs."
else
  echo; echo "Nothing changed; Hermes left alone."
fi
