// Generated by curate-codegen emitter. Do not hand-edit this file.
import type { NodeSpec, UISchemaField } from '../spec/types';

export function emitDefinition(spec: NodeSpec): string {
  const fields = spec.uiSchema.sections.flatMap((s) => s.fields);
  const basicConfigLines = fields
    .map(fieldToBasicConfig)
    .filter((x): x is string => x !== null);
  const basicConfigStr = basicConfigLines.map((l) => `    ${l}`).join(',\n');

  return `// Generated by curate-codegen. Do not hand-edit; re-curate to update.

import type { NodeDefinition } from '$lib/workflows/types';

export const ${camel(spec.type)}Def: NodeDefinition = {
  type: '${spec.type}',
  label: '${escape(spec.label)}',
  category: '${spec.category}',
  description: '${escape(spec.description)}',
  llmDescription: ${tsString(spec.llmDescription)},
  llmExamples: ${json(spec.llmExamples, 2)},
  configSchema: ${json(spec.configSchema, 2)},
  defaultConfig: ${json(spec.defaultConfig, 2)},
  basicConfig: [
${basicConfigStr}
  ],
};
`;
}

function fieldToBasicConfig(field: UISchemaField): string | null {
  const typeMap: Record<string, string> = {
    'string': 'string',
    'textarea': 'textarea',
    'dropdown': 'dropdown',
    'toggle': 'toggle',
    'datetime': 'string',
    'credential-picker': 'string',
    'resource-picker': 'string',
    'template-string': 'string',
  };
  const t = typeMap[field.widget] ?? 'string';
  const parts = [
    `{ key: '${field.key}'`,
    `label: '${escape(field.label)}'`,
    `type: '${t}'`,
  ];
  if ('description' in field && field.description) {
    parts.push(`description: ${tsString(field.description)}`);
  }
  if (field.required) parts.push(`required: true`);
  return `${parts.join(', ')} }`;
}

function camel(kebab: string): string {
  return kebab.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function escape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function tsString(s: string): string {
  if (s.includes('\n')) return '`' + s.replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
  return `'${escape(s)}'`;
}

function json(value: unknown, indent: number): string {
  return JSON.stringify(value, null, indent).replace(/\n/g, '\n  ');
}
