// Generated by curate-codegen emitter. Do not hand-edit this file.
import type { NodeSpec, UISchemaField } from '../spec/types';

// Project's NodeDefinition.category union (see src/lib/workflows/types.ts).
// Curated nodes default to 'integration' since they wrap external services.
const VALID_CATEGORIES = new Set([
  'trigger', 'core', 'integration', 'control', 'custom', 'agentic',
]);

function normalizeCategory(raw: string): string {
  return VALID_CATEGORIES.has(raw) ? raw : 'integration';
}

export function emitDefinition(spec: NodeSpec): string {
  const fields = spec.uiSchema.sections.flatMap((s) => s.fields);
  const basicConfigLines = fields
    .map(fieldToBasicConfig)
    .filter((x): x is string => x !== null);
  const basicConfigStr = basicConfigLines.map((l) => `    ${l}`).join(',\n');

  return `// Generated by curate-codegen. Do not hand-edit; re-curate to update.

import type { NodeDefinition } from '$lib/workflows/types';

export const ${camel(spec.type)}Def: NodeDefinition = {
  type: '${spec.type}',
  label: '${escape(spec.label)}',
  category: '${normalizeCategory(spec.category)}',
  description: '${escape(spec.description)}',
  llmDescription: ${tsString(spec.llmDescription)},
  llmExamples: ${json(spec.llmExamples, 2)},
  configSchema: ${json(spec.configSchema, 2)},
  defaultConfig: ${json(spec.defaultConfig, 2)},
  basicConfig: [
${basicConfigStr}
  ],
};
`;
}

function fieldToBasicConfig(field: UISchemaField): string | null {
  // Maps curate UI-schema widget identifiers to valid BasicConfigField.type
  // values (see src/lib/workflows/types.ts). Widgets without a direct project
  // equivalent (credential-picker, resource-picker, datetime) fall back to
  // plain 'text' — the panel-level Svelte component handles richer rendering.
  const typeMap: Record<string, string> = {
    'string': 'text',
    'textarea': 'textarea',
    'dropdown': 'dropdown',
    'toggle': 'toggle',
    'datetime': 'text',
    'credential-picker': 'text',
    'resource-picker': 'text',
    'template-string': 'template-textarea',
  };
  const t = typeMap[field.widget] ?? 'text';
  const parts = [
    `{ key: '${field.key}'`,
    `label: '${escape(field.label)}'`,
    `type: '${t}'`,
  ];
  if ('description' in field && field.description) {
    parts.push(`description: ${tsString(field.description)}`);
  }
  // BasicConfigField has no `required` field — required-ness lives on the
  // JSON configSchema's `required` array. Don't emit it on the basicConfig
  // entry or tsc rejects the literal.
  return `${parts.join(', ')} }`;
}

function camel(kebab: string): string {
  return kebab.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function escape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function tsString(s: string): string {
  if (s.includes('\n')) return '`' + s.replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
  return `'${escape(s)}'`;
}

function json(value: unknown, indent: number): string {
  return JSON.stringify(value, null, indent).replace(/\n/g, '\n  ');
}
