// Generated by curate-codegen emitter. Do not hand-edit this file.
import type {
  NodeSpec,
  UISchema,
  UISchemaSection,
  UISchemaField,
  UISchemaBanner,
  UISchemaAction,
  Condition,
} from '../spec/types';

export function emitPanel(spec: NodeSpec): string {
  const parts: string[] = [];

  parts.push(emitScript(spec));
  parts.push('');

  const banners = emitBanners(spec.uiSchema.banners ?? []);
  if (banners) parts.push(banners);

  const topActions = emitActions(spec.uiSchema.actions ?? [], 'top');
  if (topActions) parts.push(topActions);

  parts.push(emitSections(spec.uiSchema.sections));
  parts.push('');
  parts.push(STYLE);

  return parts.join('\n');
}

// ── Script block ──────────────────────────────────────────────────────────

function emitScript(spec: NodeSpec): string {
  const widgets = collectUsedWidgets(spec);
  const hasBannerStatus = (spec.uiSchema.banners ?? []).some((b) => b.kind === 'credential-status');
  const hasTestConnection = (spec.uiSchema.actions ?? []).some((a) => a.kind === 'test-connection');

  const imports: string[] = [
    `import type { NodeDefinition } from '$lib/workflows/types';`,
  ];
  if (widgets.has('credential-picker')) {
    imports.push(`import CredentialPicker from '$lib/canvas/nodes/panels/widgets/CredentialPicker.svelte';`);
  }
  if (widgets.has('resource-picker')) {
    imports.push(`import ResourcePicker from '$lib/canvas/nodes/panels/shared/ResourcePicker.svelte';`);
  }
  if (widgets.has('template-string')) {
    imports.push(`import TemplatedInput from '$lib/canvas/nodes/panels/shared/TemplatedInput.svelte';`);
  }
  if (hasBannerStatus) {
    imports.push(`import CredentialStatusBanner from '$lib/canvas/nodes/panels/widgets/CredentialStatusBanner.svelte';`);
  }
  if (hasTestConnection) {
    imports.push(`import TestConnectionAction from '$lib/canvas/nodes/panels/widgets/TestConnectionAction.svelte';`);
  }

  const importBlock = imports.map((l) => `  ${l}`).join('\n');

  return `<script lang="ts">
${importBlock}

  interface Props {
    config: Record<string, unknown>;
    onChange: (next: Record<string, unknown>) => void;
    definition?: NodeDefinition;
    nodeId?: string;
    workflowId?: string;
    upstreamFields?: string[];
  }
  let { config, onChange, definition, nodeId, workflowId, upstreamFields }: Props = $props();

  function set(key: string, value: unknown) {
    onChange({ ...config, [key]: value });
  }

  function evalCond(cond: any): boolean {
    if (!cond) return true;
    if (cond.kind === 'eq') return config[cond.field] === cond.value;
    if (cond.kind === 'neq') return config[cond.field] !== cond.value;
    if (cond.kind === 'in') return cond.values.includes(config[cond.field]);
    if (cond.kind === 'not-in') return !cond.values.includes(config[cond.field]);
    if (cond.kind === 'and') return cond.conditions.every(evalCond);
    if (cond.kind === 'or') return cond.conditions.some(evalCond);
    return true;
  }
</script>`;
}

function collectUsedWidgets(spec: NodeSpec): Set<string> {
  const s = new Set<string>();
  for (const section of spec.uiSchema.sections) {
    for (const field of section.fields) s.add(field.widget);
  }
  return s;
}

// ── Banners ───────────────────────────────────────────────────────────────

function emitBanners(banners: UISchemaBanner[]): string {
  return banners
    .map((b) => {
      if (b.kind === 'credential-status') {
        return `<CredentialStatusBanner credentialId={config.${b.credentialField} as string | undefined} />`;
      }
      return '';
    })
    .filter(Boolean)
    .join('\n');
}

// ── Actions ───────────────────────────────────────────────────────────────

function emitActions(actions: UISchemaAction[], placement: 'top' | 'inline'): string {
  return actions
    .filter((a) => a.placement === placement)
    .map((a) => {
      if (a.kind === 'test-connection') {
        return `<TestConnectionAction integrationType="${a.integrationType}" credentialId={config.${a.credentialField} as string | undefined} />`;
      }
      return '';
    })
    .filter(Boolean)
    .join('\n');
}

// ── Sections ──────────────────────────────────────────────────────────────

function emitSections(sections: UISchemaSection[]): string {
  return sections.map(emitSection).join('\n\n');
}

function emitSection(section: UISchemaSection): string {
  const condStr = section.showWhen ? condJson(section.showWhen) : null;
  const intro = section.intro
    ? `  <p class="section-intro">${escapeHtml(section.intro)}</p>\n`
    : '';
  const fields = section.fields.map(emitField).join('\n');

  const inner = [
    `<section class="config-section">`,
    `  <h3>${escapeHtml(section.title)}</h3>`,
    intro ? intro.trimEnd() : null,
    fields,
    `</section>`,
  ].filter((x): x is string => x !== null).join('\n');

  if (condStr) {
    return `{#if evalCond(${condStr})}\n${inner}\n{/if}`;
  }
  return inner;
}

// ── Fields ────────────────────────────────────────────────────────────────

function emitField(field: UISchemaField): string {
  const labelHtml = `<label>${escapeHtml(field.label)}${field.required ? ' <span class="req">*</span>' : ''}</label>`;
  const descHtml = 'description' in field && field.description
    ? `  <p class="hint">${escapeHtml(field.description)}</p>`
    : null;
  const widgetHtml = emitWidget(field);

  const fieldLines = [
    `  <div class="field">`,
    `    ${labelHtml}`,
    descHtml ? `    ${descHtml}` : null,
    `    ${widgetHtml}`,
    `  </div>`,
  ].filter((x): x is string => x !== null).join('\n');

  if (field.showWhen) {
    return `  {#if evalCond(${condJson(field.showWhen)})}\n${fieldLines}\n  {/if}`;
  }
  return fieldLines;
}

function emitWidget(field: UISchemaField): string {
  switch (field.widget) {
    case 'string': {
      const ph = escapeHtml('placeholder' in field ? (field.placeholder ?? '') : '');
      return `<input class="nm-text-input" type="text" placeholder="${ph}" value={(config.${field.key} as string | undefined) ?? ''} oninput={(e) => set('${field.key}', (e.currentTarget as HTMLInputElement).value)} />`;
    }
    case 'textarea': {
      const ph = escapeHtml('placeholder' in field ? (field.placeholder ?? '') : '');
      const rows = 'rows' in field ? (field.rows ?? 4) : 4;
      return `<textarea class="nm-text-input" rows="${rows}" placeholder="${ph}" value={(config.${field.key} as string | undefined) ?? ''} oninput={(e) => set('${field.key}', (e.currentTarget as HTMLTextAreaElement).value)}></textarea>`;
    }
    case 'dropdown': {
      const opts = (field as { options: { value: string; label: string }[] }).options
        .map((o) => `<option value="${escapeHtml(o.value)}">${escapeHtml(o.label)}</option>`)
        .join('');
      return `<select class="nm-text-input" value={(config.${field.key} as string | undefined) ?? ''} onchange={(e) => set('${field.key}', (e.currentTarget as HTMLSelectElement).value)}>${opts}</select>`;
    }
    case 'toggle':
      return `<input type="checkbox" checked={!!config.${field.key}} onchange={(e) => set('${field.key}', (e.currentTarget as HTMLInputElement).checked)} />`;
    case 'datetime':
      return `<input class="nm-text-input" type="datetime-local" value={(config.${field.key} as string | undefined) ?? ''} oninput={(e) => set('${field.key}', (e.currentTarget as HTMLInputElement).value)} />`;
    case 'credential-picker': {
      const f = field as { integrationType: string };
      return `<CredentialPicker integrationType="${f.integrationType}" value={config.${field.key} as string | undefined} onChange={(id) => set('${field.key}', id)} />`;
    }
    case 'resource-picker': {
      const f = field as { credentialKey: string; integrationType: string };
      return `<ResourcePicker integrationType="${f.integrationType}" fieldName="${field.key}" credentialId={config.${f.credentialKey} as string | undefined} value={config.${field.key} as string | undefined} onChange={(v) => set('${field.key}', v)} />`;
    }
    case 'template-string': {
      const ph = escapeHtml('placeholder' in field ? (field.placeholder ?? '') : '');
      return `<TemplatedInput value={(config.${field.key} as string | undefined) ?? ''} placeholder="${ph}" {upstreamFields} onChange={(v) => set('${field.key}', v)} />`;
    }
  }
}

// ── Style block ───────────────────────────────────────────────────────────

const STYLE = `<style>
  .config-section { margin-bottom: 1rem; }
  .config-section h3 { margin: 0 0 0.25rem; font-size: 0.85rem; font-weight: 600; }
  .section-intro { color: var(--nm-muted, #666); font-size: 0.85rem; margin: 0 0 0.5rem; }
  .field { display: flex; flex-direction: column; gap: 0.25rem; margin-bottom: 0.5rem; }
  .field label { font-size: 0.85rem; }
  .req { color: var(--nm-status-error, #c0392b); }
  .hint { font-size: 0.8rem; color: var(--nm-muted, #666); margin: 0; }
</style>`;

// ── Helpers ───────────────────────────────────────────────────────────────

function condJson(cond: Condition): string {
  return JSON.stringify(cond).replace(/"/g, "'");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
