import type { CredentialKind } from './types';

export type ManualCredentialField = {
  key: string;
  label: string;
  type: 'text' | 'password';
  placeholder?: string;
};

/**
 * Declarative config for creating a NON-OAuth credential (apikey / basic) for an
 * integration whose adapter has no `oauthSpec`. Drives the "+ Connect" form on
 * /admin/connections/credentials and is validated by the create route.
 *
 * Kept here — hand-owned and keyed by integrationType — rather than on the
 * adapter objects, because adapter files under `adapters/` are generated by
 * node-builder-codegen ("do not hand-edit"). This is the one place to add a new
 * apikey/basic integration's connect form.
 *
 * Contract: for `kind: 'basic'` declare fields with keys `username` + `password`;
 * for `kind: 'apikey'` declare a single field with key `key`. The create route
 * builds the encrypted payload from exactly those keys.
 */
export type ManualCredentialSpec = {
  kind: Exclude<CredentialKind, 'oauth2'>;
  fields: ManualCredentialField[];
  helpText?: string;
  helpUrl?: string;
};

export const MANUAL_CREDENTIAL_SPECS: Record<string, ManualCredentialSpec> = {
  mapbox: {
    kind: 'apikey',
    fields: [{ key: 'key', label: 'Mapbox public access token', type: 'password', placeholder: 'pk.…' }],
    helpText: 'Use a public (pk.) token with styles:read and fonts:read, restricted to this site’s URLs (and localhost for preview). Stored encrypted here, then sent to browsers to render maps. Secret (sk.) tokens are not accepted. The newest Mapbox credential is used sitewide.',
    helpUrl: 'https://docs.mapbox.com/help/dive-deeper/access-tokens/',
  },
  'apple-calendar': {
    kind: 'basic',
    fields: [
      { key: 'username', label: 'Apple ID', type: 'text', placeholder: 'you@icloud.com' },
      { key: 'password', label: 'App-specific password', type: 'password', placeholder: 'xxxx-xxxx-xxxx-xxxx' },
    ],
    helpText:
      'iCloud needs an app-specific password (not your normal Apple ID password). Create one at appleid.apple.com → Sign-In and Security → App-Specific Passwords.',
    helpUrl: 'https://support.apple.com/en-us/102654',
  },
};

export function getManualCredentialSpec(integrationType: string): ManualCredentialSpec | undefined {
  return MANUAL_CREDENTIAL_SPECS[integrationType];
}
