// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import type { NodeDefinition } from '$lib/workflows/types';

export const appleCalendarDef: NodeDefinition = {
  type: 'apple-calendar',
  label: 'Apple Calendar',
  category: 'integration',
  description: 'Read and write events on iCloud calendars via CalDAV.',
  inputs: [{ name: 'input', type: 'any', label: 'Input' }],
  outputs: [{ name: 'output', type: 'object', label: 'Apple Calendar result' }],
  llmDescription: 'Use to fetch events for a date range or to create / update / delete events on an iCloud calendar. Authenticated via app-specific password (basic auth, kind=basic in integrationCredentials).',
  llmExamples: [
    {
      "scenario": "List events in the next 7 days",
      "config": {
        "credentialId": "<id>",
        "operation": "list",
        "calendar": "<url>",
        "dateRangeStart": "{{today}}",
        "dateRangeEnd": "{{nextWeek}}"
      }
    },
    {
      "scenario": "Create a 1-hour event tomorrow at 10am",
      "config": {
        "credentialId": "<id>",
        "operation": "create",
        "calendar": "<url>",
        "eventTitle": "Standup",
        "eventStart": "{{tomorrow10am}}",
        "eventEnd": "{{tomorrow11am}}"
      }
    }
  ],
  configSchema: {
    "type": "object",
    "properties": {
      "credentialId": {
        "type": "string"
      },
      "operation": {
        "type": "string",
        "enum": [
          "list",
          "create",
          "update",
          "delete"
        ]
      },
      "calendar": {
        "type": "string"
      },
      "dateRangeStart": {
        "type": "string"
      },
      "dateRangeEnd": {
        "type": "string"
      },
      "eventTitle": {
        "type": "string"
      },
      "eventStart": {
        "type": "string"
      },
      "eventEnd": {
        "type": "string"
      },
      "eventLocation": {
        "type": "string"
      },
      "eventNotes": {
        "type": "string"
      },
      "eventId": {
        "type": "string"
      }
    },
    "required": [
      "credentialId",
      "operation",
      "calendar"
    ]
  },
  defaultConfig: {
    "operation": "list"
  },
  basicConfig: [
    { key: 'credentialId', label: 'iCloud account', type: 'text' },
    { key: 'calendar', label: 'Calendar', type: 'text' },
    { key: 'operation', label: 'What to do', type: 'dropdown' },
    { key: 'dateRangeStart', label: 'From', type: 'template-textarea' },
    { key: 'dateRangeEnd', label: 'To', type: 'template-textarea' },
    { key: 'eventTitle', label: 'Title', type: 'template-textarea' },
    { key: 'eventStart', label: 'Start', type: 'template-textarea' },
    { key: 'eventEnd', label: 'End', type: 'template-textarea' },
    { key: 'eventLocation', label: 'Location', type: 'template-textarea' },
    { key: 'eventNotes', label: 'Notes', type: 'template-textarea' },
    { key: 'eventId', label: 'Event ID', type: 'text' }
  ],
};
