// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import { getCredential } from '$lib/integrations/credentials';
// Default-import interop: tsdav is CJS; a named import works under Vite's
// interop but breaks standalone tsx runs (run-eval.ts, scripts/*) on Node 22.
import tsdav from 'tsdav';
import ical from 'ical.js';

const { createDAVClient } = tsdav;

import type { NodeExecutor, NodeResult } from '$lib/workflows/types';
import { appleCalendarDef } from './apple-calendar.def';
export { appleCalendarDef } from './apple-calendar.def';

export interface CalendarEvent {
  id: string;
  title: string;
  location: string;
  start: string;
  end: string;
  description: string;
  /** Present only when the iCalendar body could not be read. */
  parseError?: string;
}

/**
 * Turn one CalDAV resource into an event row.
 *
 * `ICAL.parse` returns a jCal triple — `[name, properties, components]` — and
 * `ICAL.Component` expects that whole triple, not its third element. Passing
 * `jcal[2]` threw `Cannot read properties of undefined` on **every** event, and
 * a bare `catch` turned each throw into a row with a blank title, blank dates
 * and a blank description. So the list operation appeared to work, returned the
 * right NUMBER of events, and had never once returned a readable one. It went
 * unnoticed because a calendar of empty rows looks much like a quiet month.
 *
 * Extracted from the executor so it can be tested against a real iCalendar
 * body without a CalDAV server, which is what would have caught it.
 */
export function parseCalendarObject(url: string, data: string): CalendarEvent {
  const blank = { id: url, title: '', location: '', start: '', end: '', description: '' };
  try {
    const component = new ical.Component(ical.parse(data));
    // A VCALENDAR may carry VTIMEZONE and other siblings; take the event.
    const vevent = component.getFirstSubcomponent('vevent');
    if (!vevent) return { ...blank, parseError: 'no VEVENT in calendar object' };
    const event = new ical.Event(vevent);
    return {
      id: url,
      title: event.summary || '',
      location: event.location || '',
      start: event.startDate?.toJSDate()?.toISOString() || '',
      end: event.endDate?.toJSDate()?.toISOString() || '',
      description: event.description || '',
    };
  } catch (err) {
    // Still return a row — one malformed invite should not empty the list —
    // but say so, rather than pass a blank off as an event with no title.
    return { ...blank, parseError: err instanceof Error ? err.message : String(err) };
  }
}

/** ical.js accepts extended ISO values, while the workflow stores iCalendar basics. */
function icalTime(value: string): ical.Time {
  const date = value.match(/^(\d{4})(\d{2})(\d{2})$/);
  if (date) return ical.Time.fromString(`${date[1]}-${date[2]}-${date[3]}`);
  const dateTime = value.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z)?$/);
  if (dateTime) return ical.Time.fromString(`${dateTime[1]}-${dateTime[2]}-${dateTime[3]}T${dateTime[4]}:${dateTime[5]}:${dateTime[6]}${dateTime[7] ?? ''}`);
  return ical.Time.fromString(value);
}

export const appleCalendarExecutor: NodeExecutor = {
  type: 'apple-calendar',
  async execute(input, config: Record<string, any>, _ctx): Promise<NodeResult> {
    const cred = await getCredential<'basic'>(config.credentialId);
        if (!cred) throw new Error('Credential not found: ' + config.credentialId);
        if (cred.kind !== 'basic') throw new Error('Apple Calendar needs a basic credential');
        const client = await createDAVClient({
          serverUrl: 'https://caldav.icloud.com',
          credentials: { username: cred.payload.username, password: cred.payload.password },
          authMethod: 'Basic',
          defaultAccountType: 'caldav',
        });
        const calendars = await client.fetchCalendars();
        const target = calendars.find((c: any) => c.url === config.calendar);
        if (!target) throw new Error('Unknown calendar: ' + config.calendar);

        if (config.operation === 'list') {
          if (!target) throw new Error('No calendar selected');
          const objects = await client.fetchCalendarObjects({
            calendar: target,
            timeRange: { start: config.dateRangeStart, end: config.dateRangeEnd },
          });
          const events = objects.map((obj: any) => parseCalendarObject(obj.url, obj.data));
          return { output: { events }, rowCount: events.length };
        }
        if (config.operation === 'create') {
          const uid = config.eventUid || crypto.randomUUID();
          // A deterministic UID makes a retry safe. Check only this event's
          // requested range, then return the existing CalDAV resource.
          const existing = await client.fetchCalendarObjects({
            calendar: target!,
            timeRange: { start: config.duplicateRangeStart || config.eventStart, end: config.duplicateRangeEnd || config.eventEnd },
          });
          const duplicate = existing.find((obj: any) => obj.data?.includes('UID:' + uid));
          if (duplicate) {
            return { output: { id: uid, url: duplicate.url, title: config.eventTitle || '', calendar: target!.displayName || config.calendar, start: config.eventStart, end: config.eventEnd, duplicate: true }, rowCount: 1 };
          }
          const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
          // All-day events are dates, so they carry VALUE=DATE and no zone.
          // A timed event is expected to arrive as a UTC instant (…Z) and needs
          // no parameter at all. Deliberately NOT ';TZID=<zone>': RFC 5545 wants
          // a matching VTIMEZONE component for any zone referenced, this object
          // has none, and a CalDAV server may reject the lot on that basis.
          const datePrefix = config.allDay ? ';VALUE=DATE' : '';
          const icalStr = [
            'BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//jkai//EN', 'BEGIN:VEVENT',
            'UID:' + uid, 'DTSTAMP:' + now, 'DTSTART' + datePrefix + ':' + config.eventStart,
            'DTEND' + datePrefix + ':' + config.eventEnd, 'SUMMARY:' + (config.eventTitle || ''),
            ...(config.eventLocation ? ['LOCATION:' + config.eventLocation] : []),
            ...(config.eventNotes ? ['DESCRIPTION:' + config.eventNotes] : []),
            'END:VEVENT', 'END:VCALENDAR',
          ].join('\r\n');
          const resp = await client.createCalendarObject({
            calendar: target!,
            filename: uid + '.ics',
            iCalString: icalStr,
          });
          return { output: { id: uid, url: resp.headers?.get('Location') || uid, title: config.eventTitle || '', calendar: target!.displayName || config.calendar, start: config.eventStart, end: config.eventEnd }, rowCount: 1 };
        }
        if (config.operation === 'update' || config.operation === 'delete') {
          // Looking up the resource through the selected calendar is deliberate:
          // an event URL from another calendar (or credential) must never become
          // a capability to modify it.
          const objects = await client.fetchCalendarObjects({ calendar: target! });
          const calendarObject = objects.find((object: any) => object.url === config.eventId);
          if (!calendarObject) throw new Error('Event not found in the selected calendar.');
          const existing = parseCalendarObject(calendarObject.url, calendarObject.data);
          if (existing.parseError) throw new Error(`Unable to read event: ${existing.parseError}`);
          const metadata = { id: existing.id, title: existing.title, calendar: target!.displayName || config.calendar, start: existing.start, end: existing.end, location: existing.location, notes: existing.description };
          if (config.operation === 'delete') {
            await client.deleteCalendarObject({ calendarObject: { url: calendarObject.url, etag: calendarObject.etag || '*' } });
            return { output: { ...metadata, deleted: true }, rowCount: 1 };
          }

          const component = new ical.Component(ical.parse(calendarObject.data));
          const event = component.getFirstSubcomponent('vevent');
          if (!event) throw new Error('Event not found in calendar object.');
          const has = (key: string) => Object.prototype.hasOwnProperty.call(config, key);
          const setText = (name: string, value: string) => {
            if (value) event.updatePropertyWithValue(name, value);
            else event.removeAllProperties(name);
          };
          if (has('eventTitle')) setText('summary', config.eventTitle);
          if (has('eventLocation')) setText('location', config.eventLocation);
          if (has('eventNotes')) setText('description', config.eventNotes);
          const allDay = config.allDay === true;
          for (const [name, value] of [['dtstart', config.eventStart], ['dtend', config.eventEnd]] as const) {
            if (!has(name === 'dtstart' ? 'eventStart' : 'eventEnd')) continue;
            const property = event.updatePropertyWithValue(name, icalTime(value));
            property.removeParameter('tzid');
            if (allDay) property.setParameter('value', 'date');
            else property.removeParameter('value');
          }
          const data = component.toString();
          await client.updateCalendarObject({
            calendarObject: { url: calendarObject.url, etag: calendarObject.etag || '*', data },
          });
          const updated = parseCalendarObject(calendarObject.url, data);
          return { output: { id: updated.id, title: updated.title, calendar: target!.displayName || config.calendar, start: updated.start, end: updated.end, location: updated.location, notes: updated.description }, rowCount: 1 };
        }
        throw new Error('Unknown operation: ' + config.operation);
  },
  getInputSchema: () => appleCalendarDef.configSchema,
  getOutputSchema: () => ({
    "type": "object",
    "properties": {
      "events": {
        "type": "array"
      },
      "id": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "etag": {
        "type": "string"
      }
    }
  }),
};

export async function resolveOptions_calendar(credentialId: string): Promise<{ value: string; label: string }[]> {
  const cred = await getCredential<'basic'>(credentialId);
        if (!cred) return [];
        const client = await createDAVClient({
          serverUrl: 'https://caldav.icloud.com',
          credentials: { username: cred.payload.username, password: cred.payload.password },
          authMethod: 'Basic',
          defaultAccountType: 'caldav',
        });
        const calendars = await client.fetchCalendars();
        return calendars.map((c: any) => ({ value: c.url, label: c.displayName || c.url }));
}