// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import { getCredential } from '$lib/integrations/credentials';
// Default-import interop: tsdav is CJS; a named import works under Vite's
// interop but breaks standalone tsx runs (run-eval.ts, scripts/*) on Node 22.
import tsdav from 'tsdav';
import ical from 'ical.js';

const { createDAVClient } = tsdav;

import type { NodeExecutor, NodeResult } from '$lib/workflows/types';
import { appleCalendarDef } from './apple-calendar.def';
export { appleCalendarDef } from './apple-calendar.def';

export const appleCalendarExecutor: NodeExecutor = {
  type: 'apple-calendar',
  async execute(input, config: Record<string, any>, _ctx): Promise<NodeResult> {
    const cred = await getCredential<'basic'>(config.credentialId);
        if (!cred) throw new Error('Credential not found: ' + config.credentialId);
        if (cred.kind !== 'basic') throw new Error('Apple Calendar needs a basic credential');
        const client = await createDAVClient({
          serverUrl: 'https://caldav.icloud.com',
          credentials: { username: cred.payload.username, password: cred.payload.password },
          authMethod: 'Basic',
          defaultAccountType: 'caldav',
        });
        const calendars = await client.fetchCalendars();
        const target = calendars.find((c: any) => c.url === config.calendar);
        if (!target) throw new Error('Unknown calendar: ' + config.calendar);

        if (config.operation === 'list') {
          if (!target) throw new Error('No calendar selected');
          const objects = await client.fetchCalendarObjects({
            calendar: target,
            timeRange: { start: config.dateRangeStart, end: config.dateRangeEnd },
          });
          const events = objects.map((obj: any) => {
            try {
              const jcal = ical.parse(obj.data);
              const vcomp = new ical.Component(jcal[2]);
              const vevent = new ical.Event(vcomp);
              return {
                id: obj.url,
                title: vevent.summary || '',
                location: vevent.location || '',
                start: vevent.startDate?.toJSDate()?.toISOString() || '',
                end: vevent.endDate?.toJSDate()?.toISOString() || '',
                description: vevent.description || '',
              };
            } catch {
              return { id: obj.url, title: '', location: '', start: '', end: '', description: '' };
            }
          });
          return { output: { events }, rowCount: events.length };
        }
        if (config.operation === 'create') {
          const uid = config.eventUid || crypto.randomUUID();
          // A deterministic UID makes a retry safe. Check only this event's
          // requested range, then return the existing CalDAV resource.
          const existing = await client.fetchCalendarObjects({
            calendar: target!,
            timeRange: { start: config.duplicateRangeStart || config.eventStart, end: config.duplicateRangeEnd || config.eventEnd },
          });
          const duplicate = existing.find((obj: any) => obj.data?.includes('UID:' + uid));
          if (duplicate) {
            return { output: { id: uid, url: duplicate.url, title: config.eventTitle || '', calendar: target!.displayName || config.calendar, start: config.eventStart, end: config.eventEnd, duplicate: true }, rowCount: 1 };
          }
          const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
          const datePrefix = config.allDay ? ';VALUE=DATE' : config.timezone ? ';TZID=' + config.timezone : '';
          const icalStr = [
            'BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//jkai//EN', 'BEGIN:VEVENT',
            'UID:' + uid, 'DTSTAMP:' + now, 'DTSTART' + datePrefix + ':' + config.eventStart,
            'DTEND' + datePrefix + ':' + config.eventEnd, 'SUMMARY:' + (config.eventTitle || ''),
            ...(config.eventLocation ? ['LOCATION:' + config.eventLocation] : []),
            ...(config.eventNotes ? ['DESCRIPTION:' + config.eventNotes] : []),
            'END:VEVENT', 'END:VCALENDAR',
          ].join('\r\n');
          const resp = await client.createCalendarObject({
            calendar: target!,
            filename: uid + '.ics',
            iCalString: icalStr,
          });
          return { output: { id: uid, url: resp.headers?.get('Location') || uid, title: config.eventTitle || '', calendar: target!.displayName || config.calendar, start: config.eventStart, end: config.eventEnd }, rowCount: 1 };
        }
        if (config.operation === 'update') {
          const uid = crypto.randomUUID();
          const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
          const icalStr = [
            'BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//jkai//EN', 'BEGIN:VEVENT',
            'UID:' + uid, 'DTSTAMP:' + now, 'DTSTART:' + config.eventStart,
            'DTEND:' + config.eventEnd, 'SUMMARY:' + (config.eventTitle || ''),
            ...(config.eventLocation ? ['LOCATION:' + config.eventLocation] : []),
            ...(config.eventNotes ? ['DESCRIPTION:' + config.eventNotes] : []),
            'END:VEVENT', 'END:VCALENDAR',
          ].join('\r\n');
          const resp = await client.updateCalendarObject({
            calendarObject: { url: config.eventId, etag: '*', data: icalStr },
          });
          return { output: { id: config.eventId }, rowCount: 1 };
        }
        if (config.operation === 'delete') {
          await client.deleteCalendarObject({
            calendarObject: { url: config.eventId, etag: '*' },
          });
          return { output: { id: config.eventId }, rowCount: 1 };
        }
        throw new Error('Unknown operation: ' + config.operation);
  },
  getInputSchema: () => appleCalendarDef.configSchema,
  getOutputSchema: () => ({
    "type": "object",
    "properties": {
      "events": {
        "type": "array"
      },
      "id": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "etag": {
        "type": "string"
      }
    }
  }),
};

export async function resolveOptions_calendar(credentialId: string): Promise<{ value: string; label: string }[]> {
  const cred = await getCredential<'basic'>(credentialId);
        if (!cred) return [];
        const client = await createDAVClient({
          serverUrl: 'https://caldav.icloud.com',
          credentials: { username: cred.payload.username, password: cred.payload.password },
          authMethod: 'Basic',
          defaultAccountType: 'caldav',
        });
        const calendars = await client.fetchCalendars();
        return calendars.map((c: any) => ({ value: c.url, label: c.displayName || c.url }));
}