import type { NodeDefinition } from '../types';

export const gmailReplyDef: NodeDefinition = {
  type: 'gmail-reply',
  category: 'integration',
  label: 'Gmail — Reply to Message',
  description: 'Send a reply to an existing Gmail thread, preserving In-Reply-To and References headers for proper threading.',
  defaultConfig: {
    accountId: 0,
    to: '{{input.from}}',
    threadId: '{{input.threadId}}',
    inReplyTo: '{{input.rfc822MessageId}}',
    references: '',
    subject: '{{input.subject}}',
    bodyText: '',
    bodyHtml: '',
  },
  inputs: [{ name: 'input', type: 'any', label: 'Input' }],
  outputs: [{ name: 'output', type: 'object', label: 'Send result' }],
  configSchema: {
    type: 'object',
    required: ['accountId', 'to', 'threadId', 'inReplyTo', 'subject'],
    properties: {
      accountId: { type: 'number', description: 'Gmail account row id' },
      to: { type: 'string', description: 'Recipient address. Defaults to {{input.from}} (supports {{input.x}})' },
      threadId: { type: 'string', description: 'Gmail thread id to reply in (supports {{input.x}})' },
      inReplyTo: { type: 'string', description: 'RFC 822 Message-ID of the message being replied to (supports {{input.x}})' },
      references: { type: 'string', description: 'References header — defaults to inReplyTo value if empty (supports {{input.x}})' },
      subject: { type: 'string', description: 'Subject line (supports {{input.x}})' },
      bodyText: { type: 'string', description: 'Plain-text body (supports {{input.x}})' },
      bodyHtml: { type: 'string', description: 'HTML body (supports {{input.x}})' },
    },
  },
  llmDescription: 'Sends a reply to an existing Gmail thread, preserving In-Reply-To and References headers so mail clients show it as a continuation of the conversation. Use this instead of gmail-send whenever replying to a received message. Requires threadId and inReplyTo from the upstream trigger or fetch output — both are available from gmail-trigger output directly. The defaults already template these fields from {{input.threadId}} and {{input.rfc822MessageId}}, so the minimal config is just accountId and bodyText. Output: { messageId, threadId, success }.',
  llmExamples: [
    {
      accountId: 1,
      to: '{{trigger.output.from}}',
      threadId: '{{trigger.output.threadId}}',
      inReplyTo: '{{nodes.fetch.output.rfc822MessageId}}',
      subject: '{{trigger.output.subject}}',
      bodyText: 'Thank you for your email. We have received your request and will respond within 2 business days.',
    },
    {
      accountId: 1,
      to: '{{input.from}}',
      threadId: '{{input.threadId}}',
      inReplyTo: '{{input.rfc822MessageId}}',
      subject: '{{input.subject}}',
      bodyHtml: '<p>{{nodes.llm.output.text}}</p>',
    },
    {
      accountId: 1,
      to: '{{trigger.output.from}}',
      threadId: '{{trigger.output.threadId}}',
      inReplyTo: '{{trigger.output.messageId}}',
      subject: 'Re: {{trigger.output.subject}}',
      bodyText: '{{nodes.compose.output.text}}',
    },
  ],
  basicConfig: [
    {
      key: 'accountId',
      label: 'Gmail Account',
      type: 'number',
      description: 'The gmail_accounts row id for the sending account.',
    },
    {
      key: 'to',
      label: 'To',
      type: 'template-textarea',
      placeholder: '{{trigger.output.from}}',
      description: 'Recipient address. Typically {{trigger.output.from}} to reply to the sender.',
    },
    {
      key: 'threadId',
      label: 'Thread ID',
      type: 'template-textarea',
      placeholder: '{{trigger.output.threadId}}',
      description: 'Gmail thread id to reply in. Taken from trigger or fetch output.',
    },
    {
      key: 'inReplyTo',
      label: 'In-Reply-To',
      type: 'template-textarea',
      placeholder: '{{nodes.fetch.output.rfc822MessageId}}',
      description: 'RFC 822 Message-ID of the message being replied to. Needed for proper threading.',
    },
    {
      key: 'subject',
      label: 'Subject',
      type: 'template-textarea',
      placeholder: '{{trigger.output.subject}}',
      description: 'Subject line. Usually the original subject (Re: is added automatically by mail clients).',
    },
    {
      key: 'bodyText',
      label: 'Body (plain text)',
      type: 'template-textarea',
      placeholder: 'Thanks for getting in touch...',
      description: 'Plain-text reply body. Supports templates.',
    },
  ],
};
