import type { NodeDefinition } from '../types';

export const gmailSendDef: NodeDefinition = {
  type: 'gmail-send',
  category: 'integration',
  label: 'Gmail — Send Message',
  description: 'Compose and send a new Gmail message. Supports template interpolation for recipient, subject, and body.',
  defaultConfig: {
    accountId: 0,
    to: '',
    subject: '',
    bodyText: '',
    bodyHtml: '',
    cc: '',
    bcc: '',
  },
  inputs: [{ name: 'input', type: 'any', label: 'Input' }],
  outputs: [{ name: 'output', type: 'object', label: 'Send result' }],
  configSchema: {
    type: 'object',
    required: ['accountId', 'to', 'subject'],
    properties: {
      accountId: { type: 'number', description: 'Gmail account row id' },
      to: { type: 'string', description: 'Recipient address (supports {{input.x}})' },
      subject: { type: 'string', description: 'Subject line (supports {{input.x}})' },
      bodyText: { type: 'string', description: 'Plain-text body (supports {{input.x}})' },
      bodyHtml: { type: 'string', description: 'HTML body (supports {{input.x}})' },
      cc: { type: 'string', description: 'CC address(es)' },
      bcc: { type: 'string', description: 'BCC address(es)' },
    },
  },
  llmDescription: 'Composes and sends a new Gmail message (fresh thread, not a reply). Use for outbound notifications, alerts, or forwarding content to a recipient. All fields support {{input.x}} templates. Use gmail-reply instead when you need to reply in an existing thread — gmail-send always starts a new conversation. Output: { messageId, threadId, success }. Pitfall: if accountId is wrong or the account\'s OAuth token is expired, the node will fail — check /admin/gmail to confirm the account is connected.',
  llmExamples: [
    {
      accountId: 1,
      to: 'john@example.com',
      subject: 'Daily job digest — {{input.date}}',
      bodyText: '{{input.summary}}',
    },
    {
      accountId: 1,
      to: '{{trigger.output.from}}',
      subject: 'Re: {{trigger.output.subject}}',
      bodyHtml: '<p>Thanks for your message. We will get back to you shortly.</p>',
    },
    {
      accountId: 1,
      to: 'team@example.com',
      subject: 'Alert: {{input.alertTitle}}',
      bodyText: '{{input.alertBody}}',
      cc: 'manager@example.com',
    },
  ],
  basicConfig: [
    {
      key: 'accountId',
      label: 'Gmail Account',
      type: 'number',
      description: 'The gmail_accounts row id for the sending account.',
    },
    {
      key: 'to',
      label: 'To',
      type: 'template-textarea',
      placeholder: 'alice@example.com',
      description: 'Recipient address. Supports {{input.x}} templates.',
    },
    {
      key: 'subject',
      label: 'Subject',
      type: 'template-textarea',
      placeholder: 'Daily digest for {{input.date}}',
      description: 'Email subject line. Supports templates.',
    },
    {
      key: 'bodyText',
      label: 'Body (plain text)',
      type: 'template-textarea',
      placeholder: 'Hello,\n\n{{input.summary}}',
      description: 'Plain-text email body. Supports templates.',
    },
    {
      key: 'bodyHtml',
      label: 'Body (HTML)',
      type: 'template-textarea',
      placeholder: '<p>{{input.summary}}</p>',
      description: 'HTML email body. If both bodyText and bodyHtml are set, both parts are sent.',
      section: 'ADVANCED',
      advancedOnly: true,
    },
    {
      key: 'cc',
      label: 'CC',
      type: 'text',
      placeholder: 'other@example.com',
      description: 'Optional CC address(es).',
      section: 'ADVANCED',
      advancedOnly: true,
    },
  ],
};
