// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import type { NodeDefinition } from '$lib/workflows/types';

export const icloudCalDef: NodeDefinition = {
  type: 'icloud-cal',
  label: 'iCloud Calendar',
  category: 'integration',
  description: 'Fetch upcoming events from an iCloud Calendar via CalDAV. Authenticates with an Apple ID and app-specific password (stored as a Basic Auth credential). Supports listing available calendars and fetching events with time-range filtering.',
  inputs: [{ name: 'input', type: 'any', label: 'Input' }],
  outputs: [{ name: 'output', type: 'object', label: 'iCloud Calendar result' }],
  llmDescription: 'Use this node when the user wants to interact with their iCloud Calendar — view upcoming events, list their calendars, or check what\'s on their schedule. Requires an app-specific password credential (integrationType: icloud-cal, kind: basic). Common patterns: (1) list_calendars to discover available calendar URLs, (2) fetch_events with a calendar URL to get upcoming events, (3) wire fetch_events output downstream to an LLM for scheduling decisions or to a whatsapp node for daily briefings.',
  llmExamples: [
    {
      "scenario": "Daily schedule briefing",
      "config": {
        "operation": "fetch_events",
        "calendarUrl": "{{input.calendarUrl}}",
        "days": 1
      },
      "notes": "Fetch today's events and pass to an LLM or WhatsApp for a morning briefing."
    },
    {
      "scenario": "Discover user's calendars",
      "config": {
        "operation": "list_calendars"
      },
      "notes": "Returns all calendar URLs and names. Use this first to find the right calendarUrl for fetch_events."
    },
    {
      "scenario": "Weekly planning overview",
      "config": {
        "operation": "fetch_events",
        "calendarUrl": "{{input.calendarUrl}}",
        "days": 7
      },
      "notes": "Fetch events for the next week for weekly planning."
    }
  ],
  configSchema: {
    "type": "object",
    "properties": {
      "credentialId": {
        "type": "string",
        "description": "ID of the iCloud credential (Basic Auth: Apple ID + app-specific password)"
      },
      "operation": {
        "type": "string",
        "description": "Operation: list_calendars or fetch_events"
      },
      "calendarUrl": {
        "type": "string",
        "description": "CalDAV calendar URL. Use list_calendars to discover."
      },
      "days": {
        "type": "number",
        "description": "Days to look ahead (and back from now). Default 7."
      }
    },
    "required": [
      "credentialId",
      "operation"
    ]
  },
  defaultConfig: {
    "operation": "fetch_events",
    "days": 7
  },
  basicConfig: [
    { key: 'credentialId', label: 'iCloud Credential', type: 'text', description: 'Apple ID email + app-specific password. Create at /admin/integrations with type \'icloud-cal\' and kind \'basic\'.' },
    { key: 'operation', label: 'Operation', type: 'dropdown', description: 'What to do' },
    { key: 'calendarUrl', label: 'Calendar URL', type: 'text', description: 'Full CalDAV calendar URL from the list_calendars operation.' },
    { key: 'days', label: 'Days', type: 'text', description: 'How many days to look ahead (and back from now). Default: 7.' }
  ],
};
