// Generated by node-builder-codegen. Do not hand-edit; re-run node-builder-codegen to update.

import { getCredential } from '$lib/integrations/credentials';
import {
  createAccount,
  fetchCalendars,
  fetchCalendarObjects,
  getBasicAuthHeaders,
} from 'tsdav';
import type { DAVCalendarObject } from 'tsdav';
import ical from 'ical.js';

import type { NodeExecutor, NodeResult } from '$lib/workflows/types';
import { icloudCalDef } from './icloud-cal.def';
export { icloudCalDef } from './icloud-cal.def';

export const icloudCalExecutor: NodeExecutor = {
  type: 'icloud-cal',
  async execute(input, config: Record<string, any>, _ctx): Promise<NodeResult> {
    const credentialId = config.credentialId as string;
    if (!credentialId) throw new Error('iCloud Calendar credential is required. Add one at /admin/integrations.');

    const cred = await getCredential<'basic'>(credentialId);
    if (!cred) throw new Error(`Credential not found: ${credentialId}`);
    if (cred.kind !== 'basic') throw new Error('iCloud Calendar requires a Basic Auth credential (Apple ID + app-specific password).');

    const { username, password } = cred.payload;
    const serverUrl = 'https://p-caldav.icloud.com';
    const headers = getBasicAuthHeaders({ username, password });

    const account = await createAccount({
      account: { serverUrl, credentials: { username, password }, accountType: 'caldav' },
    });

    const operation = (config.operation as string) || 'fetch_events';

    // ── list_calendars ──────────────────────────────────────
    if (operation === 'list_calendars') {
      const calendars = await fetchCalendars({ account });
      return {
        output: {
          calendars: calendars.map((c: any) => ({
            url: c.url ?? '',
            name: c.displayName || c.description || 'Unnamed',
            description: c.description || '',
            color: c.color || '',
          })),
          count: calendars.length,
        },
      };
    }

    // ── fetch_events ────────────────────────────────────────
    if (operation === 'fetch_events') {
      const calendarUrl = (input?.calendarUrl as string) || (config.calendarUrl as string);
      if (!calendarUrl) throw new Error('calendarUrl is required for fetch_events. Use list_calendars first to discover available calendars.');

      const calendars = await fetchCalendars({ account });
      const calendar = calendars.find((c: any) => c.url === calendarUrl);
      if (!calendar) throw new Error(`Calendar not found: ${calendarUrl}. Use list_calendars to see available calendars.`);

      const days = (input?.days as number) || (config.days as number) || 7;
      const now = new Date();
      const start = new Date(now.getTime() - Math.max(0, days / 2) * 86_400_000);
      const end = new Date(now.getTime() + days * 86_400_000);

      const objects = await fetchCalendarObjects({
        calendar,
        timeRange: { start: start.toISOString(), end: end.toISOString() },
        expand: true,
        headers,
      });

      const calendarName = calendar.displayName || calendar.description || '';
      const events = objects.map((obj: any) => {
        const jcalData = ical.parse(obj.ical);
        const vcomp = new ical.Component(jcalData[2]);
        const vevent = new ical.Event(vcomp);
        const evtStart = vevent.startDate?.toJSDate();
        const evtEnd = vevent.endDate?.toJSDate();
        return {
          uid: vevent.uid || '',
          title: vevent.summary || '',
          start: evtStart?.toISOString() || '',
          end: evtEnd?.toISOString() || '',
          location: vevent.location || '',
          description: vevent.description || '',
          calendarName,
        };
      }).filter((e: any) => e.title);

      return {
        output: {
          events,
          count: events.length,
          range: { start: start.toISOString(), end: end.toISOString() },
        },
      };
    }

    throw new Error(`Unknown operation: ${operation}`);
  },
  getInputSchema: () => icloudCalDef.configSchema,
  getOutputSchema: () => ({
    "type": "object",
    "properties": {
      "events": {
        "type": "array",
        "description": "Array of calendar events (present when operation is fetch_events)",
        "items": {
          "type": "object",
          "properties": {
            "uid": {
              "type": "string",
              "description": "Event unique identifier"
            },
            "title": {
              "type": "string",
              "description": "Event title / summary"
            },
            "start": {
              "type": "string",
              "description": "Event start time (ISO 8601)"
            },
            "end": {
              "type": "string",
              "description": "Event end time (ISO 8601)"
            },
            "location": {
              "type": "string",
              "description": "Event location"
            },
            "description": {
              "type": "string",
              "description": "Event description / notes"
            },
            "calendarName": {
              "type": "string",
              "description": "Name of the calendar this event belongs to"
            }
          }
        }
      },
      "calendars": {
        "type": "array",
        "description": "Array of available calendars (present when operation is list_calendars)",
        "items": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "color": {
              "type": "string"
            }
          }
        }
      },
      "count": {
        "type": "number",
        "description": "Number of items returned"
      },
      "range": {
        "type": "object",
        "description": "Time range used for the query",
        "properties": {
          "start": {
            "type": "string"
          },
          "end": {
            "type": "string"
          }
        }
      }
    },
    "description": "Result object containing either calendars array or events array depending on operation"
  }),
};
