import type { NodeDefinition } from '../types';

export const llmCallDef: NodeDefinition = {
  type: 'llm-call',
  label: 'LLM Call',
  category: 'core',
  description: 'Call an LLM. Leave the model empty to use the same default as jkai (configured in admin → model defaults). Set an OpenRouter model ID to override. System and user prompts support {{input.field}} templates.',
  configSchema: {
    type: 'object',
    properties: {
      model: { type: 'string', description: 'Optional OpenRouter model ID (e.g. openai/gpt-4o-mini). Leave empty to use the jkai chat default, configured in admin.' },
      systemPrompt: { type: 'string', description: 'System prompt. Supports {{input.field}} templates.' },
      userPrompt: { type: 'string', description: 'User prompt. Supports {{input.field}} templates.' },
      temperature: { type: 'number', description: 'Sampling temperature 0–2 (default 0.7)' },
      maxTokens: { type: 'number', description: 'Max tokens to generate (default 1024)' },
    },
    required: ['userPrompt'],
  },
  defaultConfig: { model: '', systemPrompt: '', userPrompt: '', temperature: 0.7, maxTokens: 1024 },
  inputs: [{ name: 'input', type: 'any', label: 'Input' }],
  outputs: [{ name: 'output', type: 'object', label: 'Response' }],
  basicConfig: [
    {
      key: 'userPrompt',
      label: 'User Prompt',
      type: 'template-textarea',
      description: 'What you want the AI to do. Use {{input.field}} to insert upstream data.',
      placeholder: 'Summarise this text: {{input.text}}',
      section: 'PROMPT',
    },
    {
      key: 'systemPrompt',
      label: 'System Prompt',
      type: 'template-textarea',
      description: 'Optional instructions that set the AI\'s role or style.',
      placeholder: 'You are a helpful assistant that writes concise summaries.',
      section: 'PROMPT',
    },
    {
      key: 'model',
      label: 'Model',
      type: 'dropdown',
      description: 'Which LLM answers this step. Leave as default unless you need a specific one.',
      options: [
        { value: '', label: 'Default (use jkai default model)' },
        { value: 'openai/gpt-4o-mini', label: 'GPT-4o mini (fast, cheap)' },
        { value: 'openai/gpt-4o', label: 'GPT-4o (balanced)' },
        { value: 'anthropic/claude-3.5-sonnet', label: 'Claude 3.5 Sonnet' },
        { value: 'anthropic/claude-3.5-haiku', label: 'Claude 3.5 Haiku (fast)' },
        { value: 'google/gemini-2.0-flash-exp', label: 'Gemini 2.0 Flash' },
        { value: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B' },
      ],
    },
    {
      key: 'temperature',
      label: 'Temperature',
      type: 'slider',
      description: 'How creative the answers are. 0 is focused and deterministic, 2 is wild.',
      min: 0,
      max: 2,
      step: 0.1,
    },
    {
      key: 'maxTokens',
      label: 'Max Tokens',
      type: 'number',
      description: 'Maximum length of the AI response (roughly 4 characters per token).',
      min: 1,
      section: 'ADVANCED',
      advancedOnly: true,
    },
  ],
};
