import type { NodeDefinition } from '../types';

export const stravaDef: NodeDefinition = {
  type: 'strava',
  label: 'Strava',
  category: 'integration',
  description:
    'Access Strava activity data. Requires Strava connected in Health settings. Prefer DB-backed ops (get_summary, query_activities) — they are fast, free, and queryable; *_api ops hit the Strava API directly.',
  configSchema: {
    type: 'object',
    properties: {
      operation: {
        type: 'string',
        description:
          'get_summary | query_activities | list_activities | get_activity | get_athlete_stats',
      },
      days: { type: 'number', description: 'Trailing window for get_summary / query_activities' },
      sportType: { type: 'string', description: 'Filter by Strava sport_type (e.g. Run, Ride)' },
      minDistanceMeters: { type: 'number', description: 'Filter activities by min distance (meters)' },
      page: { type: 'number', description: 'Page number for list_activities (default 1)' },
      perPage: { type: 'number', description: 'Results per page for list_activities (default 30, max 200)' },
      activityId: { type: 'string', description: 'Activity ID for get_activity' },
      start: { type: 'string', description: 'ISO 8601 start date filter' },
      end: { type: 'string', description: 'ISO 8601 end date filter' },
    },
    required: ['operation'],
  },
  defaultConfig: { operation: 'get_summary', days: 30, page: 1, perPage: 30 },
  inputs: [{ name: 'input', type: 'any', label: 'Input' }],
  outputs: [{ name: 'output', type: 'object', label: 'Result' }],
  basicConfig: [
    {
      key: 'operation',
      label: 'Action',
      type: 'dropdown',
      description: 'What to do',
      options: [
        { value: 'get_summary', label: 'Summary (DB · totals over range)' },
        { value: 'query_activities', label: 'Query Activities (DB · filtered)' },
        { value: 'list_activities', label: 'List Activities — API' },
        { value: 'get_activity', label: 'Get Single Activity — API' },
        { value: 'get_athlete_stats', label: 'Athlete Stats — API' },
      ],
    },
    {
      key: 'days',
      label: 'Days',
      type: 'number',
      min: 1,
      description: 'Trailing window in days.',
      visibleWhen: { key: 'operation', in: ['get_summary', 'query_activities'] },
    },
    {
      key: 'sportType',
      label: 'Sport Type',
      type: 'text',
      placeholder: 'Run | Ride | TrailRun | …',
      description: 'Filter on sport_type (case-sensitive).',
      visibleWhen: { key: 'operation', in: ['get_summary', 'query_activities'] },
    },
    {
      key: 'minDistanceMeters',
      label: 'Min Distance (m)',
      type: 'number',
      min: 0,
      description: 'Skip activities shorter than this.',
      visibleWhen: { key: 'operation', equals: 'query_activities' },
    },
    {
      key: 'activityId',
      label: 'Activity ID',
      type: 'text',
      placeholder: '1234567890',
      description: 'ID of the Strava activity to fetch.',
      visibleWhen: { key: 'operation', equals: 'get_activity' },
    },
    {
      key: 'page',
      label: 'Page',
      type: 'number',
      min: 1,
      description: 'Page number of results (1 = first page).',
      visibleWhen: { key: 'operation', equals: 'list_activities' },
    },
    {
      key: 'perPage',
      label: 'Results Per Page',
      type: 'number',
      min: 1,
      max: 200,
      description: 'How many activities to return per page (max 200).',
      visibleWhen: { key: 'operation', equals: 'list_activities' },
    },
    {
      key: 'start',
      label: 'Start Date',
      type: 'template-textarea',
      section: 'FILTERS',
      placeholder: '2026-01-01T00:00:00Z',
      description: 'ISO 8601 start date filter (optional).',
      advancedOnly: true,
    },
    {
      key: 'end',
      label: 'End Date',
      type: 'template-textarea',
      placeholder: '2026-04-18T00:00:00Z',
      description: 'ISO 8601 end date filter (optional).',
      advancedOnly: true,
    },
  ],
  llmDescription: `Read Strava activity data (requires Strava connected in Health settings). Prefer the DB-backed ops — fast, free, and queryable: \`get_summary\` (totals over a range, optionally by sportType) and \`query_activities\` (filtered activity rows). The API ops — \`list_activities\`, \`get_activity\`, \`get_athlete_stats\` — hit the Strava API directly and are rate-limited. Read-only.`,
  llmExamples: [
    { operation: 'get_summary', days: 30, sportType: 'Run' },
    { operation: 'query_activities', days: 7 },
  ],
};
